In [26]:
import pandas as pd
import geopandas as gpd

# Read Excel file
file_path = "./coodinates site CMS.xlsx"
df = pd.read_excel(file_path)

df.head()

  Unnamed: 0          Unnamed: 1  Unnamed: 2 Unnamed: 3             Unnamed: 4
0      State  State/ Site Office   Latitude   Longitude                   Site
1       GJ K        Nanisindhodi   23.101889  68.805361  Nanisindhodi [109WTG]
2       GJ K             Suthari   23.034722  68.900056        Suthari [84WTG]
3       GJ K              Kadoli   23.059694  68.846806         Kadoli [87WTG]
4       GJ K             Lathedi   22.990917     69.037        Lathedi [93WTG]

In [27]:
# Fix headers - first row is the actual column names
df.columns = df.iloc[0]
df.columns = df.columns.str.strip() 
df = df.drop(index=0).reset_index(drop=True)

df.head()

0 State State/ Site Office   Latitude  Longitude                   Site
0  GJ K       Nanisindhodi  23.101889  68.805361  Nanisindhodi [109WTG]
1  GJ K            Suthari  23.034722  68.900056        Suthari [84WTG]
2  GJ K             Kadoli  23.059694  68.846806         Kadoli [87WTG]
3  GJ K            Lathedi  22.990917     69.037        Lathedi [93WTG]
4  GJ K              Vayor  23.414611  68.676722          Vayor [84WTG]

In [28]:
# Clean State column: extract 2-letter abbreviation, normalize Rajasthan -> RJ
def clean_state(val):
    val = str(val).strip()
    if val.lower().startswith("rajasthan"):
        return "RJ"
    return val[:2].upper()

df["State"] = df["State"].apply(clean_state)

df.head()

0 State State/ Site Office   Latitude  Longitude                   Site
0    GJ       Nanisindhodi  23.101889  68.805361  Nanisindhodi [109WTG]
1    GJ            Suthari  23.034722  68.900056        Suthari [84WTG]
2    GJ             Kadoli  23.059694  68.846806         Kadoli [87WTG]
3    GJ            Lathedi  22.990917     69.037        Lathedi [93WTG]
4    GJ              Vayor  23.414611  68.676722          Vayor [84WTG]

In [29]:
df.head()

0 State State/ Site Office   Latitude  Longitude                   Site
0    GJ       Nanisindhodi  23.101889  68.805361  Nanisindhodi [109WTG]
1    GJ            Suthari  23.034722  68.900056        Suthari [84WTG]
2    GJ             Kadoli  23.059694  68.846806         Kadoli [87WTG]
3    GJ            Lathedi  22.990917     69.037        Lathedi [93WTG]
4    GJ              Vayor  23.414611  68.676722          Vayor [84WTG]

In [30]:
# Inspect raw values for problematic rows
mask = df["State/ Site Office"] == "Kayathar"
print(repr(df.loc[mask, "Latitude"].values))
print(repr(df.loc[mask, "Longitude"].values))

array(['8.851736\xa0'], dtype=object)
array([77.809425], dtype=object)

In [31]:
# Inspect raw values for problematic rows
mask = df["State/ Site Office"] == "RATLAM"
print(repr(df.loc[mask, "Latitude"].values))
print(repr(df.loc[mask, "Longitude"].values))

array([23.62353, 23.38747, nan, '23.4322.2'], dtype=object)
array([75.05234, 74.92122, nan, '75.1012.6'], dtype=object)

In [32]:
# Convert coords, coercing bad values to NaN
df["Latitude"] = pd.to_numeric(df["Latitude"], errors="coerce")
df["Longitude"] = pd.to_numeric(df["Longitude"], errors="coerce")

# Show rows with bad coordinates so you can inspect them
bad = df[df["Latitude"].isna() | df["Longitude"].isna()]
if not bad.empty:
    print(f"Dropping {len(bad)} rows with invalid coordinates:")
    print(bad[["State", "State/ Site Office", "Latitude", "Longitude"]].to_string())

df = df.dropna(subset=["Latitude", "Longitude"]).reset_index(drop=True)

Dropping 3 rows with invalid coordinates:
0   State State/ Site Office  Latitude  Longitude
79     MP             RATLAM       NaN        NaN
80     MP             RATLAM       NaN        NaN
127    TN           Kayathar       NaN  77.809425

In [33]:
import re
import pandas as pd

def parse_coord(x):
    if pd.isna(x):
        return pd.NA

    s = str(x).strip().replace("\xa0", "")  # remove NBSP

    # keep only digits, dot, minus
    s = re.sub(r"[^0-9.\-]", "", s)

    # if multiple dots, keep first dot and merge the rest
    # e.g. "23.4322.2" -> "23.43222"
    if s.count(".") > 1:
        first = s.find(".")
        s = s[:first + 1] + s[first + 1:].replace(".", "")

    # guard invalid leftovers
    if s in {"", ".", "-", "-."}:
        return pd.NA

    return pd.to_numeric(s, errors="coerce")

df["Latitude"] = df["Latitude"].apply(parse_coord)
df["Longitude"] = df["Longitude"].apply(parse_coord)

# check what is still invalid (should be only genuinely empty/bad rows)
bad = df[df["Latitude"].isna() | df["Longitude"].isna()]
print(bad[["State", "State/ Site Office", "Latitude", "Longitude"]].to_string(index=False))

# drop only truly invalid rows
df = df.dropna(subset=["Latitude", "Longitude"]).reset_index(drop=True)

gdf = gpd.GeoDataFrame(
    df,
    geometry=gpd.points_from_xy(df["Longitude"], df["Latitude"]),
    crs="EPSG:4326"
)

Empty DataFrame
Columns: [State, State/ Site Office, Latitude, Longitude]
Index: []

In [34]:
gdf.head()

,State,State/ Site Office,Latitude,Longitude,Site,geometry
0,GJ,Nanisindhodi,23.101889,68.805361,Nanisindhodi [109WTG],POINT (68.80536 23.10189)
1,GJ,Suthari,23.034722,68.900056,Suthari [84WTG],POINT (68.90006 23.03472)
2,GJ,Kadoli,23.059694,68.846806,Kadoli [87WTG],POINT (68.84681 23.05969)
3,GJ,Lathedi,22.990917,69.037000,Lathedi [93WTG],POINT (69.037 22.99092)
4,GJ,Vayor,23.414611,68.676722,Vayor [84WTG],POINT (68.67672 23.41461)

In [35]:
import folium
import pandas as pd

# Filter to only valid GeoDataFrame with points
if 'gdf' in locals() and not gdf.empty and gdf.geometry.notna().any():
    gdf_map = gdf[gdf.geometry.notna()].copy()
    
    india_center = [20.5937, 78.9629]
    # Create base map
    m = folium.Map(location=india_center, zoom_start=5, tiles="CartoDB positron")
    
    # Define colors for different states
    state_colors = {
        'MH': '#FF5733',
        'GJ': '#33FF57',
        'RJ': '#3357FF',
        'TN': '#FF33F1',
        'MP': '#F1FF33',
        'AP': '#33FFF1',
        'KA': '#FF8C33',
    }
    
    # Group by State and create feature groups
    if 'State' in gdf_map.columns:
        for state, state_data in gdf_map.groupby('State'):
            fg = folium.FeatureGroup(name=f"{state} ({len(state_data)} sites)", show=True)
            
            for idx, row in state_data.iterrows():
                location = [row.geometry.y, row.geometry.x]
                
                # Build popup content
                popup_text = f"""
                <b>{row.get('State/ Site Office', 'Unknown')}</b><br>
                State: {state}<br>
                Lat: {row.geometry.y:.4f}<br>
                Lon: {row.geometry.x:.4f}
                """
                
                color = state_colors.get(state, '#808080')
                folium.CircleMarker(
                    location=location,
                    radius=6,
                    popup=folium.Popup(popup_text, max_width=250),
                    tooltip=row.get('State/ Site Office', 'Site'),
                    color=color,
                    fill=True,
                    fillColor=color,
                    fillOpacity=0.7,
                    weight=2,
                ).add_to(fg)
            
            fg.add_to(m)
    
    # Add layer control
    folium.LayerControl(collapsed=False).add_to(m)
    
    # Save map
    output_file = "cms_sites_map.html"
    m.save(output_file)
    print(f"✓ Map saved to: {output_file}")
    print(f"Total sites: {len(gdf_map)}")
    print(f"States represented: {gdf_map['State'].unique().tolist()}")
else:
    print("No valid GeoDataFrame found. Please run the earlier cells first.")

✓ Map saved to: cms_sites_map.html
Total sites: 143
States represented: ['GJ', 'MH', 'MP', 'AP', 'KA', 'TN', 'RJ']

In [36]:
gdf_map.head()

,State,State/ Site Office,Latitude,Longitude,Site,geometry
0,GJ,Nanisindhodi,23.101889,68.805361,Nanisindhodi [109WTG],POINT (68.80536 23.10189)
1,GJ,Suthari,23.034722,68.900056,Suthari [84WTG],POINT (68.90006 23.03472)
2,GJ,Kadoli,23.059694,68.846806,Kadoli [87WTG],POINT (68.84681 23.05969)
3,GJ,Lathedi,22.990917,69.037000,Lathedi [93WTG],POINT (69.037 22.99092)
4,GJ,Vayor,23.414611,68.676722,Vayor [84WTG],POINT (68.67672 23.41461)

In [20]:
# Read Excel file
file_path = "./Lat Long.xlsx"
df = pd.read_excel(file_path)

In [21]:
# Drop any columns like "Unnamed: 0"
df = df.loc[:, ~df.columns.astype(str).str.contains("^Unnamed", case=False, regex=True)]
df.head()

,LOC_NO,SAP_FUNC_LOC_CODE,CUSTOMER_NAME,MAIN_SITE,STATE,COMM_DATE,INST_CAPACITY,LONGITUDE,LATITUDE
0,GM01,SWSBHT-SC1-GUJ01-GM01,Gujarat Mitra Pvt Ltd,Bhogat,GJ - Saurashtra,1998-11-13,0.35,69.21864,21.97192
1,G001,SWSSAT-SC2-GPL01-G001,Ghodawat Energy Pvt. Ltd.,Satara A,Maharashtra & MP,1998-11-18,0.35,73.83047,17.55353
2,G002,SWSSAT-SC2-GPL02-G002,Ghodawat Energy Pvt. Ltd.,Satara A,Maharashtra & MP,1999-03-12,0.35,73.83072,17.56047
3,G003,SWSSAT-SC2-GPL02-G003,Ghodawat Energy Pvt. Ltd.,Satara A,Maharashtra & MP,1999-03-12,0.35,73.82989,17.55786
4,G004,SWSSAT-SC2-GPL02-G004,Ghodawat Energy Pvt. Ltd.,Satara A,Maharashtra & MP,1999-03-12,0.35,73.83206,17.55828

In [8]:
df

,LOC_NO,SAP_FUNC_LOC_CODE,CUSTOMER_NAME,MAIN_SITE,STATE,COMM_DATE,INST_CAPACITY,LONGITUDE,LATITUDE
0,GM01,SWSBHT-SC1-GUJ01-GM01,Gujarat Mitra Pvt Ltd,Bhogat,GJ - Saurashtra,1998-11-13,0.35,69.21864,21.97192
1,G001,SWSSAT-SC2-GPL01-G001,Ghodawat Energy Pvt. Ltd.,Satara A,Maharashtra & MP,1998-11-18,0.35,73.83047,17.55353
2,G002,SWSSAT-SC2-GPL02-G002,Ghodawat Energy Pvt. Ltd.,Satara A,Maharashtra & MP,1999-03-12,0.35,73.83072,17.56047
3,G003,SWSSAT-SC2-GPL02-G003,Ghodawat Energy Pvt. Ltd.,Satara A,Maharashtra & MP,1999-03-12,0.35,73.82989,17.55786
4,G004,SWSSAT-SC2-GPL02-G004,Ghodawat Energy Pvt. Ltd.,Satara A,Maharashtra & MP,1999-03-12,0.35,73.83206,17.55828
...,...,...,...,...,...,...,...,...,...
9361,KKBKA057,SWSKAN-SC1-SGI01-KKB057,Sembcorp green infra private limited,Kanakagiri,Karnataka,2025-12-25,2.10,NaN,NaN
9362,BAM846D,SWSBHO-SC1-JGL01-BA846D,Juniper Green Kite PVT LTD,Bhogat 2,GJ - Saurashtra,2025-12-31,3.15,NaN,NaN
9363,KEN62,SWSKOP-SC1-SRL01-KEN62,Serentica Renewables Pvt Ltd,Koppal,Karnataka,2025-12-31,3.15,NaN,NaN
9364,KEN63,SWSKOP-SC1-SRL01-KEN63,Serentica Renewables Pvt Ltd,Koppal,Karnataka,2025-12-31,3.15,NaN,NaN
9365,KEN64,SWSKOP-SC1-SRL01-KEN64,Serentica Renewables Pvt Ltd,Koppal,Karnataka,2025-12-31,3.15,NaN,NaN

In [22]:
gdf = gpd.GeoDataFrame(
    df,
    geometry=gpd.points_from_xy(df["LONGITUDE"], df["LATITUDE"]),
    crs="EPSG:4326"
)

In [23]:
gdf.head()

,LOC_NO,SAP_FUNC_LOC_CODE,CUSTOMER_NAME,MAIN_SITE,STATE,COMM_DATE,INST_CAPACITY,LONGITUDE,LATITUDE,geometry
0,GM01,SWSBHT-SC1-GUJ01-GM01,Gujarat Mitra Pvt Ltd,Bhogat,GJ - Saurashtra,1998-11-13,0.35,69.21864,21.97192,POINT (69.21864 21.97192)
1,G001,SWSSAT-SC2-GPL01-G001,Ghodawat Energy Pvt. Ltd.,Satara A,Maharashtra & MP,1998-11-18,0.35,73.83047,17.55353,POINT (73.83047 17.55353)
2,G002,SWSSAT-SC2-GPL02-G002,Ghodawat Energy Pvt. Ltd.,Satara A,Maharashtra & MP,1999-03-12,0.35,73.83072,17.56047,POINT (73.83072 17.56047)
3,G003,SWSSAT-SC2-GPL02-G003,Ghodawat Energy Pvt. Ltd.,Satara A,Maharashtra & MP,1999-03-12,0.35,73.82989,17.55786,POINT (73.82989 17.55786)
4,G004,SWSSAT-SC2-GPL02-G004,Ghodawat Energy Pvt. Ltd.,Satara A,Maharashtra & MP,1999-03-12,0.35,73.83206,17.55828,POINT (73.83206 17.55828)

In [25]:
import folium
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors

# Filter to only valid GeoDataFrame with points
if 'gdf' in locals() and not gdf.empty and gdf.geometry.notna().any():
    # Remove rows with NaN coordinates
    gdf_map = gdf[gdf.geometry.notna()].copy()
    
    # Also filter out rows where geometry has NaN x or y values
    gdf_map = gdf_map[gdf_map.geometry.apply(lambda geom: not (pd.isna(geom.x) or pd.isna(geom.y)))]
    
    if gdf_map.empty:
        print("No valid geometries found after removing NaN values.")
    else:
        print(f"Removed {len(gdf) - len(gdf_map)} rows with invalid coordinates")
        print(f"Processing {len(gdf_map)} valid sites")
        
        india_center = [20.5937, 78.9629]
        m = folium.Map(location=india_center, zoom_start=5, tiles="CartoDB positron")
        
        # Get unique states and generate colors dynamically
        unique_states = gdf_map['STATE'].unique()
        
        # Use updated matplotlib colormap API (fixes deprecation warning)
        cmap = plt.colormaps.get_cmap('tab20')
        
        # Create a mapping of states to colors
        state_colors = {
            state: mcolors.rgb2hex(cmap(i / len(unique_states))) 
            for i, state in enumerate(unique_states)
        }
        
        print("\nState colors mapping:")
        for state, color in state_colors.items():
            print(f"  {state}: {color}")
        
        # Group by state and create feature groups
        for state, state_data in gdf_map.groupby('STATE'):
            fg = folium.FeatureGroup(name=f"{state} ({len(state_data)} sites)", show=True)
            
            for idx, row in state_data.iterrows():
                # Double-check coordinates are valid
                if pd.isna(row.geometry.y) or pd.isna(row.geometry.x):
                    continue
                    
                location = [row.geometry.y, row.geometry.x]
                
                # Build popup content
                popup_text = f"""
                <b>{row.get('MAIN_SITE', 'Unknown')}</b><br>
                LOC_NO: {row.get('LOC_NO', 'N/A')}<br>
                Customer: {row.get('CUSTOMER_NAME', 'N/A')}<br>
                Capacity: {row.get('INST_CAPACITY', 'N/A')} MW<br>
                State: {state}<br>
                Comm Date: {row.get('COMM_DATE', 'N/A')}<br>
                Lat: {row.geometry.y:.4f}<br>
                Lon: {row.geometry.x:.4f}
                """
                
                color = state_colors[state]
                folium.CircleMarker(
                    location=location,
                    radius=5,
                    popup=folium.Popup(popup_text, max_width=300),
                    tooltip=f"{row.get('MAIN_SITE', 'Site')} - {row.get('INST_CAPACITY', '?')} MW",
                    color=color,
                    fill=True,
                    fillColor=color,
                    fillOpacity=0.6,
                    weight=2,
                ).add_to(fg)
            
            fg.add_to(m)
        
        # Add layer control
        folium.LayerControl(collapsed=False).add_to(m)
        
        # Save map
        output_file = "wtg_sites_map.html"
        m.save(output_file)
        print(f"\n✓ Map saved to: {output_file}")
        print(f"Total WTG sites plotted: {len(gdf_map)}")
        print(f"Total installed capacity: {gdf_map['INST_CAPACITY'].sum():.2f} MW")
else:
    print("No valid GeoDataFrame found. Please run the earlier cells first.")

Removed 46 rows with invalid coordinates
Processing 9320 valid sites

State colors mapping:
  GJ - Saurashtra: #1f77b4
  Maharashtra & MP: #ff7f0e
  Tamilnadu: #98df8a
  Rajasthan: #9467bd
  Karnataka: #c49c94
  Andhra Pradesh: #7f7f7f
  GJ - Kutch: #dbdb8d

✓ Map saved to: wtg_sites_map.html
Total WTG sites plotted: 9320
Total installed capacity: 14538.00 MW

In [ ]:
from dotenv import load_dotenv
import os
from sqlalchemy import text
from typing import AsyncGenerator
from sqlalchemy.ext.asyncio import create_async_engine, async_sessionmaker, AsyncSession
import asyncio

# Load environment variables from .env
load_dotenv("../db.env")

# Fetch variables
USER = os.getenv("user")
PASSWORD = os.getenv("password")
HOST = os.getenv("host")
PORT = os.getenv("port")
DBNAME = os.getenv("dbname")

# Construct the SQLAlchemy connection string
DATABASE_URL = f"postgresql+asyncpg://{USER}:{PASSWORD}@{HOST}:{PORT}/{DBNAME}?sslmode=require"

# Construct the SQLAlchemy connection string
DB_URL = f"postgresql+asyncpg://{USER}:{PASSWORD}@{HOST}:{PORT}/{DBNAME}"
# DB_URL = "postgresql://mapper:password@localhost:5432/gisdb"

engine = create_async_engine(
    DB_URL,
    pool_size = 5,
    max_overflow = 0,
    pool_timeout = 5,
    pool_recycle = 1800,
    echo = False
)

AsyncSessionLocal = async_sessionmaker(
    bind=engine,
    expire_on_commit=False,
    class_=AsyncSession
)

# Test the connection
try:
    async with engine.connect() as connection:
        await connection.execute(text("SELECT 1"))
        print("Connection successful!")
except Exception as e:
    print(f"Failed to connect: {e}")

ValueError: invalid literal for int() with base 10: 'None'

In [ ]:
from sqlalchemy import create_engine

# Create a sync engine for the geopandas upload
# Use psycopg instead of psycopg2 (the new async-first driver)
sync_db_url = DB_URL.replace("postgresql+asyncpg://", "postgresql+psycopg://")
sync_engine = create_engine(sync_db_url)

try:    
    with sync_engine.connect() as conn:
        conn.execute(text("SELECT 1"))
        print("Sync connection successful!")
except Exception as e:
    print(f"Failed to connect with sync engine: {e}")

In [ ]:
try:    
    with sync_engine.begin() as conn:
        final_zones.to_postgis("mod_layers", con=conn, schema="GisDB", if_exists="replace")
        conn.execute(text("""
        CREATE INDEX IF NOT EXISTS mod_layers_geom_idx
        ON "GisDB".mod_layers USING GIST (geometry);
        """))
        print("GIS Uploaded to GisDB schema successfully")
except Exception as e:
    print(f"Failed to connect with sync engine: {e}")

In [ ]:
try:
    with sync_engine.connect() as connection:
        alter_query = text("""
                           ALTER TABLE "GisDB".mod_layers
                           ALTER COLUMN geometry TYPE geometry(Geometry, 4326);
                           """)
        connection.execute(alter_query)
        connection.commit()
        print("SUCCESS")
        
except Exception as e:
    print(f"Error altering table: {e}")

In [ ]:
# Set the SRID of the geometry column
from sqlite3 import OperationalError


try:
    with sync_engine.connect() as connection:
        connection.execute(text("SELECT UpdateGeometrySRID('GisDB', 'mod_layers', 'geometry', 4326)"))
        connection.commit()
    print("SRID set successfully")
except OperationalError as e:
    print("Error occurred while setting SRID:", e)