In [1]:
import geopandas as gpd
import zipfile
import os
from pathlib import Path

# Path to your KMZ file
kmz_path = r"./ESZ Windy States.kmz"

# KMZ is a zipped KML file, so we need to extract it first
extract_dir = r"./extracted_kmz"
os.makedirs(extract_dir, exist_ok=True)

# Extract KMZ contents
with zipfile.ZipFile(kmz_path, 'r') as zip_ref:
    zip_ref.extractall(extract_dir)
    print("Extracted files:")
    for file in zip_ref.namelist():
        print(f"  - {file}")

Extracted files:
  - doc.kml
  - files/kml_symbol_no symbol_0_01_01.png
  - files/kml_symbol_no symbol_0_02_03.png
  - files/kml_symbol_no symbol_0_04.png
  - files/kml_symbol_no symbol_0_02_01_01_01_01.png
  - files/kml_symbol_no symbol_0_02_02_01.png
  - files/kml_symbol_no symbol_0_01_01_01_01.png
  - files/kml_symbol_no symbol_0_02_01_01_01.png
  - files/kml_symbol_no symbol_0_02_01_01.png
  - files/kml_symbol_no symbol_0_01_03.png
  - files/kml_symbol_no symbol_0_01_02.png
  - files/kml_symbol_no symbol_0_02_02.png
  - files/kml_symbol_no symbol_0_01.png
  - files/kml_symbol_no symbol_0_03_02.png
  - files/kml_symbol_no symbol_0_01_01_01.png

In [7]:
import geopandas as gpd
import zipfile
import os
from pathlib import Path

# Get the directory where the notebook is located
notebook_dir = Path.cwd()
print(f"Current working directory: {notebook_dir}")

# Path to your KMZ file (in the same folder as notebook)
kmz_path = notebook_dir / "ESZ Windy States.kmz"
print(f"Looking for KMZ at: {kmz_path}")
print(f"File exists: {kmz_path.exists()}")

# If not found, list files in current directory
if not kmz_path.exists():
    print("\nFiles in current directory:")
    for file in notebook_dir.iterdir():
        print(f"  - {file.name}")

# KMZ is a zipped KML file, so we need to extract it first
extract_dir = notebook_dir / "extracted_kmz"
os.makedirs(extract_dir, exist_ok=True)

# Extract KMZ contents
if kmz_path.exists():
    with zipfile.ZipFile(kmz_path, 'r') as zip_ref:
        zip_ref.extractall(extract_dir)
        print("\nExtracted files:")
        for file in zip_ref.namelist():
            print(f"  - {file}")

Current working directory: d:\OneDrive - Suzlon Energy Ltd\Documents\Deployment\Map Analytics\test_notebooks
Looking for KMZ at: d:\OneDrive - Suzlon Energy Ltd\Documents\Deployment\Map Analytics\test_notebooks\ESZ Windy States.kmz
File exists: True

Extracted files:
  - doc.kml
  - files/kml_symbol_no symbol_0_01_01.png
  - files/kml_symbol_no symbol_0_02_03.png
  - files/kml_symbol_no symbol_0_04.png
  - files/kml_symbol_no symbol_0_02_01_01_01_01.png
  - files/kml_symbol_no symbol_0_02_02_01.png
  - files/kml_symbol_no symbol_0_01_01_01_01.png
  - files/kml_symbol_no symbol_0_02_01_01_01.png
  - files/kml_symbol_no symbol_0_02_01_01.png
  - files/kml_symbol_no symbol_0_01_03.png
  - files/kml_symbol_no symbol_0_01_02.png
  - files/kml_symbol_no symbol_0_02_02.png
  - files/kml_symbol_no symbol_0_01.png
  - files/kml_symbol_no symbol_0_03_02.png
  - files/kml_symbol_no symbol_0_01_01_01.png

In [9]:
import geopandas as gpd
import fiona
from pathlib import Path

# Find the KML file (usually doc.kml)
kml_files = list(Path(extract_dir).glob("*.kml"))
print(f"\nFound KML files: {kml_files}")

# Read the KML file with geopandas
if kml_files:
    kml_path = str(kml_files[0])
    
    # Read all layers to see the structure
    layers = fiona.listlayers(kml_path)
    print(f"\nLayers in KML: {layers}")
    
    # Read each layer to understand structure
    for layer in layers:
        try:
            gdf = gpd.read_file(kml_path, driver='KML', layer=layer)
            print(f"\n--- Layer: {layer} ---")
            print(f"Number of features: {len(gdf)}")
            print(f"Columns: {gdf.columns.tolist()}")
            print(f"\nFirst few rows:")
            print(gdf.head())
            print(f"\nGeometry types: {gdf.geometry.type.unique()}")
        except Exception as e:
            print(f"Error reading layer {layer}: {e}")
else:
    print("No KML files found in extracted directory")

Found KML files: [WindowsPath('d:/OneDrive - Suzlon Energy Ltd/Documents/Deployment/Map Analytics/test_notebooks/extracted_kmz/doc.kml')]

Layers in KML: ['ESZ -West', 'MH', 'ESZ-MH', 'i.Sancturies', 'Extrusion zone_Sanctuaries.kmz', 'Point Features', 'Area Features', 'Line Features', 'ii.Airport Funnel', 'Extrusion zone_Airport Funnel.kmz', 'Point Features (#2)', 'Area Features (#2)', 'Line Features (#2)', 'iii.Reserve Forest', 'Extrusion Zone_Forest boundary.kmz', 'Area Features (#3)', 'Line Features (#3)', 'iv.Coastal Regulatory', 'coastal.kmz', 'Area Features (#4)', 'v.Animal-Bird Migratory path', 'animal-bird.kmz', 'Point Features (#3)', 'Area Features (#5)', 'vi.Defence Protected Area', 'vii.Heritages', 'Extrusion Zone_Protected Heritage.kmz', 'Point Features (#4)', 'viii.Reserviors', 'Extrusion zone_Resorvior.kmz', 'Point Features (#5)', 'Area Features (#6)', 'ix.MOD', 'MH MOD', 'MH (#2)', 'Ahmednagar', 'Ahmednagar (#2)', 'Ahmednagar_10NM', 'Ahmednagar_10NM (#2)', 'Beed', 'Beed (#2)', 'Identified Wind Potential Blocks', 'Identified Wind Potential Blocks (#2)', 'puneandNDAAirfeld_20km', 'puneandNDAAirfeld_20km (#2)', 'pune_and_nda_airfield_56km_NEW', 'pune_and_nda_airfield_56km_NEW (#2)', 'Pune_1', 'Pune_1 (#2)', 'Solapur', 'Solapur (#2)', 'Stara', 'Stara (#2)', 'RJ', 'ESZ-RJ', 'i.Sancturies (#2)', 'Extrusion zone_Sanctuary.kmz', 'Point Features (#6)', 'Area Features (#7)', 'Line Features (#4)', 'ii.Airport funnel (#2)', 'Extrusion zone_Airport Funnel.kmz (#2)', 'Point Features (#7)', 'Area Features (#8)', 'Line Features (#5)', 'iii.Reserve Forest (#2)', 'Extrusion zone_Forest.kmz', 'Area Features (#9)', 'Line Features (#6)', 'iv.Coastal Regulatory (#2)', 'v.Animal-bird Migratory Path (#2)', 'Mukundara Tiger Reserve', 'Mukundara Tiger Reserve (#2)', 'RJ-GIB Updated.kmz', 'Area Features (#10)', 'vi.Defence protected Area (#2)', 'vii.Heritages (#2)', 'viii.Reservoir', 'GJ', 'GJ.kmz', 'GJ (#2)', 'GJ-ESZ', 'i. Sanctuaries', 'Point Features (#8)', 'Area Features (#11)', 'Area Features (#12)', 'Line Features (#7)', 'ii. Airport Funnel', 'Line Features (#8)', 'Area Features (#13)', 'Point Features (#9)', 'iii. Reserve Forest', 'Point Features (#10)', 'Area Features (#14)', 'Line Features (#9)', 'iv. Coastal Regulatory', 'Area Features (#15)', 'v. Animal/Bird Migratory Path', 'vi. Defence Protected Area', 'Area Features (#16)', 'vii. Heritages', 'Point Features (#11)', 'Line Features (#10)', 'viii. Reserviors', 'Area Features (#17)', 'Point Features (#12)', 'ix. MOD Boundaries', 'MOD Boundaries', 'No wtg zone-block4', 'No wtg mod remarks-14062024', 'shoreline25km buffer-block4', 'shoreline25km buffer', 'Amreli_1', 'Amreli_1 (#2)', 'Amreli_2', 'Amreli_2 (#2)', 'GJ_Blocks', 'GJ_Blocks (#2)', 'IAF', 'IAF (#2)', 'JamANDkhamairfiled_20km', 'JamANDkhamairfiled_20km (#2)', 'Jamnagar_and_khambaliya_airfield_56km', 'Jamnagar_and_khambaliya_airfield_56km (#2)', 'Jamnagar_1', 'Jamnagar_1 (#2)', 'Jamnagar_2', 'Jamnagar_2 (#2)', 'Kutch_1', 'Kutch_1 (#2)', 'Kutch_2', 'Kutch_2 (#2)', 'Kutch_6NM', 'Kutch_6NM (#2)', 'Naliya and Bhuj airfield_20km', 'No WTG Zone', 'Naliya and Bhuj airfield_56km', 'NOC to be obtained', 'Rajkot', 'Rajkot (#2)', 'MP', 'MP.kmz', 'MP (#2)', 'MP- ESZ', 'i. Sanctuaries (#2)', 'Point Features (#13)', 'Area Features (#18)', 'ii. Airport Funnel (#2)', 'Point Features (#14)', 'Area Features (#19)', 'Line Features (#11)', 'iii. Reserve Forest (#2)', 'iv. Animal/Bird Migratory Path', 'v. Defence Protected Area', 'vi. Heritages', 'vii. Reserviors', 'Point Features (#15)', 'Area Features (#20)', 'viii. MOD Boundaries', 'Identified Wind Potential Blocks (#3)', 'MP_bloacks', 'ESZ-South.kmz', 'ESZ-South', 'KA', 'KA-ESZ', 'ii. Airport Funnel (#3)', 'Airport Name-KA', 'Airport Funnel-KA', 'i. Sancturies', 'Santuries boundary', 'Santuries name', 'iii. Reserve Forest (#3)', 'Reserve Forest', 'RF Boundary', 'RF name', 'iv. Coastal Regulatory Zone', 'CRZ_KA', 'v. Animal / Bird Migratory path', 'Ex. Place name of EC', 'vi. Defence Protected Area (#2)', 'vii. Heritages (#2)', 'Heritage_KA.KMZ', 'Heritage_Places, KA', 'Circle 01 Kms_Heritage Place', 'viii. Reservoirs', 'AP', 'AP-ESZ', 'i. Sanctuary', 'AP (#2)', 'Santuries boundary (#2)', 'Santuries name (#2)', 'ii. Airport Funnel (#4)', 'Airport_AP', 'Airport Name-AP', 'Airport Funnel-AP', 'iii. Reserve Forest (#4)', 'Reserve Forest_AP', 'RF Boundary (#2)', 'RF name (#2)', 'iv. Coastal Regulatory Zone (#2)', 'CRZ_AP', 'v. Animal / Bird Migratory path (#2)', 'vi. Defence Protected Area (#3)', 'vii. Heritages (#3)', 'Heritage_Places, AP', 'Circle 01 Kms_Heritage Place (#2)', 'viii. Reservoirs (#2)', 'Reservoirs_AP', 'TN', 'TN-ESZ', 'i. Sancturies (#2)', 'Santuries boundary (#3)', 'Santuries name (#3)', 'ii. Airport Funnel (#5)', 'Airport name-TN&KL', 'Airport Funnel-TN&KL', 'iii. Reserve Forest (#5)', 'iv. Coastal Regulatory Zone (#3)', 'TN CRZ', 'v. Animal / Bird Migratory path (#3)', 'vi. Defence Protected Area (#4)', 'vii. Heritages (#4)', 'TN Heritage place', 'Circle 01 Kms_Heritage Place (#3)', 'Heritage_Places, TN', 'KL Hritage places.kmz', 'Heritage_Places, KL', 'Circle 01 Kms_Heritage Place (#4)', 'viii. Reservoir', 'ix.ESZ-Agri Protected Zone', 'ESZ-Agri Protected Zone.KMZ', 'Point Features (#16)', 'Area Features (#21)', 'Line Features (#12)', 'TG', 'TG-ESZ', 'i. Sanctuary (#2)', 'AP (#3)', 'Santuries boundary (#4)', 'Santuries name (#4)', 'TG (#2)', 'Santuries boundary (#5)', 'Santuries name (#5)', 'ii. Airport Funnel (#6)', 'Airport_TG', 'Airport Name-TG', 'Airport Funnel-TG', 'Airport_AP (#2)', 'Airport Name-AP (#2)', 'Airport Funnel-AP (#2)', 'iii. Reserve Forest (#6)', 'Reserve Forest_AP (#2)', 'RF Boundary (#3)', 'RF name (#3)', 'Reserve Forest_TG', 'RF Boundary (#4)', 'RF name (#4)', 'iv. Coastal Regulatory Zone (#4)', 'CRZ_AP (#2)', 'v. Animal / Bird Migratory path (#4)', 'vi. Defence Protected Area (#5)', 'vii. Heritages (#5)', 'Heritage_Places, AP (#2)', 'Circle 01 Kms_Heritage Place (#5)', 'viii. Reservoirs (#3)', 'Reservoirs-TG', 'Reservoirs_AP (#2)']
Error reading layer ESZ -West: Layer 'ESZ -West' could not be opened

--- Layer: MH ---
Number of features: 2
Columns: ['Name', 'Description', 'geometry']

First few rows:
      Name Description                                           geometry
0  Block A              POLYGON Z ((75.49 18.57002 0, 75.55 18.57002 0...
1  Block B              POLYGON Z ((75.24 18.86002 0, 75.25002 18.8300...

Geometry types: ['Polygon']
Error reading layer ESZ-MH: Layer 'ESZ-MH' could not be opened
Error reading layer i.Sancturies: Layer 'i.Sancturies' could not be opened
Error reading layer Extrusion zone_Sanctuaries.kmz: Layer 'Extrusion zone_Sanctuaries.kmz' could not be opened

--- Layer: Point Features ---
Number of features: 31
Columns: ['Name', 'Description', 'geometry']

First few rows:
      Name                 Description                       geometry
0  FEATURE  EXTRUSION_ZONE_SANCTUARIES   POINT Z (72.9908 18.99128 0)
1  FEATURE  EXTRUSION_ZONE_SANCTUARIES  POINT Z (75.07968 18.20872 0)
2  FEATURE  EXTRUSION_ZONE_SANCTUARIES  POINT Z (73.87456 16.55496 0)
3  FEATURE  EXTRUSION_ZONE_SANCTUARIES  POINT Z (74.57555 17.44746 0)
4  FEATURE  EXTRUSION_ZONE_SANCTUARIES  POINT Z (74.12003 20.01295 0)

Geometry types: ['Point']

--- Layer: Area Features ---
Number of features: 37
Columns: ['Name', 'Description', 'geometry']

First few rows:
  Name                 Description  \
0       EXTRUSION_ZONE_SANCTUARIES
1       EXTRUSION_ZONE_SANCTUARIES
2       EXTRUSION_ZONE_SANCTUARIES
3       EXTRUSION_ZONE_SANCTUARIES
4       EXTRUSION_ZONE_SANCTUARIES

                                            geometry
0  POLYGON Z ((72.94526 19.03416 0, 72.94378 19.0...
1  POLYGON Z ((74.80418 18.32651 0, 74.80288 18.3...
2  POLYGON Z ((73.95275 16.49646 0, 73.95695 16.4...
3  POLYGON Z ((74.56569 17.44746 0, 74.56567 17.4...
4  POLYGON Z ((74.10527 20.01764 0, 74.10544 20.0...

Geometry types: ['Polygon']

--- Layer: Line Features ---
Number of features: 4
Columns: ['Name', 'Description', 'geometry']

First few rows:
  Name                 Description  \
0       EXTRUSION_ZONE_SANCTUARIES
1       EXTRUSION_ZONE_SANCTUARIES
2       EXTRUSION_ZONE_SANCTUARIES
3       EXTRUSION_ZONE_SANCTUARIES

                                            geometry
0  LINESTRING Z (76.24955 20.52915 0, 76.25172 20...
1  LINESTRING Z (76.46051 20.49932 0, 76.45578 20...
2  LINESTRING Z (76.24979 20.58125 0, 76.24972 20...
3  LINESTRING Z (76.3136 20.4999 0, 76.3136 20.49...

Geometry types: ['LineString']
Error reading layer ii.Airport Funnel: Layer 'ii.Airport Funnel' could not be opened
Error reading layer Extrusion zone_Airport Funnel.kmz: Layer 'Extrusion zone_Airport Funnel.kmz' could not be opened

--- Layer: Point Features (#2) ---
Number of features: 93
Columns: ['Name', 'Description', 'geometry']

First few rows:
                   Name                 Description  \
0     Ratangiri Airport  EXTRUSION_ZONE_AIRPORT_FUN
1      Kolhapur Airport  EXTRUSION_ZONE_AIRPORT_FUN
2         Karad Airport  EXTRUSION_ZONE_AIRPORT_FUN
3  Inernational AirPort  EXTRUSION_ZONE_AIRPORT_FUN
4       Nashik  AirPort  EXTRUSION_ZONE_AIRPORT_FUN

                        geometry
0  POINT Z (73.34294 17.01792 0)
1   POINT Z (74.3096 16.66115 0)
2   POINT Z (74.17814 17.3021 0)
3  POINT Z (72.92236 19.12659 0)
4  POINT Z (73.88682 19.98786 0)

Geometry types: ['Point']

--- Layer: Area Features (#2) ---
Number of features: 29
Columns: ['Name', 'Description', 'geometry']

First few rows:
  Name                 Description  \
0       EXTRUSION_ZONE_AIRPORT_FUN
1       EXTRUSION_ZONE_AIRPORT_FUN
2       EXTRUSION_ZONE_AIRPORT_FUN
3       EXTRUSION_ZONE_AIRPORT_FUN
4       EXTRUSION_ZONE_AIRPORT_FUN

                                            geometry
0  POLYGON Z ((74.09282 20.00467 0, 73.99831 19.9...
1  POLYGON Z ((73.62349 20.00567 0, 73.53045 20.0...
2  POLYGON Z ((74.18978 20.1974 0, 74.09806 20.17...
3  POLYGON Z ((73.72435 20.13688 0, 73.62909 20.1...
4  POLYGON Z ((75.02411 20.95657 0, 74.9285 20.94...

Geometry types: ['Polygon']

--- Layer: Line Features (#2) ---
Number of features: 868
Columns: ['Name', 'Description', 'geometry']

First few rows:
  Name                 Description  \
0       EXTRUSION_ZONE_AIRPORT_FUN
1       EXTRUSION_ZONE_AIRPORT_FUN
2       EXTRUSION_ZONE_AIRPORT_FUN
3       EXTRUSION_ZONE_AIRPORT_FUN
4       EXTRUSION_ZONE_AIRPORT_FUN

                                            geometry
0  LINESTRING Z (74.23513 19.94431 0, 73.38362 19...
1  LINESTRING Z (74.33977 20.15627 0, 73.49007 20...
2  LINESTRING Z (75.16459 20.89082 0, 74.30992 20...
3  LINESTRING Z (76.05536 20.91766 0, 75.20247 21...
4  LINESTRING Z (77.484 20.65749 0, 76.63225 20.7...

Geometry types: ['LineString']
Error reading layer iii.Reserve Forest: Layer 'iii.Reserve Forest' could not be opened
Error reading layer Extrusion Zone_Forest boundary.kmz: Layer 'Extrusion Zone_Forest boundary.kmz' could not be opened

--- Layer: Area Features (#3) ---
Number of features: 70
Columns: ['Name', 'Description', 'geometry']

First few rows:
  Name                 Description  \
0       EXTRUSION_ZONE_FOREST_BOUN
1       EXTRUSION_ZONE_FOREST_BOUN
2       EXTRUSION_ZONE_FOREST_BOUN
3       EXTRUSION_ZONE_FOREST_BOUN
4       EXTRUSION_ZONE_FOREST_BOUN

                                            geometry
0  POLYGON Z ((74.63723 17.69335 0, 74.6372 17.69...
1  POLYGON Z ((74.66792 17.69657 0, 74.66766 17.6...
2  POLYGON Z ((74.59216 17.94806 0, 74.59006 17.9...
3  POLYGON Z ((74.60484 17.95083 0, 74.60404 17.9...
4  POLYGON Z ((74.6131 17.94873 0, 74.61387 17.94...

Geometry types: ['Polygon']

--- Layer: Line Features (#3) ---
Number of features: 1
Columns: ['Name', 'Description', 'geometry']

First few rows:
  Name                 Description  \
0       EXTRUSION_ZONE_FOREST_BOUN

                                            geometry
0  LINESTRING Z (74.66412 17.92641 0, 74.66435 17...

Geometry types: ['LineString']
Error reading layer iv.Coastal Regulatory: Layer 'iv.Coastal Regulatory' could not be opened
Error reading layer coastal.kmz: Layer 'coastal.kmz' could not be opened

--- Layer: Area Features (#4) ---
Number of features: 1
Columns: ['Name', 'Description', 'geometry']

First few rows:
  Name     Description                                           geometry
0       MH_COSTAL AREA  POLYGON Z ((72.72719 20.12073 0, 72.7219 20.11...

Geometry types: ['Polygon']
Error reading layer v.Animal-Bird Migratory path: Layer 'v.Animal-Bird Migratory path' could not be opened
Error reading layer animal-bird.kmz: Layer 'animal-bird.kmz' could not be opened

--- Layer: Point Features (#3) ---
Number of features: 1
Columns: ['Name', 'Description', 'geometry']

First few rows:
                    Name                          Description  \
0  Melghat Tiger Reserve  EXTRUSION ZONE_MEGHAT TIGER RESERVE

                        geometry
0  POINT Z (77.22297 21.44607 0)

Geometry types: ['Point']

--- Layer: Area Features (#5) ---
Number of features: 1
Columns: ['Name', 'Description', 'geometry']

First few rows:
  Name                          Description  \
0       EXTRUSION ZONE_MEGHAT TIGER RESERVE

                                            geometry
0  POLYGON Z ((76.80363 21.18739 0, 76.83318 21.1...

Geometry types: ['Polygon']
Error reading layer vi.Defence Protected Area: Layer 'vi.Defence Protected Area' could not be opened
Error reading layer vii.Heritages: Layer 'vii.Heritages' could not be opened
Error reading layer Extrusion Zone_Protected Heritage.kmz: Layer 'Extrusion Zone_Protected Heritage.kmz' could not be opened

--- Layer: Point Features (#4) ---
Number of features: 34
Columns: ['Name', 'Description', 'geometry']

First few rows:
           Name                 Description                       geometry
0                EXTRUSION_ZONE_PROTECTED_H  POINT Z (74.04947 18.41216 0)
1    Malhargadh  EXTRUSION_ZONE_PROTECTED_H  POINT Z (74.04947 18.41216 0)
2                EXTRUSION_ZONE_PROTECTED_H  POINT Z (73.68228 18.24665 0)
3  Rajgadh Fort  EXTRUSION_ZONE_PROTECTED_H  POINT Z (73.68228 18.24665 0)
4                EXTRUSION_ZONE_PROTECTED_H  POINT Z (75.71273 20.55193 0)

Geometry types: ['Point']
Error reading layer viii.Reserviors: Layer 'viii.Reserviors' could not be opened
Error reading layer Extrusion zone_Resorvior.kmz: Layer 'Extrusion zone_Resorvior.kmz' could not be opened

--- Layer: Point Features (#5) ---
Number of features: 73
Columns: ['Name', 'Description', 'geometry']

First few rows:
              Name               Description                       geometry
0          Rajapur  EXTRUSION_ZONE_RESORVIOR   POINT Z (73.9607 16.31774 0)
1      Mulashi Dam  EXTRUSION_ZONE_RESORVIOR  POINT Z (73.41582 18.56364 0)
2  Khadakwasla Dam  EXTRUSION_ZONE_RESORVIOR   POINT Z (73.71457 18.4005 0)
3      Panshet Dam  EXTRUSION_ZONE_RESORVIOR  POINT Z (73.53815 18.36531 0)
4     Itiadoh Lake  EXTRUSION_ZONE_RESORVIOR  POINT Z (80.19145 20.83938 0)

Geometry types: ['Point']

--- Layer: Area Features (#6) ---
Number of features: 74
Columns: ['Name', 'Description', 'geometry']

First few rows:
  Name               Description  \
0       EXTRUSION_ZONE_RESORVIOR
1       EXTRUSION_ZONE_RESORVIOR
2       EXTRUSION_ZONE_RESORVIOR
3       EXTRUSION_ZONE_RESORVIOR
4       EXTRUSION_ZONE_RESORVIOR

                                            geometry
0  POLYGON Z ((72.85132 19.69657 0, 72.8513 19.69...
1  POLYGON Z ((73.93818 16.29434 0, 73.94004 16.2...
2  POLYGON Z ((73.39891 18.58894 0, 73.39856 18.5...
3  POLYGON Z ((73.66607 18.38672 0, 73.66722 18.3...
4  POLYGON Z ((73.52147 18.37512 0, 73.5223 18.37...

Geometry types: ['Polygon']
Error reading layer ix.MOD: Layer 'ix.MOD' could not be opened
Error reading layer MH MOD: Layer 'MH MOD' could not be opened
Error reading layer MH (#2): Layer 'MH (#2)' could not be opened

--- Layer: Ahmednagar ---
Number of features: 1
Columns: ['Name', 'Description', 'geometry']

First few rows:
  Name                                        Description  \
0    0  <html xmlns:fo="http://www.w3.org/1999/XSL/For...

                                            geometry
0  MULTIPOLYGON Z (((74.3325 19.15083 0, 74.67178...

Geometry types: ['MultiPolygon']
Error reading layer Ahmednagar (#2): Layer 'Ahmednagar (#2)' could not be opened

--- Layer: Ahmednagar_10NM ---
Number of features: 1
Columns: ['Name', 'Description', 'geometry']

First few rows:
                 Name                                        Description  \
0  19 13 03 074 35 37  <html xmlns:fo="http://www.w3.org/1999/XSL/For...

                                            geometry
0  MULTIPOLYGON Z (((74.59361 19.38492 0, 74.5854...

Geometry types: ['MultiPolygon']
Error reading layer Ahmednagar_10NM (#2): Layer 'Ahmednagar_10NM (#2)' could not be opened

--- Layer: Beed ---
Number of features: 1
Columns: ['Name', 'Description', 'geometry']

First few rows:
  Name                                        Description  \
0    0  <html xmlns:fo="http://www.w3.org/1999/XSL/For...

                                            geometry
0  MULTIPOLYGON Z (((75.16667 19.13333 0, 75.1666...

Geometry types: ['MultiPolygon']
Error reading layer Beed (#2): Layer 'Beed (#2)' could not be opened

--- Layer: Identified Wind Potential Blocks ---
Number of features: 5
Columns: ['Name', 'Description', 'geometry']

First few rows:
       Name                                        Description  \
0    Nashik  <html xmlns:fo="http://www.w3.org/1999/XSL/For...
1      Beed  <html xmlns:fo="http://www.w3.org/1999/XSL/For...
2      Pune  <html xmlns:fo="http://www.w3.org/1999/XSL/For...
3  Kolhapur  <html xmlns:fo="http://www.w3.org/1999/XSL/For...
4   Solapur  <html xmlns:fo="http://www.w3.org/1999/XSL/For...

                                            geometry
0  MULTIPOLYGON Z (((74.92326 19.56098 0, 74.9668...
1  MULTIPOLYGON Z (((75.1919 19.1419 0, 75.20392 ...
2  MULTIPOLYGON Z (((73.48333 19.53949 0, 73.4928...
3  MULTIPOLYGON Z (((73.59079 17.94913 0, 73.6117...
4  MULTIPOLYGON Z (((74.46518 17.63715 0, 74.4654...

Geometry types: ['MultiPolygon']
Error reading layer Identified Wind Potential Blocks (#2): Layer 'Identified Wind Potential Blocks (#2)' could not be opened

--- Layer: puneandNDAAirfeld_20km ---
Number of features: 2
Columns: ['Name', 'Description', 'geometry']

First few rows:
            Name                                        Description  \
0  Pune Airfield  <html xmlns:fo="http://www.w3.org/1999/XSL/For...
1   NDA Airfield  <html xmlns:fo="http://www.w3.org/1999/XSL/For...

                                            geometry
0  MULTIPOLYGON Z (((73.92028 18.76347 0, 73.9118...
1  MULTIPOLYGON Z (((73.77944 18.65347 0, 73.771 ...

Geometry types: ['MultiPolygon']
Error reading layer puneandNDAAirfeld_20km (#2): Layer 'puneandNDAAirfeld_20km (#2)' could not be opened

--- Layer: pune_and_nda_airfield_56km_NEW ---
Number of features: 2
Columns: ['Name', 'Description', 'geometry']

First few rows:
            Name                                        Description  \
0  Pune Airfield  <html xmlns:fo="http://www.w3.org/1999/XSL/For...
1   NDA Airfield  <html xmlns:fo="http://www.w3.org/1999/XSL/For...

                                            geometry
0  MULTIPOLYGON Z (((73.92028 19.08869 0, 73.9061...
1  MULTIPOLYGON Z (((73.77944 18.9787 0, 73.76529...

Geometry types: ['MultiPolygon']
Error reading layer pune_and_nda_airfield_56km_NEW (#2): Layer 'pune_and_nda_airfield_56km_NEW (#2)' could not be opened

--- Layer: Pune_1 ---
Number of features: 6
Columns: ['Name', 'Description', 'geometry']

First few rows:
  Name                                        Description  \
0    0  <html xmlns:fo="http://www.w3.org/1999/XSL/For...
1    0  <html xmlns:fo="http://www.w3.org/1999/XSL/For...
2    0  <html xmlns:fo="http://www.w3.org/1999/XSL/For...
3    0  <html xmlns:fo="http://www.w3.org/1999/XSL/For...
4    0  <html xmlns:fo="http://www.w3.org/1999/XSL/For...


In [16]:
import geopandas as gpd
import fiona
import zipfile
from pathlib import Path

notebook_dir = Path.cwd()
extract_dir = notebook_dir / "extracted_kmz"

# Find the KML file
kml_files = list(Path(extract_dir).glob("*.kml"))
if kml_files:
    kml_path = str(kml_files[0])
    
    # Read all layers
    layers = fiona.listlayers(kml_path)
    print(f"Total layers found: {len(layers)}\n")
    
    # Extract nested KMZ files (layers that end with .kmz)
    kmz_layers = [layer for layer in layers if layer.endswith('.kmz')]
    print(f"Found {len(kmz_layers)} nested KMZ files:")
    for kmz_layer in kmz_layers:
        print(f"  - {kmz_layer}")
    
    # Extract each nested KMZ
    for kmz_layer in kmz_layers:
        try:
            gdf = gpd.read_file(kml_path, driver='KML', layer=kmz_layer)
            if len(gdf) > 0:
                # The geometry contains the KMZ data
                print(f"\nExtracting: {kmz_layer}")
        except Exception as e:
            print(f"Error with {kmz_layer}: {e}")
    
    # Look for KMZ files in the extract directory
    kmz_files = list(extract_dir.glob("**/*.kmz"))
    print(f"\n\nFound {len(kmz_files)} KMZ files in directory:")
    for kmz_file in kmz_files:
        print(f"  - {kmz_file.relative_to(extract_dir)}")
        # Extract each KMZ
        nested_dir = kmz_file.parent / kmz_file.stem
        nested_dir.mkdir(exist_ok=True)
        try:
            with zipfile.ZipFile(kmz_file, 'r') as zip_ref:
                zip_ref.extractall(nested_dir)
                print(f"    Extracted to: {nested_dir}")
        except Exception as e:
            print(f"    Error extracting: {e}")

# Find all state folders (XX-ESZ pattern)
state_folders = []
for folder in extract_dir.rglob("*"):
    if folder.is_dir() and "-ESZ" in folder.name:
        state_folders.append(folder)

print(f"\n\nTotal states found: {len(state_folders)}")
for state in sorted(state_folders):
    print(f"  - {state.name}")

Total layers found: 267

Found 14 nested KMZ files:
  - Extrusion zone_Sanctuaries.kmz
  - Extrusion zone_Airport Funnel.kmz
  - Extrusion Zone_Forest boundary.kmz
  - coastal.kmz
  - animal-bird.kmz
  - Extrusion Zone_Protected Heritage.kmz
  - Extrusion zone_Resorvior.kmz
  - Extrusion zone_Sanctuary.kmz
  - Extrusion zone_Forest.kmz
  - RJ-GIB Updated.kmz
  - GJ.kmz
  - MP.kmz
  - ESZ-South.kmz
  - KL Hritage places.kmz
Error with Extrusion zone_Sanctuaries.kmz: Layer 'Extrusion zone_Sanctuaries.kmz' could not be opened
Error with Extrusion zone_Airport Funnel.kmz: Layer 'Extrusion zone_Airport Funnel.kmz' could not be opened
Error with Extrusion Zone_Forest boundary.kmz: Layer 'Extrusion Zone_Forest boundary.kmz' could not be opened
Error with coastal.kmz: Layer 'coastal.kmz' could not be opened
Error with animal-bird.kmz: Layer 'animal-bird.kmz' could not be opened
Error with Extrusion Zone_Protected Heritage.kmz: Layer 'Extrusion Zone_Protected Heritage.kmz' could not be opened
Error with Extrusion zone_Resorvior.kmz: Layer 'Extrusion zone_Resorvior.kmz' could not be opened
Error with Extrusion zone_Sanctuary.kmz: Layer 'Extrusion zone_Sanctuary.kmz' could not be opened
Error with Extrusion zone_Forest.kmz: Layer 'Extrusion zone_Forest.kmz' could not be opened
Error with RJ-GIB Updated.kmz: Layer 'RJ-GIB Updated.kmz' could not be opened
Error with GJ.kmz: Layer 'GJ.kmz' could not be opened
Error with MP.kmz: Layer 'MP.kmz' could not be opened
Error with ESZ-South.kmz: Layer 'ESZ-South.kmz' could not be opened
Error with KL Hritage places.kmz: Layer 'KL Hritage places.kmz' could not be opened


Found 0 KMZ files in directory:


Total states found: 0

In [17]:
import geopandas as gpd
import fiona
import zipfile
import io
from pathlib import Path

notebook_dir = Path.cwd()
extract_dir = notebook_dir / "extracted_kmz"

# Find the KML file
kml_files = list(Path(extract_dir).glob("*.kml"))
if kml_files:
    kml_path = str(kml_files[0])
    
    # Read all layers
    layers = fiona.listlayers(kml_path)
    print(f"Total layers found: {len(layers)}\n")
    
    # Extract nested KMZ files (layers that end with .kmz)
    kmz_layers = [layer for layer in layers if layer.endswith('.kmz')]
    print(f"Found {len(kmz_layers)} nested KMZ files:")
    for kmz_layer in kmz_layers:
        print(f"  - {kmz_layer}")
    
    # Extract each nested KMZ from the KML layer
    for kmz_layer in kmz_layers:
        try:
            # Read the layer with fiona
            with fiona.open(kml_path, driver='KML', layer=kmz_layer) as src:
                for feature in src:
                    # The geometry contains the KMZ binary data
                    if 'geometry' in feature and feature['geometry']:
                        kmz_data = feature['geometry'].get('coordinates')
                        if kmz_data:
                            print(f"Found KMZ data in layer: {kmz_layer}")
        except Exception as e:
            print(f"Error reading {kmz_layer}: {e}")
    
    # Look for any .kmz files that were already extracted
    kmz_files = list(extract_dir.rglob("*.kmz"))
    print(f"\n\nFound {len(kmz_files)} KMZ files in directory:")
    
    # Recursively extract all KMZ files
    def extract_all_kmz(directory):
        for kmz_file in directory.glob("*.kmz"):
            nested_dir = kmz_file.parent / kmz_file.stem
            nested_dir.mkdir(exist_ok=True)
            print(f"Extracting: {kmz_file.name} to {nested_dir}")
            try:
                with zipfile.ZipFile(kmz_file, 'r') as zip_ref:
                    zip_ref.extractall(nested_dir)
                # Recursively extract any nested KMZ files
                extract_all_kmz(nested_dir)
            except Exception as e:
                print(f"Error extracting {kmz_file.name}: {e}")
    
    extract_all_kmz(extract_dir)

# Find all state folders (XX-ESZ pattern)
state_folders = []
for folder in extract_dir.rglob("*"):
    if folder.is_dir() and "-ESZ" in folder.name:
        state_folders.append(folder)

print(f"\n\nTotal states found: {len(state_folders)}")
for state in sorted(state_folders):
    print(f"  - {state.name}")

Total layers found: 267

Found 14 nested KMZ files:
  - Extrusion zone_Sanctuaries.kmz
  - Extrusion zone_Airport Funnel.kmz
  - Extrusion Zone_Forest boundary.kmz
  - coastal.kmz
  - animal-bird.kmz
  - Extrusion Zone_Protected Heritage.kmz
  - Extrusion zone_Resorvior.kmz
  - Extrusion zone_Sanctuary.kmz
  - Extrusion zone_Forest.kmz
  - RJ-GIB Updated.kmz
  - GJ.kmz
  - MP.kmz
  - ESZ-South.kmz
  - KL Hritage places.kmz
Error reading Extrusion zone_Sanctuaries.kmz: Null layer: <closed Collection 'd:\OneDrive - Suzlon Energy Ltd\Documents\Deployment\Map Analytics\test_notebooks\extracted_kmz\doc.kml:Extrusion zone_Sanctuaries.kmz', mode 'r' at 0x18da9ec3cb0> Extrusion zone_Sanctuaries.kmz
Error reading Extrusion zone_Airport Funnel.kmz: Null layer: <closed Collection 'd:\OneDrive - Suzlon Energy Ltd\Documents\Deployment\Map Analytics\test_notebooks\extracted_kmz\doc.kml:Extrusion zone_Airport Funnel.kmz', mode 'r' at 0x18da9e03d90> Extrusion zone_Airport Funnel.kmz
Error reading Extrusion Zone_Forest boundary.kmz: Null layer: <closed Collection 'd:\OneDrive - Suzlon Energy Ltd\Documents\Deployment\Map Analytics\test_notebooks\extracted_kmz\doc.kml:Extrusion Zone_Forest boundary.kmz', mode 'r' at 0x18da9e03d90> Extrusion Zone_Forest boundary.kmz
Error reading coastal.kmz: Null layer: <closed Collection 'd:\OneDrive - Suzlon Energy Ltd\Documents\Deployment\Map Analytics\test_notebooks\extracted_kmz\doc.kml:coastal.kmz', mode 'r' at 0x18da9f5e520> coastal.kmz
Error reading animal-bird.kmz: Null layer: <closed Collection 'd:\OneDrive - Suzlon Energy Ltd\Documents\Deployment\Map Analytics\test_notebooks\extracted_kmz\doc.kml:animal-bird.kmz', mode 'r' at 0x18da9f5e520> animal-bird.kmz
Error reading Extrusion Zone_Protected Heritage.kmz: Null layer: <closed Collection 'd:\OneDrive - Suzlon Energy Ltd\Documents\Deployment\Map Analytics\test_notebooks\extracted_kmz\doc.kml:Extrusion Zone_Protected Heritage.kmz', mode 'r' at 0x18da9d5e7b0> Extrusion Zone_Protected Heritage.kmz
Error reading Extrusion zone_Resorvior.kmz: Null layer: <closed Collection 'd:\OneDrive - Suzlon Energy Ltd\Documents\Deployment\Map Analytics\test_notebooks\extracted_kmz\doc.kml:Extrusion zone_Resorvior.kmz', mode 'r' at 0x18da9ff6360> Extrusion zone_Resorvior.kmz
Error reading Extrusion zone_Sanctuary.kmz: Null layer: <closed Collection 'd:\OneDrive - Suzlon Energy Ltd\Documents\Deployment\Map Analytics\test_notebooks\extracted_kmz\doc.kml:Extrusion zone_Sanctuary.kmz', mode 'r' at 0x18da9ff6360> Extrusion zone_Sanctuary.kmz
Error reading Extrusion zone_Forest.kmz: Null layer: <closed Collection 'd:\OneDrive - Suzlon Energy Ltd\Documents\Deployment\Map Analytics\test_notebooks\extracted_kmz\doc.kml:Extrusion zone_Forest.kmz', mode 'r' at 0x18da9e64250> Extrusion zone_Forest.kmz
Error reading RJ-GIB Updated.kmz: Null layer: <closed Collection 'd:\OneDrive - Suzlon Energy Ltd\Documents\Deployment\Map Analytics\test_notebooks\extracted_kmz\doc.kml:RJ-GIB Updated.kmz', mode 'r' at 0x18da9e64050> RJ-GIB Updated.kmz
Error reading GJ.kmz: Null layer: <closed Collection 'd:\OneDrive - Suzlon Energy Ltd\Documents\Deployment\Map Analytics\test_notebooks\extracted_kmz\doc.kml:GJ.kmz', mode 'r' at 0x18da9d445f0> GJ.kmz
Error reading MP.kmz: Null layer: <closed Collection 'd:\OneDrive - Suzlon Energy Ltd\Documents\Deployment\Map Analytics\test_notebooks\extracted_kmz\doc.kml:MP.kmz', mode 'r' at 0x18da9d445f0> MP.kmz
Error reading ESZ-South.kmz: Null layer: <closed Collection 'd:\OneDrive - Suzlon Energy Ltd\Documents\Deployment\Map Analytics\test_notebooks\extracted_kmz\doc.kml:ESZ-South.kmz', mode 'r' at 0x18da9d44b90> ESZ-South.kmz
Error reading KL Hritage places.kmz: Null layer: <closed Collection 'd:\OneDrive - Suzlon Energy Ltd\Documents\Deployment\Map Analytics\test_notebooks\extracted_kmz\doc.kml:KL Hritage places.kmz', mode 'r' at 0x18da9d44f50> KL Hritage places.kmz


Found 0 KMZ files in directory:


Total states found: 0

In [17]:
import geopandas as gpd
import fiona
import zipfile
import io
from pathlib import Path

notebook_dir = Path.cwd()
extract_dir = notebook_dir / "extracted_kmz"

# Find the KML file
kml_files = list(Path(extract_dir).glob("*.kml"))
if kml_files:
    kml_path = str(kml_files[0])
    
    # Read all layers
    layers = fiona.listlayers(kml_path)
    print(f"Total layers found: {len(layers)}\n")
    
    # Extract nested KMZ files (layers that end with .kmz)
    kmz_layers = [layer for layer in layers if layer.endswith('.kmz')]
    print(f"Found {len(kmz_layers)} nested KMZ files:")
    for kmz_layer in kmz_layers:
        print(f"  - {kmz_layer}")
    
    # Extract each nested KMZ from the KML layer
    for kmz_layer in kmz_layers:
        try:
            # Read the layer with fiona to get the binary data
            with fiona.open(kml_path, driver='KML', layer=kmz_layer) as src:
                for feature in src:
                    if 'properties' in feature:
                        # Check if Description contains base64 or binary data
                        desc = feature['properties'].get('Description', '')
                        if desc:
                            print(f"\nProcessing: {kmz_layer}")
                            # Try to extract KMZ from description or look for embedded file
                            break
        except Exception as e:
            print(f"Trying alternative method for {kmz_layer}")
    
    # Alternative: Extract KMZ files by reading the KML XML directly
    import xml.etree.ElementTree as ET
    tree = ET.parse(kml_path)
    root = tree.getroot()
    
    # Find all NetworkLink elements that reference KMZ files
    ns = {'kml': 'http://www.opengis.net/kml/2.2'}
    
    kmz_extracted_count = 0
    for network_link in root.findall('.//kml:NetworkLink', ns):
        href = network_link.find('.//kml:href', ns)
        if href is not None and href.text and href.text.endswith('.kmz'):
            kmz_file_path = Path(extract_dir) / href.text
            if kmz_file_path.exists():
                nested_dir = kmz_file_path.parent / kmz_file_path.stem
                nested_dir.mkdir(exist_ok=True)
                print(f"Extracting: {href.text}")
                try:
                    with zipfile.ZipFile(kmz_file_path, 'r') as zip_ref:
                        zip_ref.extractall(nested_dir)
                        kmz_extracted_count += 1
                except Exception as e:
                    print(f"Error: {e}")
    
    # Recursively extract any remaining KMZ files
    def extract_all_kmz(directory, depth=0):
        indent = "  " * depth
        for kmz_file in directory.glob("*.kmz"):
            nested_dir = kmz_file.parent / kmz_file.stem
            nested_dir.mkdir(exist_ok=True)
            print(f"{indent}Extracting: {kmz_file.name}")
            try:
                with zipfile.ZipFile(kmz_file, 'r') as zip_ref:
                    zip_ref.extractall(nested_dir)
                extract_all_kmz(nested_dir, depth + 1)
            except Exception as e:
                print(f"{indent}Error: {e}")
    
    extract_all_kmz(extract_dir)

# Find all state folders (XX-ESZ pattern)
state_folders = []
for folder in extract_dir.rglob("*"):
    if folder.is_dir() and "-ESZ" in folder.name:
        state_folders.append(folder)

print(f"\n\nTotal states found: {len(state_folders)}")
for state in sorted(state_folders):
    print(f"  - {state.name}")

Total layers found: 267

Found 14 nested KMZ files:
  - Extrusion zone_Sanctuaries.kmz
  - Extrusion zone_Airport Funnel.kmz
  - Extrusion Zone_Forest boundary.kmz
  - coastal.kmz
  - animal-bird.kmz
  - Extrusion Zone_Protected Heritage.kmz
  - Extrusion zone_Resorvior.kmz
  - Extrusion zone_Sanctuary.kmz
  - Extrusion zone_Forest.kmz
  - RJ-GIB Updated.kmz
  - GJ.kmz
  - MP.kmz
  - ESZ-South.kmz
  - KL Hritage places.kmz
Trying alternative method for Extrusion zone_Sanctuaries.kmz
Trying alternative method for Extrusion zone_Airport Funnel.kmz
Trying alternative method for Extrusion Zone_Forest boundary.kmz
Trying alternative method for coastal.kmz
Trying alternative method for animal-bird.kmz
Trying alternative method for Extrusion Zone_Protected Heritage.kmz
Trying alternative method for Extrusion zone_Resorvior.kmz
Trying alternative method for Extrusion zone_Sanctuary.kmz
Trying alternative method for Extrusion zone_Forest.kmz
Trying alternative method for RJ-GIB Updated.kmz
Trying alternative method for GJ.kmz
Trying alternative method for MP.kmz
Trying alternative method for ESZ-South.kmz
Trying alternative method for KL Hritage places.kmz

AssertionError:

AssertionError:

In [25]:
import geopandas as gpd
import pandas as pd
import xml.etree.ElementTree as ET
from pathlib import Path
import fiona

notebook_dir = Path.cwd()
extract_dir = notebook_dir / "extracted_kmz"

# Read the main KML file and parse its folder structure
kml_path = extract_dir / "doc.kml"
fixed_kml_path = extract_dir / "doc_fixed.kml"
kml_path = fixed_kml_path


# Parse the XML to understand the folder hierarchy
tree = ET.parse(kml_path)
root = tree.getroot()

# Define namespaces
ns = {
    'kml': 'http://www.opengis.net/kml/2.2',
    'atom': 'http://www.w3.org/2005/Atom'
}

# Extract state information from folder hierarchy
def get_folder_hierarchy(element, path=[]):
    """Recursively extract folder hierarchy"""
    hierarchies = []
    
    for folder in element.findall('.//kml:Folder', ns):
        name_elem = folder.find('kml:name', ns)
        if name_elem is not None:
            folder_name = name_elem.text
            current_path = path + [folder_name]
            hierarchies.append(current_path)
            
    return hierarchies

hierarchies = get_folder_hierarchy(root)

# Print folder structure to understand state organization
print("Folder structure:")
for h in hierarchies[:20]:  # Show first 20
    indent = "  " * (len(h) - 1)
    print(f"{indent}{h[-1]}")

# Read all layers from the KML
print("\n\nReading all KML layers...")
layers = fiona.listlayers(str(kml_path))
print(f"Total layers: {len(layers)}")

all_gdfs = []
state_mapping = {
    'MH': 'Maharashtra',
    'GJ': 'Gujarat', 
    'RJ': 'Rajasthan',
    'MP': 'Madhya Pradesh',
    'KA': 'Karnataka',
    'AP': 'Andhra Pradesh',
    'TG': 'Telangana',
    'TN': 'Tamil Nadu',
    'KL': 'Kerala'
}

# Read each layer and extract state info from hierarchy
for layer_name in layers:
    # Skip KMZ references
    if layer_name.endswith('.kmz'):
        continue
    
    try:
        gdf = gpd.read_file(str(kml_path), driver='KML', layer=layer_name)
        
        if len(gdf) > 0:
            # Try to determine state from layer context
            # The folder hierarchy in the XML shows state organization
            state_code = None
            
            # Check if layer name contains state code
            for code in state_mapping.keys():
                if code in layer_name or f'{code}-ESZ' in layer_name or f'ESZ-{code}' in layer_name:
                    state_code = code
                    break
            
            # Add metadata
            gdf['layer_name'] = layer_name
            gdf['state_code'] = state_code
            gdf['state_name'] = state_mapping.get(state_code, None)
            
            all_gdfs.append(gdf)
            
            state_info = f" ({state_code})" if state_code else ""
            print(f"✓ {len(gdf):4d} features from layer: {layer_name}{state_info}")
            
    except Exception as e:
        print(f"✗ Error reading {layer_name}: {e}")

# Combine all GeoDataFrames
if all_gdfs:
    combined_gdf = gpd.GeoDataFrame(pd.concat(all_gdfs, ignore_index=True))
    
    print(f"\n{'='*70}")
    print(f"SUMMARY")
    print(f"{'='*70}")
    print(f"Total features extracted: {len(combined_gdf):,}")
    print(f"Total layers processed: {len(all_gdfs)}")
    
    print(f"\nGeometry types:")
    print(combined_gdf.geometry.geom_type.value_counts())
    
    print(f"\nColumns: {combined_gdf.columns.tolist()}")
    
    if 'state_code' in combined_gdf.columns:
        print(f"\nFeatures by state:")
        state_counts = combined_gdf['state_code'].value_counts()
        for state, count in state_counts.items():
            state_name = state_mapping.get(state, 'Unknown')
            print(f"  {state} ({state_name}): {count:,}")
    
    print(f"\nSample data:")
    print(combined_gdf[['Name', 'Description', 'state_code', 'geometry']].head(10))
    
    # Save to file
    output_file = notebook_dir / "esz_combined2.gpkg"
    combined_gdf.to_file(output_file, driver='GPKG')
    print(f"\n✓ Saved to: {output_file}")
    
else:
    print("\n⚠ No features extracted")

Folder structure:
ESZ
ESZ -West
MH
ESZ-MH
i.Sancturies
Point Features
Area Features
Line Features
ii.Airport Funnel
Point Features
Area Features
Line Features
iii.Reserve Forest
Area Features
Line Features
iv.Coastal Regulatory
Area Features
v.Animal-Bird Migratory path
Point Features
Area Features


Reading all KML layers...
Total layers: 267
✗ Error reading ESZ -West: Layer 'ESZ -West' could not be opened
✓    2 features from layer: MH (MH)
✗ Error reading ESZ-MH: Layer 'ESZ-MH' could not be opened
✗ Error reading i.Sancturies: Layer 'i.Sancturies' could not be opened
✓   31 features from layer: Point Features
✓   37 features from layer: Area Features
✓    4 features from layer: Line Features
✗ Error reading ii.Airport Funnel: Layer 'ii.Airport Funnel' could not be opened
✓   93 features from layer: Point Features (#2)
✓   29 features from layer: Area Features (#2)
✓  868 features from layer: Line Features (#2)
✗ Error reading iii.Reserve Forest: Layer 'iii.Reserve Forest' could not be opened
✓   70 features from layer: Area Features (#3)
✓    1 features from layer: Line Features (#3)
✗ Error reading iv.Coastal Regulatory: Layer 'iv.Coastal Regulatory' could not be opened
✓    1 features from layer: Area Features (#4)
✗ Error reading v.Animal-Bird Migratory path: Layer 'v.Animal-Bird Migratory path' could not be opened
✓    1 features from layer: Point Features (#3)
✓    1 features from layer: Area Features (#5)
✗ Error reading vi.Defence Protected Area: Layer 'vi.Defence Protected Area' could not be opened
✗ Error reading vii.Heritages: Layer 'vii.Heritages' could not be opened
✓   34 features from layer: Point Features (#4)
✗ Error reading viii.Reserviors: Layer 'viii.Reserviors' could not be opened
✓   73 features from layer: Point Features (#5)
✓   74 features from layer: Area Features (#6)
✗ Error reading ix.MOD: Layer 'ix.MOD' could not be opened
✗ Error reading MH MOD: Layer 'MH MOD' could not be opened
✗ Error reading MH (#2): Layer 'MH (#2)' could not be opened
✓    1 features from layer: Ahmednagar
✗ Error reading Ahmednagar (#2): Layer 'Ahmednagar (#2)' could not be opened
✓    1 features from layer: Ahmednagar_10NM
✗ Error reading Ahmednagar_10NM (#2): Layer 'Ahmednagar_10NM (#2)' could not be opened
✓    1 features from layer: Beed
✗ Error reading Beed (#2): Layer 'Beed (#2)' could not be opened
✓    5 features from layer: Identified Wind Potential Blocks
✗ Error reading Identified Wind Potential Blocks (#2): Layer 'Identified Wind Potential Blocks (#2)' could not be opened
✓    2 features from layer: puneandNDAAirfeld_20km
✗ Error reading puneandNDAAirfeld_20km (#2): Layer 'puneandNDAAirfeld_20km (#2)' could not be opened
✓    2 features from layer: pune_and_nda_airfield_56km_NEW
✗ Error reading pune_and_nda_airfield_56km_NEW (#2): Layer 'pune_and_nda_airfield_56km_NEW (#2)' could not be opened
✓    6 features from layer: Pune_1
✗ Error reading Pune_1 (#2): Layer 'Pune_1 (#2)' could not be opened
✓    1 features from layer: Solapur
✗ Error reading Solapur (#2): Layer 'Solapur (#2)' could not be opened
✓    1 features from layer: Stara
✗ Error reading Stara (#2): Layer 'Stara (#2)' could not be opened
✗ Error reading RJ: Layer 'RJ' could not be opened
✗ Error reading ESZ-RJ: Layer 'ESZ-RJ' could not be opened
✗ Error reading i.Sancturies (#2): Layer 'i.Sancturies (#2)' could not be opened
✓   21 features from layer: Point Features (#6)
✓   22 features from layer: Area Features (#7)
✓    1 features from layer: Line Features (#4)
✗ Error reading ii.Airport funnel (#2): Layer 'ii.Airport funnel (#2)' could not be opened
✗ Error reading Extrusion zone_Airport Funnel.kmz (#2): Layer 'Extrusion zone_Airport Funnel.kmz (#2)' could not be opened
✓   10 features from layer: Point Features (#7)
✓   20 features from layer: Area Features (#8)
✓   54 features from layer: Line Features (#5)
✗ Error reading iii.Reserve Forest (#2): Layer 'iii.Reserve Forest (#2)' could not be opened
✓    3 features from layer: Area Features (#9)
✓  100 features from layer: Line Features (#6)
✗ Error reading iv.Coastal Regulatory (#2): Layer 'iv.Coastal Regulatory (#2)' could not be opened
✗ Error reading v.Animal-bird Migratory Path (#2): Layer 'v.Animal-bird Migratory Path (#2)' could not be opened
✓    1 features from layer: Mukundara Tiger Reserve
✗ Error reading Mukundara Tiger Reserve (#2): Layer 'Mukundara Tiger Reserve (#2)' could not be opened
✓    1 features from layer: Area Features (#10)
✗ Error reading vi.Defence protected Area (#2): Layer 'vi.Defence protected Area (#2)' could not be opened
✗ Error reading vii.Heritages (#2): Layer 'vii.Heritages (#2)' could not be opened
✗ Error reading viii.Reservoir: Layer 'viii.Reservoir' could not be opened
✗ Error reading GJ: Layer 'GJ' could not be opened
✗ Error reading GJ (#2): Layer 'GJ (#2)' could not be opened
✗ Error reading GJ-ESZ: Layer 'GJ-ESZ' could not be opened
✗ Error reading i. Sanctuaries: Layer 'i. Sanctuaries' could not be opened
✓   11 features from layer: Point Features (#8)
✓    4 features from layer: Area Features (#11)
✓    8 features from layer: Area Features (#12)
✓    7 features from layer: Line Features (#7)
✗ Error reading ii. Airport Funnel: Layer 'ii. Airport Funnel' could not be opened
✓  460 features from layer: Line Features (#8)
✓  166 features from layer: Area Features (#13)
✓  402 features from layer: Point Features (#9)
✓   30 features from layer: iii. Reserve Forest
✓   32 features from layer: Point Features (#10)
✓  139 features from layer: Area Features (#14)
✓  802 features from layer: Line Features (#9)
✗ Error reading iv. Coastal Regulatory: Layer 'iv. Coastal Regulatory' could not be opened
✓    1 features from layer: Area Features (#15)
✗ Error reading v. Animal/Bird Migratory Path: Layer 'v. Animal/Bird Migratory Path' could not be opened
✓    3 features from layer: vi. Defence Protected Area
✓    1 features from layer: Area Features (#16)
✗ Error reading vii. Heritages: Layer 'vii. Heritages' could not be opened
✓   12 features from layer: Point Features (#11)
✓    7 features from layer: Line Features (#10)
✗ Error reading viii. Reserviors: Layer 'viii. Reserviors' could not be opened
✓   37 features from layer: Area Features (#17)
✓   60 features from layer: Point Features (#12)
✗ Error reading ix. MOD Boundaries: Layer 'ix. MOD Boundaries' could not be opened
✗ Error reading MOD Boundaries: Layer 'MOD Boundaries' could not be opened
✗ Error reading No wtg zone-block4: Layer 'No wtg zone-block4' could not be opened
✓    1 features from layer: No wtg mod remarks-14062024
✗ Error reading shoreline25km buffer-block4: Layer 'shoreline25km buffer-block4' could not be opened
✓    1 features from layer: shoreline25km buffer
✓    1 features from layer: Amreli_1
✗ Error reading Amreli_1 (#2): Layer 'Amreli_1 (#2)' could not be opened
✓    1 features from layer: Amreli_2
✗ Error reading Amreli_2 (#2): Layer 'Amreli_2 (#2)' could not be opened
✓    6 features from layer: GJ_Blocks (GJ)
✗ Error reading GJ_Blocks (#2): Layer 'GJ_Blocks (#2)' could not be opened
✓    1 features from layer: IAF
✗ Error reading IAF (#2): Layer 'IAF (#2)' could not be opened
✓    2 features from layer: JamANDkhamairfiled_20km
✗ Error reading JamANDkhamairfiled_20km (#2): Layer 'JamANDkhamairfiled_20km (#2)' could not be opened
✓    2 features from layer: Jamnagar_and_khambaliya_airfield_56km
✗ Error reading Jamnagar_and_khambaliya_airfield_56km (#2): Layer 'Jamnagar_and_khambaliya_airfield_56km (#2)' could not be opened
✓    1 features from layer: Jamnagar_1
✗ Error reading Jamnagar_1 (#2): Layer 'Jamnagar_1 (#2)' could not be opened
✓    2 features from layer: Jamnagar_2
✗ Error reading Jamnagar_2 (#2): Layer 'Jamnagar_2 (#2)' could not be opened
✓    1 features from layer: Kutch_1
✗ Error reading Kutch_1 (#2): Layer 'Kutch_1 (#2)' could not be opened
✓    1 features from layer: Kutch_2
✗ Error reading Kutch_2 (#2): Layer 'Kutch_2 (#2)' could not be opened
✓    1 features from layer: Kutch_6NM
✗ Error reading Kutch_6NM (#2): Layer 'Kutch_6NM (#2)' could not be opened
✗ Error reading Naliya and Bhuj airfield_20km: Layer 'Naliya and Bhuj airfield_20km' could not be opened
✓    2 features from layer: No WTG Zone (TG)
✗ Error reading Naliya and Bhuj airfield_56km: Layer 'Naliya and Bhuj airfield_56km' could not be opened
✓    2 features from layer: NOC to be obtained
✓    1 features from layer: Rajkot
✗ Error reading Rajkot (#2): Layer 'Rajkot (#2)' could not be opened
✗ Error reading MP: Layer 'MP' could not be opened
✗ Error reading MP (#2): Layer 'MP (#2)' could not be opened
✗ Error reading MP- ESZ: Layer 'MP- ESZ' could not be opened
✗ Error reading i. Sanctuaries (#2): Layer 'i. Sanctuaries (#2)' could not be opened
✓   25 features from layer: Point Features (#13)
✓   21 features from layer: Area Features (#18)
✗ Error reading ii. Airport Funnel (#2): Layer 'ii. Airport Funnel (#2)' could not be opened
✓  117 features from layer: Point Features (#14)
✓  230 features from layer: Area Features (#19)
✓  605 features from layer: Line Features (#11)
✗ Error reading iii. Reserve Forest (#2): Layer 'iii. Reserve Forest (#2)' could not be opened
✗ Error reading iv. Animal/Bird Migratory Path: Layer 'iv. Animal/Bird Migratory Path' could not be opened
✗ Error reading v. Defence Protected Area: Layer 'v. Defence Protected Area' could not be opened
✗ Error reading vi. Heritages: Layer 'vi. Heritages' could not be opened
✗ Error reading vii. Reserviors: Layer 'vii. Reserviors' could not be opened
✓   11 features from layer: Point Features (#15)
✓   11 features from layer: Area Features (#20)
✗ Error reading viii. MOD Boundaries: Layer 'viii. MOD Boundaries' could not be opened
✗ Error reading Identified Wind Potential Blocks (#3): Layer 'Identified Wind Potential Blocks (#3)' could not be opened
✓    3 features from layer: MP_bloacks (MP)
✗ Error reading ESZ-South: Layer 'ESZ-South' could not be opened
✗ Error reading KA: Layer 'KA' could not be opened
✗ Error reading KA-ESZ: Layer 'KA-ESZ' could not be opened
✗ Error reading ii. Airport Funnel (#3): Layer 'ii. Airport Funnel (#3)' could not be opened
✓   19 features from layer: Airport Name-KA (KA)
✓ 1465 features from layer: Airport Funnel-KA (KA)
✗ Error reading i. Sancturies: Layer 'i. Sancturies' could not be opened
✓   30 features from layer: Santuries boundary
✓   30 features from layer: Santuries name
✗ Error reading iii. Reserve Forest (#3): Layer 'iii. Reserve Forest (#3)' could not be opened
✗ Error reading Reserve Forest: Layer 'Reserve Forest' could not be opened
✓ 1308 features from layer: RF Boundary
✓  848 features from layer: RF name
✗ Error reading iv. Coastal Regulatory Zone: Layer 'iv. Coastal Regulatory Zone' could not be opened
✓   17 features from layer: CRZ_KA (KA)
✗ Error reading v. Animal / Bird Migratory path: Layer 'v. Animal / Bird Migratory path' could not be opened
✓    8 features from layer: Ex. Place name of EC
✓    2 features from layer: vi. Defence Protected Area (#2)
✗ Error reading vii. Heritages (#2): Layer 'vii. Heritages (#2)' could not be opened
✗ Error reading Heritage_KA.KMZ: Layer 'Heritage_KA.KMZ' could not be opened
✓   21 features from layer: Heritage_Places, KA (KA)
✓   21 features from layer: Circle 01 Kms_Heritage Place
✓   29 features from layer: viii. Reservoirs
✗ Error reading AP: Layer 'AP' could not be opened
✗ Error reading AP-ESZ: Layer 'AP-ESZ' could not be opened
✗ Error reading i. Sanctuary: Layer 'i. Sanctuary' could not be opened
✗ Error reading AP (#2): Layer 'AP (#2)' could not be opened
✓   21 features from layer: Santuries boundary (#2)
✓   18 features from layer: Santuries name (#2)
✗ Error reading ii. Airport Funnel (#4): Layer 'ii. Airport Funnel (#4)' could not be opened
✗ Error reading Airport_AP: Layer 'Airport_AP' could not be opened
✓    8 features from layer: Airport Name-AP (AP)
✓  544 features from layer: Airport Funnel-AP (AP)
✗ Error reading iii. Reserve Forest (#4): Layer 'iii. Reserve Forest (#4)' could not be opened
✗ Error reading Reserve Forest_AP: Layer 'Reserve Forest_AP' could not be opened
✓  187 features from layer: RF Boundary (#2)
✓  147 features from layer: RF name (#2)
✗ Error reading iv. Coastal Regulatory Zone (#2): Layer 'iv. Coastal Regulatory Zone (#2)' could not be opened
✓   75 features from layer: CRZ_AP (AP)
✗ Error reading v. Animal / Bird Migratory path (#2): Layer 'v. Animal / Bird Migratory path (#2)' could not be opened
✗ Error reading vi. Defence Protected Area (#3): Layer 'vi. Defence Protected Area (#3)' could not be opened
✗ Error reading vii. Heritages (#3): Layer 'vii. Heritages (#3)' could not be opened
✓   20 features from layer: Heritage_Places, AP (AP)
✓   20 features from layer: Circle 01 Kms_Heritage Place (#2)
✗ Error reading viii. Reservoirs (#2): Layer 'viii. Reservoirs (#2)' could not be opened
✓   46 features from layer: Reservoirs_AP (AP)
✗ Error reading TN: Layer 'TN' could not be opened
✗ Error reading TN-ESZ: Layer 'TN-ESZ' could not be opened
✗ Error reading i. Sancturies (#2): Layer 'i. Sancturies (#2)' could not be opened
✓   21 features from layer: Santuries boundary (#3)
✓   21 features from layer: Santuries name (#3)
✗ Error reading ii. Airport Funnel (#5): Layer 'ii. Airport Funnel (#5)' could not be opened
✓   19 features from layer: Airport name-TN&KL (TN)
✓ 1340 features from layer: Airport Funnel-TN&KL (TN)
✗ Error reading iii. Reserve Forest (#5): Layer 'iii. Reserve Forest (#5)' could not be opened
✗ Error reading iv. Coastal Regulatory Zone (#3): Layer 'iv. Coastal Regulatory Zone (#3)' could not be opened
✓   30 features from layer: TN CRZ (TN)
✗ Error reading v. Animal / Bird Migratory path (#3): Layer 'v. Animal / Bird Migratory path (#3)' could not be opened
✗ Error reading vi. Defence Protected Area (#4): Layer 'vi. Defence Protected Area (#4)' could not be opened
✗ Error reading vii. Heritages (#4): Layer 'vii. Heritages (#4)' could not be opened
✗ Error reading TN Heritage place: Layer 'TN Heritage place' could not be opened
✓   18 features from layer: Circle 01 Kms_Heritage Place (#3)
✓   18 features from layer: Heritage_Places, TN (TN)
✓   21 features from layer: Heritage_Places, KL (KL)
✓   21 features from layer: Circle 01 Kms_Heritage Place (#4)
✓   42 features from layer: viii. Reservoir
✗ Error reading ix.ESZ-Agri Protected Zone: Layer 'ix.ESZ-Agri Protected Zone' could not be opened
✗ Error reading ESZ-Agri Protected Zone.KMZ: Layer 'ESZ-Agri Protected Zone.KMZ' could not be opened
✓   22 features from layer: Point Features (#16)
✓    2 features from layer: Area Features (#21)
✓   21 features from layer: Line Features (#12)
✗ Error reading TG: Layer 'TG' could not be opened
✗ Error reading TG-ESZ: Layer 'TG-ESZ' could not be opened
✗ Error reading i. Sanctuary (#2): Layer 'i. Sanctuary (#2)' could not be opened
✗ Error reading AP (#3): Layer 'AP (#3)' could not be opened
✓   21 features from layer: Santuries boundary (#4)
✓   18 features from layer: Santuries name (#4)
✗ Error reading TG (#2): Layer 'TG (#2)' could not be opened
✓   11 features from layer: Santuries boundary (#5)
✓   11 features from layer: Santuries name (#5)
✗ Error reading ii. Airport Funnel (#6): Layer 'ii. Airport Funnel (#6)' could not be opened
✗ Error reading Airport_TG: Layer 'Airport_TG' could not be opened
✓    7 features from layer: Airport Name-TG (TG)
✓  536 features from layer: Airport Funnel-TG (TG)
✗ Error reading Airport_AP (#2): Layer 'Airport_AP (#2)' could not be opened
✓    8 features from layer: Airport Name-AP (#2) (AP)
✓  544 features from layer: Airport Funnel-AP (#2) (AP)
✗ Error reading iii. Reserve Forest (#6): Layer 'iii. Reserve Forest (#6)' could not be opened
✗ Error reading Reserve Forest_AP (#2): Layer 'Reserve Forest_AP (#2)' could not be opened
✓  187 features from layer: RF Boundary (#3)
✓  147 features from layer: RF name (#3)
✗ Error reading Reserve Forest_TG: Layer 'Reserve Forest_TG' could not be opened
✓   25 features from layer: RF Boundary (#4)
✓   39 features from layer: RF name (#4)
✗ Error reading iv. Coastal Regulatory Zone (#4): Layer 'iv. Coastal Regulatory Zone (#4)' could not be opened
✓   75 features from layer: CRZ_AP (#2) (AP)
✗ Error reading v. Animal / Bird Migratory path (#4): Layer 'v. Animal / Bird Migratory path (#4)' could not be opened
✗ Error reading vi. Defence Protected Area (#5): Layer 'vi. Defence Protected Area (#5)' could not be opened
✗ Error reading vii. Heritages (#5): Layer 'vii. Heritages (#5)' could not be opened
✓   20 features from layer: Heritage_Places, AP (#2) (AP)
✓   20 features from layer: Circle 01 Kms_Heritage Place (#5)
✗ Error reading viii. Reservoirs (#3): Layer 'viii. Reservoirs (#3)' could not be opened
✓   63 features from layer: Reservoirs-TG (TG)
✓   46 features from layer: Reservoirs_AP (#2) (AP)

======================================================================
SUMMARY
======================================================================
Total features extracted: 13,061
Total layers processed: 128

Geometry types:
LineString      8525
Polygon         2932
Point           1554
MultiPolygon      50
Name: count, dtype: int64

Columns: ['Name', 'Description', 'geometry', 'layer_name', 'state_code', 'state_name']

Features by state:
  KA (Karnataka): 1,522
  TN (Tamil Nadu): 1,407
  AP (Andhra Pradesh): 1,386
  TG (Telangana): 608
  KL (Kerala): 21
  GJ (Gujarat): 6
  MP (Madhya Pradesh): 3
  MH (Maharashtra): 2

Sample data:
      Name                 Description state_code  \
0  Block A                                     MH
1  Block B                                     MH
2  FEATURE  EXTRUSION_ZONE_SANCTUARIES       None
3  FEATURE  EXTRUSION_ZONE_SANCTUARIES       None
4  FEATURE  EXTRUSION_ZONE_SANCTUARIES       None
5  FEATURE  EXTRUSION_ZONE_SANCTUARIES       None
6  FEATURE  EXTRUSION_ZONE_SANCTUARIES       None
7  FEATURE  EXTRUSION_ZONE_SANCTUARIES       None
8  FEATURE  EXTRUSION_ZONE_SANCTUARIES       None
9  FEATURE  EXTRUSION_ZONE_SANCTUARIES       None

                                            geometry
0  POLYGON Z ((75.49 18.57002 0, 75.55 18.57002 0...
1  POLYGON Z ((75.24 18.86002 0, 75.25002 18.8300...
2                       POINT Z (72.9908 18.99128 0)
3                      POINT Z (75.07968 18.20872 0)
4                      POINT Z (73.87456 16.55496 0)
5                      POINT Z (74.57555 17.44746 0)
6                      POINT Z (74.12003 20.01295 0)
7                      POINT Z (72.89745 19.40617 0)
8                      POINT Z (73.22142 19.60515 0)
9                      POINT Z (72.89745 19.40617 0)

✓ Saved to: d:\OneDrive - Suzlon Energy Ltd\Documents\Deployment\Map Analytics\test_notebooks\esz_combined2.gpkg

In [27]:
import geopandas as gpd
import pandas as pd
import xml.etree.ElementTree as ET
from pathlib import Path
import zipfile
import fiona
import re

notebook_dir = Path.cwd()
extract_dir = notebook_dir / "extracted_kmz"
kml_path = extract_dir / "doc.kml"

print("Fixing XML namespace issue...")

# Read the KML file
with open(kml_path, 'r', encoding='utf-8') as f:
    kml_content = f.read()

# Check if xsi namespace is missing from root element
if 'xmlns:xsi=' not in kml_content[:500]:
    print("Missing xsi namespace - adding it...")
    kml_content = kml_content.replace(
        '<kml xmlns="http://www.opengis.net/kml/2.2"',
        '<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"'
    )
    
    fixed_kml_path = extract_dir / "doc_fixed.kml"
    with open(fixed_kml_path, 'w', encoding='utf-8') as f:
        f.write(kml_content)
    
    kml_path = fixed_kml_path
    print(f"✓ Fixed KML saved to: {kml_path}")

# Parse the fixed file
print("\nAttempting to parse fixed XML...")
tree = ET.parse(kml_path)
root = tree.getroot()
print("✓ XML parsing successful!")

# Define namespace dict
ns = {
    'kml': 'http://www.opengis.net/kml/2.2',
    'atom': 'http://www.w3.org/2005/Atom',
    'xsi': 'http://www.w3.org/2001/XMLSchema-instance'
}

print("\nSearching for embedded KMZ references...")
print(f"DEBUG: Searching for all Document elements...")

# Find all Document elements
all_docs = root.findall('.//kml:Document', ns)
print(f"DEBUG: Found {len(all_docs)} Document elements")

kmz_references = []

# Check each Document
for i, doc in enumerate(all_docs):
    name_elem = doc.find('kml:name', ns)
    doc_name = name_elem.text if name_elem is not None else f"[unnamed-{i}]"
    
    # Debug: show all Document names
    if i < 10:  # Show first 10
        print(f"DEBUG: Document {i}: {doc_name}")
    
    # Check if name ends with .kmz
    if name_elem is not None and name_elem.text and name_elem.text.endswith('.kmz'):
        print(f"\nDEBUG: Found KMZ Document: {doc_name}")
        
        # Look for atom:link - try different ways
        atom_link = doc.find('.//atom:link', ns)
        
        if atom_link is not None:
            # The href is an attribute of atom:link
            href = atom_link.get('href')
            print(f"  Found atom:link with href attribute: {href}")
            
            if href:
                kmz_references.append((doc_name, href))
                print(f"  ✓ Added: {doc_name} -> {href}")
        else:
            print(f"  ✗ No atom:link found in this Document")
            # Debug: show what's inside this Document
            print(f"  Document children: {[child.tag for child in doc]}")

print(f"\n{'='*60}")
print(f"Total KMZ references found: {len(kmz_references)}\n")

# Extract each KMZ file
for kmz_name, href in kmz_references:
    kmz_file = extract_dir / href
    
    if kmz_file.exists():
        nested_dir = extract_dir / kmz_file.stem
        nested_dir.mkdir(exist_ok=True)
        
        print(f"Extracting: {kmz_name}")
        try:
            with zipfile.ZipFile(kmz_file, 'r') as zip_ref:
                zip_ref.extractall(nested_dir)
                print(f"  ✓ Extracted to: {nested_dir.name}")
        except Exception as e:
            print(f"  ✗ Error: {e}")
    else:
        print(f"⚠ File not found: {href}")

# Recursively extract nested KMZ files
def extract_nested_kmz(directory, depth=0):
    indent = "  " * depth
    extracted = False
    
    for kmz_file in directory.rglob("*.kmz"):
        nested_dir = kmz_file.parent / kmz_file.stem
        
        if nested_dir.exists() and any(nested_dir.iterdir()):
            continue
        
        nested_dir.mkdir(exist_ok=True)
        print(f"{indent}Extracting nested: {kmz_file.relative_to(extract_dir)}")
        
        try:
            with zipfile.ZipFile(kmz_file, 'r') as zip_ref:
                zip_ref.extractall(nested_dir)
                extracted = True
        except Exception as e:
            print(f"{indent}  Error: {e}")
    
    return extracted

print("\nExtracting nested KMZ files...")
max_iterations = 5
for i in range(max_iterations):
    if not extract_nested_kmz(extract_dir, i):
        break
    print(f"  Iteration {i+1} complete")

print("\n✓ All KMZ files extracted successfully!")

Fixing XML namespace issue...
Missing xsi namespace - adding it...
✓ Fixed KML saved to: d:\OneDrive - Suzlon Energy Ltd\Documents\Deployment\Map Analytics\test_notebooks\extracted_kmz\doc_fixed.kml

Attempting to parse fixed XML...
✓ XML parsing successful!

Searching for embedded KMZ references...
DEBUG: Searching for all Document elements...
DEBUG: Found 49 Document elements
DEBUG: Document 0: Extrusion zone_Sanctuaries.kmz

DEBUG: Found KMZ Document: Extrusion zone_Sanctuaries.kmz
  ✗ No atom:link found in this Document
  Document children: ['{http://www.opengis.net/kml/2.2}name', '{http://www.opengis.net/kml/2.2}visibility', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}StyleMap', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Folder', '{http://www.opengis.net/kml/2.2}Folder', '{http://www.opengis.net/kml/2.2}Folder']
DEBUG: Document 1: Extrusion zone_Airport Funnel.kmz

DEBUG: Found KMZ Document: Extrusion zone_Airport Funnel.kmz
  ✗ No atom:link found in this Document
  Document children: ['{http://www.opengis.net/kml/2.2}name', '{http://www.opengis.net/kml/2.2}visibility', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}StyleMap', '{http://www.opengis.net/kml/2.2}Folder', '{http://www.opengis.net/kml/2.2}Folder', '{http://www.opengis.net/kml/2.2}Folder']
DEBUG: Document 2: Extrusion Zone_Forest boundary.kmz

DEBUG: Found KMZ Document: Extrusion Zone_Forest boundary.kmz
  ✗ No atom:link found in this Document
  Document children: ['{http://www.opengis.net/kml/2.2}name', '{http://www.opengis.net/kml/2.2}visibility', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}StyleMap', '{http://www.opengis.net/kml/2.2}Folder', '{http://www.opengis.net/kml/2.2}Folder']
DEBUG: Document 3: coastal.kmz

DEBUG: Found KMZ Document: coastal.kmz
  ✗ No atom:link found in this Document
  Document children: ['{http://www.opengis.net/kml/2.2}name', '{http://www.opengis.net/kml/2.2}visibility', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Folder']
DEBUG: Document 4: animal-bird.kmz

DEBUG: Found KMZ Document: animal-bird.kmz
  ✗ No atom:link found in this Document
  Document children: ['{http://www.opengis.net/kml/2.2}name', '{http://www.opengis.net/kml/2.2}visibility', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Folder', '{http://www.opengis.net/kml/2.2}Folder']
DEBUG: Document 5: Extrusion Zone_Protected Heritage.kmz

DEBUG: Found KMZ Document: Extrusion Zone_Protected Heritage.kmz
  ✗ No atom:link found in this Document
  Document children: ['{http://www.opengis.net/kml/2.2}name', '{http://www.opengis.net/kml/2.2}visibility', '{http://www.opengis.net/kml/2.2}StyleMap', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Folder']
DEBUG: Document 6: Extrusion zone_Resorvior.kmz

DEBUG: Found KMZ Document: Extrusion zone_Resorvior.kmz
  ✗ No atom:link found in this Document
  Document children: ['{http://www.opengis.net/kml/2.2}name', '{http://www.opengis.net/kml/2.2}visibility', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}StyleMap', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Folder', '{http://www.opengis.net/kml/2.2}Folder']
DEBUG: Document 7: MH MOD
DEBUG: Document 8: Ahmednagar
DEBUG: Document 9: Ahmednagar_10NM

DEBUG: Found KMZ Document: Extrusion zone_Sanctuary.kmz
  ✗ No atom:link found in this Document
  Document children: ['{http://www.opengis.net/kml/2.2}name', '{http://www.opengis.net/kml/2.2}visibility', '{http://www.opengis.net/kml/2.2}StyleMap', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Folder', '{http://www.opengis.net/kml/2.2}Folder', '{http://www.opengis.net/kml/2.2}Folder']

DEBUG: Found KMZ Document: Extrusion zone_Airport Funnel.kmz
  ✗ No atom:link found in this Document
  Document children: ['{http://www.opengis.net/kml/2.2}name', '{http://www.opengis.net/kml/2.2}visibility', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}StyleMap', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Folder', '{http://www.opengis.net/kml/2.2}Folder', '{http://www.opengis.net/kml/2.2}Folder']

DEBUG: Found KMZ Document: Extrusion zone_Forest.kmz
  ✗ No atom:link found in this Document
  Document children: ['{http://www.opengis.net/kml/2.2}name', '{http://www.opengis.net/kml/2.2}visibility', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}StyleMap', '{http://www.opengis.net/kml/2.2}Folder', '{http://www.opengis.net/kml/2.2}Folder']

DEBUG: Found KMZ Document: RJ-GIB Updated.kmz
  ✗ No atom:link found in this Document
  Document children: ['{http://www.opengis.net/kml/2.2}name', '{http://www.opengis.net/kml/2.2}visibility', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}StyleMap', '{http://www.opengis.net/kml/2.2}Folder']

DEBUG: Found KMZ Document: GJ.kmz
  ✗ No atom:link found in this Document
  Document children: ['{http://www.opengis.net/kml/2.2}name', '{http://www.opengis.net/kml/2.2}visibility', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}StyleMap', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}StyleMap', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}StyleMap', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}StyleMap', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}StyleMap', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}StyleMap', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Folder']

DEBUG: Found KMZ Document: MP.kmz
  ✗ No atom:link found in this Document
  Document children: ['{http://www.opengis.net/kml/2.2}name', '{http://www.opengis.net/kml/2.2}visibility', '{http://www.opengis.net/kml/2.2}StyleMap', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}StyleMap', '{http://www.opengis.net/kml/2.2}StyleMap', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Style', '{http://www.opengis.net/kml/2.2}Folder']

DEBUG: Found KMZ Document: ESZ-South.kmz
  ✗ No atom:link found in this Document

In [26]:
import geopandas as gpd
import pandas as pd
import xml.etree.ElementTree as ET
from pathlib import Path
import zipfile
import fiona

notebook_dir = Path.cwd()
extract_dir = notebook_dir / "extracted_kmz"
kml_path = extract_dir / "doc.kml"
    
fixed_kml_path = extract_dir / "doc_fixed.kml"
kml_path = fixed_kml_path

with open(kml_path, 'r', encoding='utf-8') as f:
    kml_content = f.read()

# Register all namespaces found in the file
import re
namespaces = dict(re.findall(r'xmlns:?([a-z]*?)="([^"]*)"', kml_content))

# Register namespaces with ElementTree
for prefix, uri in namespaces.items():
    if prefix:
        ET.register_namespace(prefix, uri)
    else:
        ET.register_namespace('kml', uri)

# Now parse the file
tree = ET.parse(kml_path)
root = tree.getroot()

# Define namespace dict for searching
ns = {
    'kml': 'http://www.opengis.net/kml/2.2',
    'atom': 'http://www.w3.org/2005/Atom',
    'xsi': 'http://www.w3.org/2001/XMLSchema-instance'
}

print("\nSearching for embedded KMZ references...")

# Find all Document elements that have .kmz names (these are inside Folders)
kmz_references = []

# Search in ALL Document elements (not just top level)
for doc in root.findall('.//kml:Document', ns):
    name_elem = doc.find('kml:name', ns)
    if name_elem is not None and name_elem.text and name_elem.text.endswith('.kmz'):
        # Look for atom:link in this Document
        atom_link = doc.find('.//atom:link', ns)
        if atom_link is not None:
            href = atom_link.get('href')
            if href:
                kmz_references.append((name_elem.text, href))
                print(f"Found KMZ reference: {name_elem.text} -> {href}")

# Also check for NetworkLink elements
for network_link in root.findall('.//kml:NetworkLink', ns):
    name_elem = network_link.find('kml:name', ns)
    href_elem = network_link.find('.//kml:href', ns)
    if href_elem is not None and href_elem.text and href_elem.text.endswith('.kmz'):
        kmz_name = name_elem.text if name_elem is not None else href_elem.text
        kmz_references.append((kmz_name, href_elem.text))
        print(f"Found KMZ reference (NetworkLink): {kmz_name} -> {href_elem.text}")

print(f"\nTotal KMZ references found: {len(kmz_references)}\n")

# Extract each KMZ file
for kmz_name, href in kmz_references:
    kmz_file = extract_dir / href
    
    if kmz_file.exists():
        nested_dir = extract_dir / kmz_file.stem
        nested_dir.mkdir(exist_ok=True)
        
        print(f"Extracting: {kmz_name}")
        try:
            with zipfile.ZipFile(kmz_file, 'r') as zip_ref:
                zip_ref.extractall(nested_dir)
                print(f"  ✓ Extracted to: {nested_dir.name}")
        except Exception as e:
            print(f"  ✗ Error: {e}")
    else:
        print(f"⚠ File not found: {href}")

# Now recursively extract any nested KMZ files
def extract_nested_kmz(directory, depth=0):
    """Recursively extract nested KMZ files"""
    indent = "  " * depth
    extracted = False
    
    for kmz_file in directory.rglob("*.kmz"):
        nested_dir = kmz_file.parent / kmz_file.stem
        
        # Skip if already extracted
        if nested_dir.exists() and any(nested_dir.iterdir()):
            continue
        
        nested_dir.mkdir(exist_ok=True)
        print(f"{indent}Extracting nested: {kmz_file.relative_to(extract_dir)}")
        
        try:
            with zipfile.ZipFile(kmz_file, 'r') as zip_ref:
                zip_ref.extractall(nested_dir)
                extracted = True
        except Exception as e:
            print(f"{indent}  Error: {e}")
    
    return extracted

print("\nExtracting nested KMZ files...")
max_iterations = 5
for i in range(max_iterations):
    if not extract_nested_kmz(extract_dir, i):
        break
    print(f"  Iteration {i+1} complete")

# Now read all KML files found
print("\n" + "="*60)
print("Reading geometry data from all KML files...")
print("="*60 + "\n")

all_gdfs = []
state_mapping = {
    'MH': 'Maharashtra',
    'GJ': 'Gujarat', 
    'RJ': 'Rajasthan',
    'MP': 'Madhya Pradesh',
    'KA': 'Karnataka',
    'AP': 'Andhra Pradesh',
    'TG': 'Telangana',
    'TN': 'Tamil Nadu',
    'KL': 'Kerala'
}

# Find all KML files in extracted directories
for kml_file in extract_dir.rglob("*.kml"):
    try:
        layers = fiona.listlayers(str(kml_file))
        
        for layer in layers:
            # Skip KMZ references
            if layer.endswith('.kmz'):
                continue
            
            try:
                gdf = gpd.read_file(str(kml_file), driver='KML', layer=layer)
                
                if len(gdf) > 0:
                    # Extract state from path or layer name
                    state_code = None
                    path_str = str(kml_file.relative_to(extract_dir))
                    
                    for code in state_mapping.keys():
                        if code in path_str or code in layer:
                            state_code = code
                            break
                    
                    # Add metadata
                    gdf['kml_file'] = kml_file.name
                    gdf['layer_name'] = layer
                    gdf['state_code'] = state_code
                    gdf['state_name'] = state_mapping.get(state_code, None)
                    
                    all_gdfs.append(gdf)
                    
                    state_info = f" ({state_code})" if state_code else ""
                    print(f"✓ {len(gdf):4d} features from {kml_file.relative_to(extract_dir)} / {layer}{state_info}")
                    
            except Exception as e:
                pass  # Skip silently
                
    except Exception as e:
        pass  # Skip silently

# Combine all GeoDataFrames
if all_gdfs:
    combined_gdf = gpd.GeoDataFrame(pd.concat(all_gdfs, ignore_index=True))
    
    print(f"\n{'='*60}")
    print(f"SUMMARY")
    print(f"{'='*60}")
    print(f"Total features: {len(combined_gdf):,}")
    print(f"Total KML layers: {len(all_gdfs)}")
    
    print(f"\nGeometry types:")
    print(combined_gdf.geometry.geom_type.value_counts())
    
    if 'state_code' in combined_gdf.columns:
        print(f"\nFeatures by state:")
        state_counts = combined_gdf['state_code'].value_counts().sort_index()
        for state, count in state_counts.items():
            if state:
                print(f"  {state} ({state_mapping[state]}): {count:,}")
            else:
                print(f"  Unknown: {count:,}")
    
    print(f"\nFirst few rows:")
    display_cols = [col for col in ['Name', 'Description', 'state_code', 'geometry'] if col in combined_gdf.columns]
    print(combined_gdf[display_cols].head())
    
    # Save to file
    output_file = notebook_dir / "esz_combined.gpkg"
    combined_gdf.to_file(output_file, driver='GPKG')
    print(f"\n✓ Saved to: {output_file}")
    
else:
    print("\n⚠ No features extracted")

Searching for embedded KMZ references...

Total KMZ references found: 0


Extracting nested KMZ files...

============================================================
Reading geometry data from all KML files...
============================================================

✓    2 features from doc.kml / MH (MH)
✓   31 features from doc.kml / Point Features
✓   37 features from doc.kml / Area Features
✓    4 features from doc.kml / Line Features
✓   93 features from doc.kml / Point Features (#2)
✓   29 features from doc.kml / Area Features (#2)
✓  868 features from doc.kml / Line Features (#2)
✓   70 features from doc.kml / Area Features (#3)
✓    1 features from doc.kml / Line Features (#3)
✓    1 features from doc.kml / Area Features (#4)
✓    1 features from doc.kml / Point Features (#3)
✓    1 features from doc.kml / Area Features (#5)
✓   34 features from doc.kml / Point Features (#4)
✓   73 features from doc.kml / Point Features (#5)
✓   74 features from doc.kml / Area Features (#6)
✓    1 features from doc.kml / Ahmednagar
✓    1 features from doc.kml / Ahmednagar_10NM
✓    1 features from doc.kml / Beed
✓    5 features from doc.kml / Identified Wind Potential Blocks

KeyboardInterrupt:

In [20]:
import geopandas as gpd
import pandas as pd
import xml.etree.ElementTree as ET
from pathlib import Path
import zipfile
import fiona

notebook_dir = Path.cwd()
extract_dir = notebook_dir / "extracted_kmz"
kml_path = extract_dir / "doc.kml"

# First, let's diagnose the XML parsing issue
print("Diagnosing XML parsing issue...")
print(f"File exists: {kml_path.exists()}")
print(f"File size: {kml_path.stat().st_size} bytes")

# Try to read the first few lines to see if it's valid XML
with open(kml_path, 'r', encoding='utf-8') as f:
    first_lines = [f.readline() for _ in range(10)]
    print("\nFirst 10 lines of KML:")
    for i, line in enumerate(first_lines, 1):
        print(f"{i}: {line.rstrip()}")

# Try parsing with detailed error handling
try:
    print("\nAttempting to parse XML...")
    tree = ET.parse(kml_path)
    root = tree.getroot()
    print("✓ XML parsing successful!")
except ET.ParseError as e:
    print(f"✗ XML ParseError: {e}")
    print(f"  Line: {e.position[0]}, Column: {e.position[1]}")
    
    # Show the problematic line
    with open(kml_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()
        if e.position[0] <= len(lines):
            print(f"\nProblematic line {e.position[0]}:")
            print(lines[e.position[0] - 1])
except Exception as e:
    print(f"✗ Unexpected error: {type(e).__name__}: {e}")
    import traceback
    traceback.print_exc()

Diagnosing XML parsing issue...
File exists: True
File size: 23073520 bytes

First 10 lines of KML:
1: <?xml version="1.0" encoding="UTF-8"?>
2: <kml xmlns="http://www.opengis.net/kml/2.2" xmlns:gx="http://www.google.com/kml/ext/2.2" xmlns:kml="http://www.opengis.net/kml/2.2" xmlns:atom="http://www.w3.org/2005/Atom">
3: <Folder>
4: 	<name>ESZ</name>
5: 	<visibility>0</visibility>
6: 	<Folder>
7: 		<name>ESZ -West</name>
8: 		<visibility>0</visibility>
9: 		<Folder>
10: 			<name>MH</name>

Attempting to parse XML...
ERROR! Session/line number was not unique in database. History logging moved to new session 82
✗ XML ParseError: unbound prefix: line 14673, column 7
  Line: 14673, Column: 7

Problematic line 14673:
							<Document id="Ahmednagar" xsi:schemaLocation="http://www.opengis.net/kml/2.2 http://schemas.opengis.net/kml/2.2.0/ogckml22.xsd http://www.google.com/kml/ext/2.2 http://code.google.com/apis/kml/schema/kml22gx.xsd">

In [21]:
import geopandas as gpd
import pandas as pd
import xml.etree.ElementTree as ET
from pathlib import Path
import zipfile
import fiona
import re

notebook_dir = Path.cwd()
extract_dir = notebook_dir / "extracted_kmz"
kml_path = extract_dir / "doc.kml"

print("Fixing XML namespace issue...")

# Read the KML file
with open(kml_path, 'r', encoding='utf-8') as f:
    kml_content = f.read()

# Check if xsi namespace is missing from root element
if 'xmlns:xsi=' not in kml_content[:500]:  # Check first 500 chars
    print("Missing xsi namespace - adding it...")
    # Add the missing xsi namespace to the root kml element
    kml_content = kml_content.replace(
        '<kml xmlns="http://www.opengis.net/kml/2.2"',
        '<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"'
    )
    
    # Save the fixed version
    fixed_kml_path = extract_dir / "doc_fixed.kml"
    with open(fixed_kml_path, 'w', encoding='utf-8') as f:
        f.write(kml_content)
    
    kml_path = fixed_kml_path
    print(f"✓ Fixed KML saved to: {kml_path}")

# Now parse the fixed file
print("\nAttempting to parse fixed XML...")
tree = ET.parse(kml_path)
root = tree.getroot()
print("✓ XML parsing successful!")

# Define namespace dict for searching
ns = {
    'kml': 'http://www.opengis.net/kml/2.2',
    'atom': 'http://www.w3.org/2005/Atom',
    'xsi': 'http://www.w3.org/2001/XMLSchema-instance'
}

print("\nSearching for embedded KMZ references...")

# Find all Document elements that reference KMZ files
kmz_references = []
for doc in root.findall('.//kml:Document', ns):
    name_elem = doc.find('kml:name', ns)
    if name_elem is not None and name_elem.text and name_elem.text.endswith('.kmz'):
        atom_link = doc.find('.//atom:link', ns)
        if atom_link is not None:
            href = atom_link.get('href')
            if href:
                kmz_references.append((name_elem.text, href))
                print(f"Found KMZ reference: {name_elem.text} -> {href}")

print(f"\nTotal KMZ references found: {len(kmz_references)}\n")

# Extract each KMZ file
for kmz_name, href in kmz_references:
    kmz_file = extract_dir / href
    
    if kmz_file.exists():
        nested_dir = extract_dir / kmz_file.stem
        nested_dir.mkdir(exist_ok=True)
        
        print(f"Extracting: {kmz_name}")
        try:
            with zipfile.ZipFile(kmz_file, 'r') as zip_ref:
                zip_ref.extractall(nested_dir)
                print(f"  ✓ Extracted to: {nested_dir.name}")
        except Exception as e:
            print(f"  ✗ Error: {e}")
    else:
        print(f"⚠ File not found: {href}")

# Recursively extract any nested KMZ files
def extract_nested_kmz(directory, depth=0):
    """Recursively extract nested KMZ files"""
    indent = "  " * depth
    extracted = False
    
    for kmz_file in directory.rglob("*.kmz"):
        nested_dir = kmz_file.parent / kmz_file.stem
        
        # Skip if already extracted
        if nested_dir.exists() and any(nested_dir.iterdir()):
            continue
        
        nested_dir.mkdir(exist_ok=True)
        print(f"{indent}Extracting nested: {kmz_file.relative_to(extract_dir)}")
        
        try:
            with zipfile.ZipFile(kmz_file, 'r') as zip_ref:
                zip_ref.extractall(nested_dir)
                extracted = True
        except Exception as e:
            print(f"{indent}  Error: {e}")
    
    return extracted

print("\nExtracting nested KMZ files...")
max_iterations = 5
for i in range(max_iterations):
    if not extract_nested_kmz(extract_dir, i):
        break
    print(f"  Iteration {i+1} complete")

print("\n✓ All KMZ files extracted successfully!")

Fixing XML namespace issue...
Missing xsi namespace - adding it...
✓ Fixed KML saved to: d:\OneDrive - Suzlon Energy Ltd\Documents\Deployment\Map Analytics\test_notebooks\extracted_kmz\doc_fixed.kml

Attempting to parse fixed XML...
✓ XML parsing successful!

Searching for embedded KMZ references...

Total KMZ references found: 0


Extracting nested KMZ files...

✓ All KMZ files extracted successfully!

In [28]:
import geopandas as gpd
import pandas as pd
import xml.etree.ElementTree as ET
from pathlib import Path
import fiona

notebook_dir = Path.cwd()
extract_dir = notebook_dir / "extracted_kmz"
kml_path = extract_dir / "doc_fixed.kml"

# Parse the XML to build a mapping of layer names to folder paths
tree = ET.parse(kml_path)
root = tree.getroot()

ns = {
    'kml': 'http://www.opengis.net/kml/2.2',
    'atom': 'http://www.w3.org/2005/Atom'
}

# Build a mapping of folder hierarchy
def build_folder_map(element, path=[]):
    """Recursively build a map of folder names to their paths"""
    folder_map = {}
    
    for folder in element:
        if folder.tag.endswith('Folder'):
            name_elem = folder.find('kml:name', ns)
            if name_elem is not None:
                folder_name = name_elem.text
                current_path = path + [folder_name]
                folder_map[folder_name] = current_path
                
                # Recursively process subfolders
                subfolder_map = build_folder_map(folder, current_path)
                folder_map.update(subfolder_map)
    
    return folder_map

folder_map = build_folder_map(root)

# Print folder structure for debugging
print("Folder hierarchy found:")
for folder_name, path in list(folder_map.items())[:20]:
    indent = "  " * (len(path) - 1)
    print(f"{indent}{folder_name}")

# State mapping
state_mapping = {
    'MH': 'Maharashtra',
    'GJ': 'Gujarat', 
    'RJ': 'Rajasthan',
    'MP': 'Madhya Pradesh',
    'KA': 'Karnataka',
    'AP': 'Andhra Pradesh',
    'TG': 'Telangana',
    'TN': 'Tamil Nadu',
    'KL': 'Kerala'
}

# Function to extract state from folder path
def get_state_from_path(folder_path):
    """Extract state code from folder path"""
    for folder in folder_path:
        # Check for state code patterns
        for code in state_mapping.keys():
            if f'{code}-ESZ' in folder or f'ESZ-{code}' in folder or folder == code:
                return code
    return None

# Read all layers
print("\n\nReading geometry layers...")
layers = fiona.listlayers(str(kml_path))
print(f"Total layers: {len(layers)}\n")

all_gdfs = []

for layer_name in layers:
    # Skip KMZ reference layers
    if layer_name.endswith('.kmz'):
        continue
    
    # Skip folder layers (they don't contain geometry)
    if layer_name in ['ESZ', 'ESZ -West', 'ESZ-MH', 'MH', 'GJ', 'RJ', 'KA', 'AP', 'TG', 'TN', 'KL', 'MP']:
        continue
    
    try:
        gdf = gpd.read_file(str(kml_path), driver='KML', layer=layer_name)
        
        if len(gdf) > 0:
            # Find the folder path for this layer
            state_code = None
            
            # Search for state code in layer name first
            for code in state_mapping.keys():
                if code in layer_name:
                    state_code = code
                    break
            
            # If not found in layer name, try to infer from folder hierarchy
            # by checking which folders appear before this layer in the file
            if not state_code:
                # This is a heuristic - layers are read in order of appearance
                # We can track which state folder we're currently in
                for folder_name, folder_path in folder_map.items():
                    state = get_state_from_path(folder_path)
                    if state:
                        # Assume this layer belongs to the most recently encountered state
                        state_code = state
                        break
            
            # Add metadata
            gdf['layer_name'] = layer_name
            gdf['state_code'] = state_code
            gdf['state_name'] = state_mapping.get(state_code, None) if state_code else None
            
            all_gdfs.append(gdf)
            
            state_info = f" ({state_code})" if state_code else ""
            print(f"✓ {len(gdf):4d} features from layer: {layer_name}{state_info}")
            
    except Exception as e:
        print(f"✗ Error reading {layer_name}: {e}")

# Combine all GeoDataFrames
if all_gdfs:
    combined_gdf = gpd.GeoDataFrame(pd.concat(all_gdfs, ignore_index=True))
    
    print(f"\n{'='*70}")
    print(f"SUMMARY")
    print(f"{'='*70}")
    print(f"Total features extracted: {len(combined_gdf):,}")
    print(f"Total layers processed: {len(all_gdfs)}")
    
    print(f"\nGeometry types:")
    print(combined_gdf.geometry.geom_type.value_counts())
    
    print(f"\nColumns: {combined_gdf.columns.tolist()}")
    
    if 'state_code' in combined_gdf.columns:
        print(f"\nFeatures by state:")
        state_counts = combined_gdf['state_code'].value_counts().sort_index()
        for state, count in state_counts.items():
            if state:
                print(f"  {state} ({state_mapping[state]}): {count:,}")
            else:
                print(f"  Unknown: {count:,}")
    
    print(f"\nSample data:")
    display_cols = [col for col in ['Name', 'Description', 'state_code', 'geometry'] if col in combined_gdf.columns]
    print(combined_gdf[display_cols].head(10))
    
    # Save to file
    output_file = notebook_dir / "esz_combined.gpkg"
    combined_gdf.to_file(output_file, driver='GPKG')
    print(f"\n✓ Saved to: {output_file}")
    
else:
    print("\n⚠ No features extracted")

Folder hierarchy found:
ESZ
  ESZ -West
    MH
      ESZ-MH
        i.Sancturies
        ii.Airport Funnel
        iii.Reserve Forest
        iv.Coastal Regulatory
        v.Animal-Bird Migratory path
        vi.Defence Protected Area
        vii.Heritages
        viii.Reserviors
        ix.MOD
    RJ
      ESZ-RJ
        ii.Airport funnel
        v.Animal-bird Migratory Path
        vi.Defence protected Area
        viii.Reservoir
    GJ


Reading geometry layers...
Total layers: 267

✗ Error reading i.Sancturies: Layer 'i.Sancturies' could not be opened
✓   31 features from layer: Point Features (MH)
✓   37 features from layer: Area Features (MH)
✓    4 features from layer: Line Features (MH)
✗ Error reading ii.Airport Funnel: Layer 'ii.Airport Funnel' could not be opened
✓   93 features from layer: Point Features (#2) (MH)
✓   29 features from layer: Area Features (#2) (MH)
✓  868 features from layer: Line Features (#2) (MH)
✗ Error reading iii.Reserve Forest: Layer 'iii.Reserve Forest' could not be opened
✓   70 features from layer: Area Features (#3) (MH)
✓    1 features from layer: Line Features (#3) (MH)
✗ Error reading iv.Coastal Regulatory: Layer 'iv.Coastal Regulatory' could not be opened
✓    1 features from layer: Area Features (#4) (MH)
✗ Error reading v.Animal-Bird Migratory path: Layer 'v.Animal-Bird Migratory path' could not be opened
✓    1 features from layer: Point Features (#3) (MH)
✓    1 features from layer: Area Features (#5) (MH)
✗ Error reading vi.Defence Protected Area: Layer 'vi.Defence Protected Area' could not be opened
✗ Error reading vii.Heritages: Layer 'vii.Heritages' could not be opened
✓   34 features from layer: Point Features (#4) (MH)
✗ Error reading viii.Reserviors: Layer 'viii.Reserviors' could not be opened
✓   73 features from layer: Point Features (#5) (MH)
✓   74 features from layer: Area Features (#6) (MH)
✗ Error reading ix.MOD: Layer 'ix.MOD' could not be opened
✗ Error reading MH MOD: Layer 'MH MOD' could not be opened
✗ Error reading MH (#2): Layer 'MH (#2)' could not be opened
✓    1 features from layer: Ahmednagar (MH)
✗ Error reading Ahmednagar (#2): Layer 'Ahmednagar (#2)' could not be opened
✓    1 features from layer: Ahmednagar_10NM (MH)
✗ Error reading Ahmednagar_10NM (#2): Layer 'Ahmednagar_10NM (#2)' could not be opened
✓    1 features from layer: Beed (MH)
✗ Error reading Beed (#2): Layer 'Beed (#2)' could not be opened
✓    5 features from layer: Identified Wind Potential Blocks (MH)
✗ Error reading Identified Wind Potential Blocks (#2): Layer 'Identified Wind Potential Blocks (#2)' could not be opened
✓    2 features from layer: puneandNDAAirfeld_20km (MH)
✗ Error reading puneandNDAAirfeld_20km (#2): Layer 'puneandNDAAirfeld_20km (#2)' could not be opened
✓    2 features from layer: pune_and_nda_airfield_56km_NEW (MH)
✗ Error reading pune_and_nda_airfield_56km_NEW (#2): Layer 'pune_and_nda_airfield_56km_NEW (#2)' could not be opened
✓    6 features from layer: Pune_1 (MH)
✗ Error reading Pune_1 (#2): Layer 'Pune_1 (#2)' could not be opened
✓    1 features from layer: Solapur (MH)
✗ Error reading Solapur (#2): Layer 'Solapur (#2)' could not be opened
✓    1 features from layer: Stara (MH)
✗ Error reading Stara (#2): Layer 'Stara (#2)' could not be opened
✗ Error reading ESZ-RJ: Layer 'ESZ-RJ' could not be opened
✗ Error reading i.Sancturies (#2): Layer 'i.Sancturies (#2)' could not be opened
✓   21 features from layer: Point Features (#6) (MH)
✓   22 features from layer: Area Features (#7) (MH)
✓    1 features from layer: Line Features (#4) (MH)
✗ Error reading ii.Airport funnel (#2): Layer 'ii.Airport funnel (#2)' could not be opened
✗ Error reading Extrusion zone_Airport Funnel.kmz (#2): Layer 'Extrusion zone_Airport Funnel.kmz (#2)' could not be opened
✓   10 features from layer: Point Features (#7) (MH)
✓   20 features from layer: Area Features (#8) (MH)
✓   54 features from layer: Line Features (#5) (MH)
✗ Error reading iii.Reserve Forest (#2): Layer 'iii.Reserve Forest (#2)' could not be opened
✓    3 features from layer: Area Features (#9) (MH)
✓  100 features from layer: Line Features (#6) (MH)
✗ Error reading iv.Coastal Regulatory (#2): Layer 'iv.Coastal Regulatory (#2)' could not be opened
✗ Error reading v.Animal-bird Migratory Path (#2): Layer 'v.Animal-bird Migratory Path (#2)' could not be opened
✓    1 features from layer: Mukundara Tiger Reserve (MH)
✗ Error reading Mukundara Tiger Reserve (#2): Layer 'Mukundara Tiger Reserve (#2)' could not be opened
✓    1 features from layer: Area Features (#10) (MH)
✗ Error reading vi.Defence protected Area (#2): Layer 'vi.Defence protected Area (#2)' could not be opened
✗ Error reading vii.Heritages (#2): Layer 'vii.Heritages (#2)' could not be opened
✗ Error reading viii.Reservoir: Layer 'viii.Reservoir' could not be opened
✗ Error reading GJ (#2): Layer 'GJ (#2)' could not be opened
✗ Error reading GJ-ESZ: Layer 'GJ-ESZ' could not be opened
✗ Error reading i. Sanctuaries: Layer 'i. Sanctuaries' could not be opened
✓   11 features from layer: Point Features (#8) (MH)
✓    4 features from layer: Area Features (#11) (MH)
✓    8 features from layer: Area Features (#12) (MH)
✓    7 features from layer: Line Features (#7) (MH)
✗ Error reading ii. Airport Funnel: Layer 'ii. Airport Funnel' could not be opened
✓  460 features from layer: Line Features (#8) (MH)
✓  166 features from layer: Area Features (#13) (MH)
✓  402 features from layer: Point Features (#9) (MH)
✓   30 features from layer: iii. Reserve Forest (MH)
✓   32 features from layer: Point Features (#10) (MH)
✓  139 features from layer: Area Features (#14) (MH)
✓  802 features from layer: Line Features (#9) (MH)
✗ Error reading iv. Coastal Regulatory: Layer 'iv. Coastal Regulatory' could not be opened
✓    1 features from layer: Area Features (#15) (MH)
✗ Error reading v. Animal/Bird Migratory Path: Layer 'v. Animal/Bird Migratory Path' could not be opened
✓    3 features from layer: vi. Defence Protected Area (MH)
✓    1 features from layer: Area Features (#16) (MH)
✗ Error reading vii. Heritages: Layer 'vii. Heritages' could not be opened
✓   12 features from layer: Point Features (#11) (MH)
✓    7 features from layer: Line Features (#10) (MH)
✗ Error reading viii. Reserviors: Layer 'viii. Reserviors' could not be opened
✓   37 features from layer: Area Features (#17) (MH)
✓   60 features from layer: Point Features (#12) (MH)
✗ Error reading ix. MOD Boundaries: Layer 'ix. MOD Boundaries' could not be opened
✗ Error reading MOD Boundaries: Layer 'MOD Boundaries' could not be opened
✗ Error reading No wtg zone-block4: Layer 'No wtg zone-block4' could not be opened
✓    1 features from layer: No wtg mod remarks-14062024 (MH)
✗ Error reading shoreline25km buffer-block4: Layer 'shoreline25km buffer-block4' could not be opened
✓    1 features from layer: shoreline25km buffer (MH)
✓    1 features from layer: Amreli_1 (MH)
✗ Error reading Amreli_1 (#2): Layer 'Amreli_1 (#2)' could not be opened
✓    1 features from layer: Amreli_2 (MH)
✗ Error reading Amreli_2 (#2): Layer 'Amreli_2 (#2)' could not be opened
✓    6 features from layer: GJ_Blocks (GJ)
✗ Error reading GJ_Blocks (#2): Layer 'GJ_Blocks (#2)' could not be opened
✓    1 features from layer: IAF (MH)
✗ Error reading IAF (#2): Layer 'IAF (#2)' could not be opened
✓    2 features from layer: JamANDkhamairfiled_20km (MH)
✗ Error reading JamANDkhamairfiled_20km (#2): Layer 'JamANDkhamairfiled_20km (#2)' could not be opened
✓    2 features from layer: Jamnagar_and_khambaliya_airfield_56km (MH)
✗ Error reading Jamnagar_and_khambaliya_airfield_56km (#2): Layer 'Jamnagar_and_khambaliya_airfield_56km (#2)' could not be opened
✓    1 features from layer: Jamnagar_1 (MH)
✗ Error reading Jamnagar_1 (#2): Layer 'Jamnagar_1 (#2)' could not be opened
✓    2 features from layer: Jamnagar_2 (MH)
✗ Error reading Jamnagar_2 (#2): Layer 'Jamnagar_2 (#2)' could not be opened
✓    1 features from layer: Kutch_1 (MH)
✗ Error reading Kutch_1 (#2): Layer 'Kutch_1 (#2)' could not be opened
✓    1 features from layer: Kutch_2 (MH)
✗ Error reading Kutch_2 (#2): Layer 'Kutch_2 (#2)' could not be opened
✓    1 features from layer: Kutch_6NM (MH)
✗ Error reading Kutch_6NM (#2): Layer 'Kutch_6NM (#2)' could not be opened
✗ Error reading Naliya and Bhuj airfield_20km: Layer 'Naliya and Bhuj airfield_20km' could not be opened
✓    2 features from layer: No WTG Zone (TG)
✗ Error reading Naliya and Bhuj airfield_56km: Layer 'Naliya and Bhuj airfield_56km' could not be opened
✓    2 features from layer: NOC to be obtained (MH)
✓    1 features from layer: Rajkot (MH)
✗ Error reading Rajkot (#2): Layer 'Rajkot (#2)' could not be opened
✗ Error reading MP (#2): Layer 'MP (#2)' could not be opened
✗ Error reading MP- ESZ: Layer 'MP- ESZ' could not be opened
✗ Error reading i. Sanctuaries (#2): Layer 'i. Sanctuaries (#2)' could not be opened
✓   25 features from layer: Point Features (#13) (MH)
✓   21 features from layer: Area Features (#18) (MH)
✗ Error reading ii. Airport Funnel (#2): Layer 'ii. Airport Funnel (#2)' could not be opened
✓  117 features from layer: Point Features (#14) (MH)
✓  230 features from layer: Area Features (#19) (MH)
✓  605 features from layer: Line Features (#11) (MH)
✗ Error reading iii. Reserve Forest (#2): Layer 'iii. Reserve Forest (#2)' could not be opened
✗ Error reading iv. Animal/Bird Migratory Path: Layer 'iv. Animal/Bird Migratory Path' could not be opened
✗ Error reading v. Defence Protected Area: Layer 'v. Defence Protected Area' could not be opened
✗ Error reading vi. Heritages: Layer 'vi. Heritages' could not be opened
✗ Error reading vii. Reserviors: Layer 'vii. Reserviors' could not be opened
✓   11 features from layer: Point Features (#15) (MH)
✓   11 features from layer: Area Features (#20) (MH)
✗ Error reading viii. MOD Boundaries: Layer 'viii. MOD Boundaries' could not be opened
✗ Error reading Identified Wind Potential Blocks (#3): Layer 'Identified Wind Potential Blocks (#3)' could not be opened
✓    3 features from layer: MP_bloacks (MP)
✗ Error reading ESZ-South: Layer 'ESZ-South' could not be opened
✗ Error reading KA-ESZ: Layer 'KA-ESZ' could not be opened
✗ Error reading ii. Airport Funnel (#3): Layer 'ii. Airport Funnel (#3)' could not be opened
✓   19 features from layer: Airport Name-KA (KA)
✓ 1465 features from layer: Airport Funnel-KA (KA)
✗ Error reading i. Sancturies: Layer 'i. Sancturies' could not be opened
✓   30 features from layer: Santuries boundary (MH)
✓   30 features from layer: Santuries name (MH)
✗ Error reading iii. Reserve Forest (#3): Layer 'iii. Reserve Forest (#3)' could not be opened
✗ Error reading Reserve Forest: Layer 'Reserve Forest' could not be opened
✓ 1308 features from layer: RF Boundary (MH)
✓  848 features from layer: RF name (MH)
✗ Error reading iv. Coastal Regulatory Zone: Layer 'iv. Coastal Regulatory Zone' could not be opened
✓   17 features from layer: CRZ_KA (KA)
✗ Error reading v. Animal / Bird Migratory path: Layer 'v. Animal / Bird Migratory path' could not be opened
✓    8 features from layer: Ex. Place name of EC (MH)
✓    2 features from layer: vi. Defence Protected Area (#2) (MH)
✗ Error reading vii. Heritages (#2): Layer 'vii. Heritages (#2)' could not be opened
✗ Error reading Heritage_KA.KMZ: Layer 'Heritage_KA.KMZ' could not be opened
✓   21 features from layer: Heritage_Places, KA (KA)
✓   21 features from layer: Circle 01 Kms_Heritage Place (MH)
✓   29 features from layer: viii. Reservoirs (MH)
✗ Error reading AP-ESZ: Layer 'AP-ESZ' could not be opened
✗ Error reading i. Sanctuary: Layer 'i. Sanctuary' could not be opened
✗ Error reading AP (#2): Layer 'AP (#2)' could not be opened
✓   21 features from layer: Santuries boundary (#2) (MH)
✓   18 features from layer: Santuries name (#2) (MH)
✗ Error reading ii. Airport Funnel (#4): Layer 'ii. Airport Funnel (#4)' could not be opened
✗ Error reading Airport_AP: Layer 'Airport_AP' could not be opened
✓    8 features from layer: Airport Name-AP (AP)
✓  544 features from layer: Airport Funnel-AP (AP)
✗ Error reading iii. Reserve Forest (#4): Layer 'iii. Reserve Forest (#4)' could not be opened
✗ Error reading Reserve Forest_AP: Layer 'Reserve Forest_AP' could not be opened
✓  187 features from layer: RF Boundary (#2) (MH)
✓  147 features from layer: RF name (#2) (MH)
✗ Error reading iv. Coastal Regulatory Zone (#2): Layer 'iv. Coastal Regulatory Zone (#2)' could not be opened
✓   75 features from layer: CRZ_AP (AP)
✗ Error reading v. Animal / Bird Migratory path (#2): Layer 'v. Animal / Bird Migratory path (#2)' could not be opened
✗ Error reading vi. Defence Protected Area (#3): Layer 'vi. Defence Protected Area (#3)' could not be opened
✗ Error reading vii. Heritages (#3): Layer 'vii. Heritages (#3)' could not be opened
✓   20 features from layer: Heritage_Places, AP (AP)
✓   20 features from layer: Circle 01 Kms_Heritage Place (#2) (MH)
✗ Error reading viii. Reservoirs (#2): Layer 'viii. Reservoirs (#2)' could not be opened
✓   46 features from layer: Reservoirs_AP (AP)
✗ Error reading TN-ESZ: Layer 'TN-ESZ' could not be opened
✗ Error reading i. Sancturies (#2): Layer 'i. Sancturies (#2)' could not be opened
✓   21 features from layer: Santuries boundary (#3) (MH)
✓   21 features from layer: Santuries name (#3) (MH)
✗ Error reading ii. Airport Funnel (#5): Layer 'ii. Airport Funnel (#5)' could not be opened
✓   19 features from layer: Airport name-TN&KL (TN)
✓ 1340 features from layer: Airport Funnel-TN&KL (TN)
✗ Error reading iii. Reserve Forest (#5): Layer 'iii. Reserve Forest (#5)' could not be opened
✗ Error reading iv. Coastal Regulatory Zone (#3): Layer 'iv. Coastal Regulatory Zone (#3)' could not be opened
✓   30 features from layer: TN CRZ (TN)
✗ Error reading v. Animal / Bird Migratory path (#3): Layer 'v. Animal / Bird Migratory path (#3)' could not be opened
✗ Error reading vi. Defence Protected Area (#4): Layer 'vi. Defence Protected Area (#4)' could not be opened
✗ Error reading vii. Heritages (#4): Layer 'vii. Heritages (#4)' could not be opened
✗ Error reading TN Heritage place: Layer 'TN Heritage place' could not be opened
✓   18 features from layer: Circle 01 Kms_Heritage Place (#3) (MH)
✓   18 features from layer: Heritage_Places, TN (TN)
✓   21 features from layer: Heritage_Places, KL (KL)
✓   21 features from layer: Circle 01 Kms_Heritage Place (#4) (MH)
✓   42 features from layer: viii. Reservoir (MH)
✗ Error reading ix.ESZ-Agri Protected Zone: Layer 'ix.ESZ-Agri Protected Zone' could not be opened
✗ Error reading ESZ-Agri Protected Zone.KMZ: Layer 'ESZ-Agri Protected Zone.KMZ' could not be opened
✓   22 features from layer: Point Features (#16) (MH)
✓    2 features from layer: Area Features (#21) (MH)
✓   21 features from layer: Line Features (#12) (MH)
✗ Error reading TG-ESZ: Layer 'TG-ESZ' could not be opened
✗ Error reading i. Sanctuary (#2): Layer 'i. Sanctuary (#2)' could not be opened
✗ Error reading AP (#3): Layer 'AP (#3)' could not be opened
✓   21 features from layer: Santuries boundary (#4) (MH)
✓   18 features from layer: Santuries name (#4) (MH)
✗ Error reading TG (#2): Layer 'TG (#2)' could not be opened
✓   11 features from layer: Santuries boundary (#5) (MH)
✓   11 features from layer: Santuries name (#5) (MH)
✗ Error reading ii. Airport Funnel (#6): Layer 'ii. Airport Funnel (#6)' could not be opened
✗ Error reading Airport_TG: Layer 'Airport_TG' could not be opened
✓    7 features from layer: Airport Name-TG (TG)
✓  536 features from layer: Airport Funnel-TG (TG)
✗ Error reading Airport_AP (#2): Layer 'Airport_AP (#2)' could not be opened
✓    8 features from layer: Airport Name-AP (#2) (AP)
✓  544 features from layer: Airport Funnel-AP (#2) (AP)
✗ Error reading iii. Reserve Forest (#6): Layer 'iii. Reserve Forest (#6)' could not be opened
✗ Error reading Reserve Forest_AP (#2): Layer 'Reserve Forest_AP (#2)' could not be opened
✓  187 features from layer: RF Boundary (#3) (MH)
✓  147 features from layer: RF name (#3) (MH)
✗ Error reading Reserve Forest_TG: Layer 'Reserve Forest_TG' could not be opened
✓   25 features from layer: RF Boundary (#4) (MH)
✓   39 features from layer: RF name (#4) (MH)
✗ Error reading iv. Coastal Regulatory Zone (#4): Layer 'iv. Coastal Regulatory Zone (#4)' could not be opened
✓   75 features from layer: CRZ_AP (#2) (AP)
✗ Error reading v. Animal / Bird Migratory path (#4): Layer 'v. Animal / Bird Migratory path (#4)' could not be opened
✗ Error reading vi. Defence Protected Area (#5): Layer 'vi. Defence Protected Area (#5)' could not be opened
✗ Error reading vii. Heritages (#5): Layer 'vii. Heritages (#5)' could not be opened
✓   20 features from layer: Heritage_Places, AP (#2) (AP)
✓   20 features from layer: Circle 01 Kms_Heritage Place (#5) (MH)
✗ Error reading viii. Reservoirs (#3): Layer 'viii. Reservoirs (#3)' could not be opened
✓   63 features from layer: Reservoirs-TG (TG)
✓   46 features from layer: Reservoirs_AP (#2) (AP)

======================================================================
SUMMARY
======================================================================
Total features extracted: 13,059
Total layers processed: 127

Geometry types:
LineString      8525
Polygon         2930
Point           1554
MultiPolygon      50
Name: count, dtype: int64

Columns: ['Name', 'Description', 'geometry', 'layer_name', 'state_code', 'state_name']

Features by state:
  AP (Andhra Pradesh): 1,386
  GJ (Gujarat): 6
  KA (Karnataka): 1,522
  KL (Kerala): 21
  MH (Maharashtra): 8,106
  MP (Madhya Pradesh): 3
  TG (Telangana): 608
  TN (Tamil Nadu): 1,407

Sample data:
      Name                 Description state_code  \
0  FEATURE  EXTRUSION_ZONE_SANCTUARIES         MH
1  FEATURE  EXTRUSION_ZONE_SANCTUARIES         MH
2  FEATURE  EXTRUSION_ZONE_SANCTUARIES         MH
3  FEATURE  EXTRUSION_ZONE_SANCTUARIES         MH
4  FEATURE  EXTRUSION_ZONE_SANCTUARIES         MH
5  FEATURE  EXTRUSION_ZONE_SANCTUARIES         MH
6  FEATURE  EXTRUSION_ZONE_SANCTUARIES         MH
7  FEATURE  EXTRUSION_ZONE_SANCTUARIES         MH
8  FEATURE  EXTRUSION_ZONE_SANCTUARIES         MH
9  FEATURE  EXTRUSION_ZONE_SANCTUARIES         MH

                        geometry
0   POINT Z (72.9908 18.99128 0)
1  POINT Z (75.07968 18.20872 0)
2  POINT Z (73.87456 16.55496 0)
3  POINT Z (74.57555 17.44746 0)
4  POINT Z (74.12003 20.01295 0)
5  POINT Z (72.89745 19.40617 0)
6  POINT Z (73.22142 19.60515 0)
7  POINT Z (72.89745 19.40617 0)
8   POINT Z (72.9169 19.30923 0)
9  POINT Z (72.87959 19.23263 0)

✓ Saved to: d:\OneDrive - Suzlon Energy Ltd\Documents\Deployment\Map Analytics\test_notebooks\esz_combined.gpkg

In [29]:
import geopandas as gpd
import pandas as pd
import xml.etree.ElementTree as ET
from pathlib import Path
import fiona

notebook_dir = Path.cwd()
extract_dir = notebook_dir / "extracted_kmz"
kml_path = extract_dir / "doc_fixed.kml"

# Parse the XML to build a mapping of layer names to their parent folders
tree = ET.parse(kml_path)
root = tree.getroot()

ns = {
    'kml': 'http://www.opengis.net/kml/2.2',
    'atom': 'http://www.w3.org/2005/Atom'
}

# State mapping
state_mapping = {
    'MH': 'Maharashtra',
    'GJ': 'Gujarat', 
    'RJ': 'Rajasthan',
    'MP': 'Madhya Pradesh',
    'KA': 'Karnataka',
    'AP': 'Andhra Pradesh',
    'TG': 'Telangana',
    'TN': 'Tamil Nadu',
    'KL': 'Kerala'
}

# Category mapping (standardize category names)
category_mapping = {
    'i. Sanctuary': 'Sanctuary',
    'ii. Airport Funnel': 'Airport Funnel',
    'iii. Reserve Forest': 'Reserve Forest',
    'iv. Coastal Regulatory Zone': 'Coastal Regulatory Zone',
    'v. Animal / Bird Migratory path': 'Animal/Bird Migratory Path',
    'vi. Defence Protected Area': 'Defence Protected Area',
    'vii. Heritages': 'Heritage',
    'viii. Reservoirs': 'Reservoir'
}

def build_layer_to_folder_map(element, path=[]):
    """
    Recursively build a mapping of layer names to their parent folder hierarchy.
    Returns: dict mapping layer_name -> {'path': [...], 'state': 'XX', 'category': 'YYY'}
    """
    layer_map = {}
    
    for child in element:
        if child.tag.endswith('Folder'):
            # Get folder name
            name_elem = child.find('kml:name', ns)
            if name_elem is not None:
                folder_name = name_elem.text
                current_path = path + [folder_name]
                
                # Recursively process this folder
                subfolder_map = build_layer_to_folder_map(child, current_path)
                layer_map.update(subfolder_map)
                
        elif child.tag.endswith('Document'):
            # Document elements contain the actual layers
            doc_name_elem = child.find('kml:name', ns)
            if doc_name_elem is not None:
                doc_name = doc_name_elem.text
                
                # Extract state and category from path
                state_code = None
                category = None
                
                # Look for state in path
                for folder in path:
                    for code in state_mapping.keys():
                        if f'{code}-ESZ' in folder or folder == code:
                            state_code = code
                            break
                    
                    # Look for category in path
                    for cat_key, cat_value in category_mapping.items():
                        if cat_key in folder or folder.startswith(cat_key.split('.')[0]):
                            category = cat_value
                            break
                
                # Store mapping
                layer_map[doc_name] = {
                    'path': path.copy(),
                    'state': state_code,
                    'category': category
                }
    
    return layer_map

# Build the layer mapping
print("Building layer to folder mapping...")
layer_to_folder = build_layer_to_folder_map(root)

print(f"Found {len(layer_to_folder)} layer mappings\n")

# Show some examples
print("Sample layer mappings:")
for i, (layer, info) in enumerate(list(layer_to_folder.items())[:10]):
    path_str = " > ".join(info['path'])
    print(f"{layer}:")
    print(f"  Path: {path_str}")
    print(f"  State: {info['state']}, Category: {info['category']}\n")

# Read all layers
print("\n" + "="*70)
print("Reading geometry layers...")
print("="*70 + "\n")

layers = fiona.listlayers(str(kml_path))
print(f"Total layers available: {len(layers)}\n")

all_gdfs = []

for layer_name in layers:
    # Skip KMZ reference layers
    if layer_name.endswith('.kmz'):
        continue
    
    # Skip pure folder layers (no geometry)
    if layer_name in ['ESZ', 'ESZ -West', 'ESZ-South'] + list(state_mapping.keys()):
        continue
    
    # Skip category folder layers
    if any(layer_name.startswith(cat.split('.')[0]) for cat in category_mapping.keys()):
        continue
    
    try:
        gdf = gpd.read_file(str(kml_path), driver='KML', layer=layer_name)
        
        if len(gdf) > 0:
            # Get state and category from mapping
            layer_info = layer_to_folder.get(layer_name, {})
            state_code = layer_info.get('state')
            category = layer_info.get('category')
            
            # Fallback: try to extract from layer name
            if not state_code:
                for code in state_mapping.keys():
                    if code in layer_name:
                        state_code = code
                        break
            
            # Add metadata
            gdf['layer_name'] = layer_name
            gdf['state_code'] = state_code
            gdf['state_name'] = state_mapping.get(state_code, None) if state_code else None
            gdf['category'] = category
            gdf['folder_path'] = ' > '.join(layer_info.get('path', [])) if layer_info else None
            
            all_gdfs.append(gdf)
            
            state_info = f"({state_code})" if state_code else "(??)"
            cat_info = f"[{category}]" if category else "[Unknown]"
            print(f"✓ {len(gdf):4d} features | {state_info:6s} {cat_info:30s} | {layer_name}")
            
    except Exception as e:
        print(f"✗ Error reading {layer_name}: {e}")

# Combine all GeoDataFrames
if all_gdfs:
    combined_gdf = gpd.GeoDataFrame(pd.concat(all_gdfs, ignore_index=True))
    
    print(f"\n{'='*70}")
    print(f"SUMMARY")
    print(f"{'='*70}")
    print(f"Total features: {len(combined_gdf):,}")
    print(f"Total layers: {len(all_gdfs)}")
    
    print(f"\nGeometry types:")
    print(combined_gdf.geometry.geom_type.value_counts())
    
    if 'state_code' in combined_gdf.columns and 'category' in combined_gdf.columns:
        print(f"\nFeatures by state:")
        state_counts = combined_gdf.groupby(['state_code', 'state_name']).size().sort_index()
        for (state, name), count in state_counts.items():
            if state:
                print(f"  {state} ({name}): {count:,}")
        
        print(f"\nFeatures by category:")
        cat_counts = combined_gdf['category'].value_counts().sort_index()
        for cat, count in cat_counts.items():
            print(f"  {cat if cat else 'Unknown':35s}: {count:,}")
        
        print(f"\nFeatures by state and category:")
        pivot = combined_gdf.groupby(['state_code', 'category']).size().unstack(fill_value=0)
        print(pivot)
    
    print(f"\nColumns: {combined_gdf.columns.tolist()}")
    
    print(f"\nSample data:")
    display_cols = [col for col in ['Name', 'state_code', 'category', 'layer_name', 'geometry'] 
                    if col in combined_gdf.columns]
    print(combined_gdf[display_cols].head(15))
    
    # Save to file
    output_file = notebook_dir / "esz_combined.gpkg"
    combined_gdf.to_file(output_file, driver='GPKG')
    print(f"\n✓ Saved to: {output_file}")
    print(f"  Total size: {output_file.stat().st_size / 1024 / 1024:.2f} MB")
    
else:
    print("\n⚠ No features extracted")

Building layer to folder mapping...
Found 15 layer mappings

Sample layer mappings:
Extrusion zone_Sanctuaries.kmz:
  Path: ESZ > ESZ -West > MH > ESZ-MH > i.Sancturies
  State: MH, Category: Sanctuary

Extrusion zone_Airport Funnel.kmz:
  Path: ESZ > ESZ -West > RJ > ESZ-RJ > ii.Airport funnel
  State: RJ, Category: Sanctuary

Extrusion Zone_Forest boundary.kmz:
  Path: ESZ > ESZ -West > MH > ESZ-MH > iii.Reserve Forest
  State: MH, Category: Sanctuary

coastal.kmz:
  Path: ESZ > ESZ -West > MH > ESZ-MH > iv.Coastal Regulatory
  State: MH, Category: Sanctuary

animal-bird.kmz:
  Path: ESZ > ESZ -West > MH > ESZ-MH > v.Animal-Bird Migratory path
  State: MH, Category: Animal/Bird Migratory Path

Extrusion Zone_Protected Heritage.kmz:
  Path: ESZ > ESZ -West > MH > ESZ-MH > vii.Heritages
  State: MH, Category: Animal/Bird Migratory Path

Extrusion zone_Resorvior.kmz:
  Path: ESZ > ESZ -West > MH > ESZ-MH > viii.Reserviors
  State: MH, Category: Animal/Bird Migratory Path

MH MOD:
  Path: ESZ > ESZ -West > MH > ESZ-MH > ix.MOD
  State: MH, Category: Sanctuary

Extrusion zone_Sanctuary.kmz:
  Path: ESZ > ESZ -West > RJ > ESZ-RJ > i.Sancturies
  State: RJ, Category: Sanctuary

Extrusion zone_Forest.kmz:
  Path: ESZ > ESZ -West > RJ > ESZ-RJ > iii.Reserve Forest
  State: RJ, Category: Sanctuary


======================================================================
Reading geometry layers...
======================================================================

Total layers available: 267

✗ Error reading ESZ-MH: Layer 'ESZ-MH' could not be opened
✓   31 features | (??)   [Unknown]                      | Point Features
✓   37 features | (??)   [Unknown]                      | Area Features
✓    4 features | (??)   [Unknown]                      | Line Features
✓   93 features | (??)   [Unknown]                      | Point Features (#2)
✓   29 features | (??)   [Unknown]                      | Area Features (#2)
✓  868 features | (??)   [Unknown]                      | Line Features (#2)
✓   70 features | (??)   [Unknown]                      | Area Features (#3)
✓    1 features | (??)   [Unknown]                      | Line Features (#3)
✓    1 features | (??)   [Unknown]                      | Area Features (#4)
✓    1 features | (??)   [Unknown]                      | Point Features (#3)
✓    1 features | (??)   [Unknown]                      | Area Features (#5)
✓   34 features | (??)   [Unknown]                      | Point Features (#4)
✓   73 features | (??)   [Unknown]                      | Point Features (#5)
✓   74 features | (??)   [Unknown]                      | Area Features (#6)
✗ Error reading MH MOD: Layer 'MH MOD' could not be opened
✗ Error reading MH (#2): Layer 'MH (#2)' could not be opened
✓    1 features | (??)   [Unknown]                      | Ahmednagar
✗ Error reading Ahmednagar (#2): Layer 'Ahmednagar (#2)' could not be opened
✓    1 features | (??)   [Unknown]                      | Ahmednagar_10NM
✗ Error reading Ahmednagar_10NM (#2): Layer 'Ahmednagar_10NM (#2)' could not be opened
✓    1 features | (??)   [Unknown]                      | Beed
✗ Error reading Beed (#2): Layer 'Beed (#2)' could not be opened
✓    5 features | (??)   [Unknown]                      | Identified Wind Potential Blocks
✗ Error reading Identified Wind Potential Blocks (#2): Layer 'Identified Wind Potential Blocks (#2)' could not be opened
✓    2 features | (??)   [Unknown]                      | puneandNDAAirfeld_20km
✗ Error reading puneandNDAAirfeld_20km (#2): Layer 'puneandNDAAirfeld_20km (#2)' could not be opened
✓    2 features | (??)   [Unknown]                      | pune_and_nda_airfield_56km_NEW
✗ Error reading pune_and_nda_airfield_56km_NEW (#2): Layer 'pune_and_nda_airfield_56km_NEW (#2)' could not be opened
✓    6 features | (??)   [Unknown]                      | Pune_1
✗ Error reading Pune_1 (#2): Layer 'Pune_1 (#2)' could not be opened
✓    1 features | (??)   [Unknown]                      | Solapur
✗ Error reading Solapur (#2): Layer 'Solapur (#2)' could not be opened
✓    1 features | (??)   [Unknown]                      | Stara
✗ Error reading Stara (#2): Layer 'Stara (#2)' could not be opened
✗ Error reading ESZ-RJ: Layer 'ESZ-RJ' could not be opened
✓   21 features | (??)   [Unknown]                      | Point Features (#6)
✓   22 features | (??)   [Unknown]                      | Area Features (#7)
✓    1 features | (??)   [Unknown]                      | Line Features (#4)
✗ Error reading Extrusion zone_Airport Funnel.kmz (#2): Layer 'Extrusion zone_Airport Funnel.kmz (#2)' could not be opened
✓   10 features | (??)   [Unknown]                      | Point Features (#7)
✓   20 features | (??)   [Unknown]                      | Area Features (#8)
✓   54 features | (??)   [Unknown]                      | Line Features (#5)
✓    3 features | (??)   [Unknown]                      | Area Features (#9)
✓  100 features | (??)   [Unknown]                      | Line Features (#6)
✓    1 features | (RJ)   [Animal/Bird Migratory Path]   | Mukundara Tiger Reserve
✗ Error reading Mukundara Tiger Reserve (#2): Layer 'Mukundara Tiger Reserve (#2)' could not be opened
✓    1 features | (??)   [Unknown]                      | Area Features (#10)
✗ Error reading GJ (#2): Layer 'GJ (#2)' could not be opened
✗ Error reading GJ-ESZ: Layer 'GJ-ESZ' could not be opened
✓   11 features | (??)   [Unknown]                      | Point Features (#8)
✓    4 features | (??)   [Unknown]                      | Area Features (#11)
✓    8 features | (??)   [Unknown]                      | Area Features (#12)
✓    7 features | (??)   [Unknown]                      | Line Features (#7)
✓  460 features | (??)   [Unknown]                      | Line Features (#8)
✓  166 features | (??)   [Unknown]                      | Area Features (#13)
✓  402 features | (??)   [Unknown]                      | Point Features (#9)
✓   32 features | (??)   [Unknown]                      | Point Features (#10)
✓  139 features | (??)   [Unknown]                      | Area Features (#14)
✓  802 features | (??)   [Unknown]                      | Line Features (#9)
✓    1 features | (??)   [Unknown]                      | Area Features (#15)
✓    1 features | (??)   [Unknown]                      | Area Features (#16)
✓   12 features | (??)   [Unknown]                      | Point Features (#11)
✓    7 features | (??)   [Unknown]                      | Line Features (#10)
✓   37 features | (??)   [Unknown]                      | Area Features (#17)
✓   60 features | (??)   [Unknown]                      | Point Features (#12)
✗ Error reading MOD Boundaries: Layer 'MOD Boundaries' could not be opened
✗ Error reading No wtg zone-block4: Layer 'No wtg zone-block4' could not be opened
✓    1 features | (??)   [Unknown]                      | No wtg mod remarks-14062024
✗ Error reading shoreline25km buffer-block4: Layer 'shoreline25km buffer-block4' could not be opened
✓    1 features | (??)   [Unknown]                      | shoreline25km buffer
✓    1 features | (??)   [Unknown]                      | Amreli_1
✗ Error reading Amreli_1 (#2): Layer 'Amreli_1 (#2)' could not be opened
✓    1 features | (??)   [Unknown]                      | Amreli_2
✗ Error reading Amreli_2 (#2): Layer 'Amreli_2 (#2)' could not be opened
✓    6 features | (GJ)   [Unknown]                      | GJ_Blocks
✗ Error reading GJ_Blocks (#2): Layer 'GJ_Blocks (#2)' could not be opened
✓    1 features | (??)   [Unknown]                      | IAF
✗ Error reading IAF (#2): Layer 'IAF (#2)' could not be opened
✓    2 features | (??)   [Unknown]                      | JamANDkhamairfiled_20km
✗ Error reading JamANDkhamairfiled_20km (#2): Layer 'JamANDkhamairfiled_20km (#2)' could not be opened
✓    2 features | (??)   [Unknown]                      | Jamnagar_and_khambaliya_airfield_56km
✗ Error reading Jamnagar_and_khambaliya_airfield_56km (#2): Layer 'Jamnagar_and_khambaliya_airfield_56km (#2)' could not be opened
✓    1 features | (??)   [Unknown]                      | Jamnagar_1
✗ Error reading Jamnagar_1 (#2): Layer 'Jamnagar_1 (#2)' could not be opened
✓    2 features | (??)   [Unknown]                      | Jamnagar_2
✗ Error reading Jamnagar_2 (#2): Layer 'Jamnagar_2 (#2)' could not be opened
✓    1 features | (??)   [Unknown]                      | Kutch_1
✗ Error reading Kutch_1 (#2): Layer 'Kutch_1 (#2)' could not be opened
✓    1 features | (??)   [Unknown]                      | Kutch_2
✗ Error reading Kutch_2 (#2): Layer 'Kutch_2 (#2)' could not be opened
✓    1 features | (??)   [Unknown]                      | Kutch_6NM
✗ Error reading Kutch_6NM (#2): Layer 'Kutch_6NM (#2)' could not be opened
✗ Error reading Naliya and Bhuj airfield_20km: Layer 'Naliya and Bhuj airfield_20km' could not be opened
✓    2 features | (TG)   [Unknown]                      | No WTG Zone
✗ Error reading Naliya and Bhuj airfield_56km: Layer 'Naliya and Bhuj airfield_56km' could not be opened
✓    2 features | (??)   [Unknown]                      | NOC to be obtained
✓    1 features | (??)   [Unknown]                      | Rajkot
✗ Error reading Rajkot (#2): Layer 'Rajkot (#2)' could not be opened
✗ Error reading MP (#2): Layer 'MP (#2)' could not be opened
✗ Error reading MP- ESZ: Layer 'MP- ESZ' could not be opened
✓   25 features | (??)   [Unknown]                      | Point Features (#13)
✓   21 features | (??)   [Unknown]                      | Area Features (#18)
✓  117 features | (??)   [Unknown]                      | Point Features (#14)
✓  230 features | (??)   [Unknown]                      | Area Features (#19)
✓  605 features | (??)   [Unknown]                      | Line Features (#11)
✓   11 features | (??)   [Unknown]                      | Point Features (#15)
✓   11 features | (??)   [Unknown]                      | Area Features (#20)
✗ Error reading Identified Wind Potential Blocks (#3): Layer 'Identified Wind Potential Blocks (#3)' could not be opened
✓    3 features | (MP)   [Unknown]                      | MP_bloacks
✗ Error reading KA-ESZ: Layer 'KA-ESZ' could not be opened
✓   19 features | (KA)   [Unknown]                      | Airport Name-KA
✓ 1465 features | (KA)   [Unknown]                      | Airport Funnel-KA
✓   30 features | (??)   [Unknown]                      | Santuries boundary
✓   30 features | (??)   [Unknown]                      | Santuries name
✗ Error reading Reserve Forest: Layer 'Reserve Forest' could not be opened
✓ 1308 features | (??)   [Unknown]                      | RF Boundary
✓  848 features | (??)   [Unknown]                      | RF name
✓   17 features | (KA)   [Unknown]                      | CRZ_KA
✓    8 features | (??)   [Unknown]                      | Ex. Place name of EC
✗ Error reading Heritage_KA.KMZ: Layer 'Heritage_KA.KMZ' could not be opened
✓   21 features | (KA)   [Unknown]                      | Heritage_Places, KA
✓   21 features | (??)   [Unknown]                      | Circle 01 Kms_Heritage Place
✗ Error reading AP-ESZ: Layer 'AP-ESZ' could not be opened
✗ Error reading AP (#2): Layer 'AP (#2)' could not be opened
✓   21 features | (??)   [Unknown]                      | Santuries boundary (#2)
✓   18 features | (??)   [Unknown]                      | Santuries name (#2)
✗ Error reading Airport_AP: Layer 'Airport_AP' could not be opened
✓    8 features | (AP)   [Unknown]                      | Airport Name-AP
✓  544 features | (AP)   [Unknown]                      | Airport Funnel-AP
✗ Error reading Reserve Forest_AP: Layer 'Reserve Forest_AP' could not be opened
✓  187 features | (??)   [Unknown]                      | RF Boundary (#2)
✓  147 features | (??)   [Unknown]                      | RF name (#2)
✓   75 features | (AP)   [Unknown]                      | CRZ_AP
✓   20 features | (AP)   [Unknown]                      | Heritage_Places, AP
✓   20 features | (??)   [Unknown]                      | Circle 01 Kms_Heritage Place (#2)
✓   46 features | (AP)   [Unknown]                      | Reservoirs_AP
✗ Error reading TN-ESZ: Layer 'TN-ESZ' could not be opened
✓   21 features | (??)   [Unknown]                      | Santuries boundary (#3)
✓   21 features | (??)   [Unknown]                      | Santuries name (#3)
✓   19 features | (TN)   [Unknown]                      | Airport name-TN&KL
✓ 1340 features | (TN)   [Unknown]                      | Airport Funnel-TN&KL
✓   30 features | (TN)   [Unknown]                      | TN CRZ
✗ Error reading TN Heritage place: Layer 'TN Heritage place' could not be opened
✓   18 features | (??)   [Unknown]                      | Circle 01 Kms_Heritage Place (#3)
✓   18 features | (TN)   [Unknown]                      | Heritage_Places, TN
✓   21 features | (KL)   [Unknown]                      | Heritage_Places, KL
✓   21 features | (??)   [Unknown]                      | Circle 01 Kms_Heritage Place (#4)
✗ Error reading ESZ-Agri Protected Zone.KMZ: Layer 'ESZ-Agri Protected Zone.KMZ' could not be opened
✓   22 features | (??)   [Unknown]                      | Point Features (#16)
✓    2 features | (??)   [Unknown]                      | Area Features (#21)
✓   21 features | (??)   [Unknown]                      | Line Features (#12)
✗ Error reading TG-ESZ: Layer 'TG-ESZ' could not be opened
✗ Error reading AP (#3): Layer 'AP (#3)' could not be opened
✓   21 features | (??)   [Unknown]                      | Santuries boundary (#4)
✓   18 features | (??)   [Unknown]                      | Santuries name (#4)
✗ Error reading TG (#2): Layer 'TG (#2)' could not be opened
✓   11 features | (??)   [Unknown]                      | Santuries boundary (#5)
✓   11 features | (??)   [Unknown]                      | Santuries name (#5)
✗ Error reading Airport_TG: Layer 'Airport_TG' could not be opened
✓    7 features | (TG)   [Unknown]                      | Airport Name-TG
✓  536 features | (TG)   [Unknown]                      | Airport Funnel-TG
✗ Error reading Airport_AP (#2): Layer 'Airport_AP (#2)' could not be opened
✓    8 features | (AP)   [Unknown]                      | Airport Name-AP (#2)
✓  544 features | (AP)   [Unknown]                      | Airport Funnel-AP (#2)
✗ Error reading Reserve Forest_AP (#2): Layer 'Reserve Forest_AP (#2)' could not be opened
✓  187 features | (??)   [Unknown]                      | RF Boundary (#3)
✓  147 features | (??)   [Unknown]                      | RF name (#3)
✗ Error reading Reserve Forest_TG: Layer 'Reserve Forest_TG' could not be opened
✓   25 features | (??)   [Unknown]                      | RF Boundary (#4)
✓   39 features | (??)   [Unknown]                      | RF name (#4)
✓   75 features | (AP)   [Unknown]                      | CRZ_AP (#2)
✓   20 features | (AP)   [Unknown]                      | Heritage_Places, AP (#2)
✓   20 features | (??)   [Unknown]                      | Circle 01 Kms_Heritage Place (#5)
✓   63 features | (TG)   [Unknown]                      | Reservoirs-TG
✓   46 features | (AP)   [Unknown]                      | Reservoirs_AP (#2)

======================================================================
SUMMARY
======================================================================
Total features: 12,953
Total layers: 122

Geometry types:
LineString      8495
Polygon         2855
Point           1553
MultiPolygon      50
Name: count, dtype: int64

Features by state:
  AP (Andhra Pradesh): 1,386
  GJ (Gujarat): 6
  KA (Karnataka): 1,522
  KL (Kerala): 21
  MP (Madhya Pradesh): 3
  RJ (Rajasthan): 1
  TG (Telangana): 608
  TN (Tamil Nadu): 1,407

Features by category:
  Animal/Bird Migratory Path         : 1

Features by state and category:
category    Animal/Bird Migratory Path
state_code
RJ                                   1

Columns: ['Name', 'Description', 'geometry', 'layer_name', 'state_code', 'state_name', 'category', 'folder_path']

Sample data:
       Name state_code category      layer_name                       geometry
0   FEATURE       None     None  Point Features   POINT Z (72.9908 18.99128 0)
1   FEATURE       None     None  Point Features  POINT Z (75.07968 18.20872 0)
2   FEATURE       None     None  Point Features  POINT Z (73.87456 16.55496 0)
3   FEATURE       None     None  Point Features  POINT Z (74.57555 17.44746 0)
4   FEATURE       None     None  Point Features  POINT Z (74.12003 20.01295 0)
5   FEATURE       None     None  Point Features  POINT Z (72.89745 19.40617 0)
6   FEATURE       None     None  Point Features  POINT Z (73.22142 19.60515 0)
7   FEATURE       None     None  Point Features  POINT Z (72.89745 19.40617 0)
8   FEATURE       None     None  Point Features   POINT Z (72.9169 19.30923 0)
9   FEATURE       None     None  Point Features  POINT Z (72.87959 19.23263 0)
10  FEATURE       None     None  Point Features   POINT Z (73.1054 18.89337 0)
11  FEATURE       None     None  Point Features   POINT Z (72.9205 18.43686 0)
12  FEATURE       None     None  Point Features  POINT Z (73.74265 17.58199 0)
13  FEATURE       None     None  Point Features  POINT Z (73.74638 17.18779 0)
14  FEATURE       None     None  Point Features  POINT Z (73.49879 19.13199 0)

✓ Saved to: d:\OneDrive - Suzlon Energy Ltd\Documents\Deployment\Map Analytics\test_notebooks\esz_combined.gpkg
  Total size: 35.41 MB

In [31]:
import geopandas as gpd
import pandas as pd
import xml.etree.ElementTree as ET
from pathlib import Path
import fiona

notebook_dir = Path.cwd()
extract_dir = notebook_dir / "extracted_kmz"
kml_path = extract_dir / "doc_fixed.kml"

# Parse the XML to build a mapping of layer names to their parent folders
tree = ET.parse(kml_path)
root = tree.getroot()

ns = {
    'kml': 'http://www.opengis.net/kml/2.2',
    'atom': 'http://www.w3.org/2005/Atom'
}

# State mapping
state_mapping = {
    'MH': 'Maharashtra',
    'GJ': 'Gujarat', 
    'RJ': 'Rajasthan',
    'MP': 'Madhya Pradesh',
    'KA': 'Karnataka',
    'AP': 'Andhra Pradesh',
    'TG': 'Telangana',
    'TN': 'Tamil Nadu',
    'KL': 'Kerala'
}

# Category mapping (handle variations and spelling mistakes)
category_patterns = {
    'Sanctuary': ['i. Sanctuary', 'i.Sancturies', 'i. Sanctuaries', 'Sancturies', 'Sanctuary'],
    'Airport Funnel': ['ii. Airport Funnel', 'ii.Airport Funnel', 'ii.Airport funnel', 'Airport Funnel'],
    'Reserve Forest': ['iii. Reserve Forest', 'iii.Reserve Forest', 'Reserve Forest'],
    'Coastal Regulatory Zone': ['iv. Coastal Regulatory Zone', 'iv.Coastal Regulatory', 'iv. Coastal Regulatory'],
    'Animal/Bird Migratory Path': ['v. Animal / Bird Migratory path', 'v. Animal/Bird Migratory Path', 'v.Animal-Bird Migratory path', 'v.Animal-bird Migratory Path'],
    'Defence Protected Area': ['vi. Defence Protected Area', 'vi.Defence Protected Area', 'vi.Defence protected Area'],
    'Heritage': ['vii. Heritages', 'vii. Heritage', 'vii.Heritages'],
    'Reservoir': ['viii. Reservoirs', 'viii. Reservoir', 'viii.Reserviors', 'viii.Reserviors'],
    'MOD': ['ix. MOD', 'ix.MOD', 'MOD Boundaries', 'ix. MOD Boundaries'],
    'Agri Protected Zone': ['ix.ESZ-Agri Protected Zone', 'ESZ-Agri Protected Zone']
}

def match_category(folder_name):
    """Match folder name to standardized category"""
    if not folder_name:
        return None
    
    for standard_cat, patterns in category_patterns.items():
        for pattern in patterns:
            if pattern in folder_name or folder_name.startswith(pattern.split('.')[0]):
                return standard_cat
    return None

def build_layer_hierarchy(element, path=[], state_context=None, category_context=None):
    """
    Build a complete hierarchy mapping each layer to its state and category.
    Tracks folder context as we traverse the XML tree.
    """
    layer_map = {}
    
    for child in element:
        if child.tag.endswith('Folder'):
            name_elem = child.find('kml:name', ns)
            if name_elem is not None:
                folder_name = name_elem.text
                current_path = path + [folder_name]
                
                # Update state context
                new_state = state_context
                for code in state_mapping.keys():
                    if f'{code}-ESZ' in folder_name or folder_name == code or f'ESZ-{code}' in folder_name:
                        new_state = code
                        break
                
                # Update category context
                new_category = match_category(folder_name)
                if new_category:
                    category_context = new_category
                
                # Recursively process children with updated context
                subfolder_map = build_layer_hierarchy(
                    child, 
                    current_path, 
                    new_state, 
                    category_context
                )
                layer_map.update(subfolder_map)
                
        elif child.tag.endswith('Document'):
            doc_name_elem = child.find('kml:name', ns)
            if doc_name_elem is not None:
                doc_name = doc_name_elem.text
                
                # Store the layer with its inherited context
                layer_map[doc_name] = {
                    'path': path.copy(),
                    'state': state_context,
                    'category': category_context
                }
    
    return layer_map

# Build the layer mapping with context tracking
print("Building layer hierarchy with context tracking...")
layer_to_context = build_layer_hierarchy(root)

print(f"Found {len(layer_to_context)} layer mappings\n")

# Show examples of the mapping
print("Sample layer context mappings:")
for i, (layer, info) in enumerate(list(layer_to_context.items())[:15]):
    path_str = " > ".join(info['path'][-3:]) if len(info['path']) > 3 else " > ".join(info['path'])
    state_str = info['state'] if info['state'] else '???'
    cat_str = info['category'] if info['category'] else 'Unknown'
    print(f"{layer:40s} | State: {state_str:3s} | Category: {cat_str}")

# Read all layers
print("\n" + "="*70)
print("Reading geometry layers...")
print("="*70 + "\n")

layers = fiona.listlayers(str(kml_path))
print(f"Total layers available: {len(layers)}\n")

all_gdfs = []

for layer_name in layers:
    # Skip KMZ reference layers
    if layer_name.endswith('.kmz'):
        continue
    
    # Skip pure folder layers (these don't have geometry)
    # They appear as "Error reading" in the output
    try:
        gdf = gpd.read_file(str(kml_path), driver='KML', layer=layer_name)
        
        if len(gdf) > 0:
            # Get state and category from context mapping
            layer_info = layer_to_context.get(layer_name, {})
            state_code = layer_info.get('state')
            category = layer_info.get('category')
            
            # Fallback: try to extract state from layer name
            if not state_code:
                for code in state_mapping.keys():
                    if code in layer_name:
                        state_code = code
                        break
            
            # Add metadata
            gdf['layer_name'] = layer_name
            gdf['state_code'] = state_code
            gdf['state_name'] = state_mapping.get(state_code, None) if state_code else None
            gdf['category'] = category
            gdf['folder_path'] = ' > '.join(layer_info.get('path', [])) if layer_info else None
            
            all_gdfs.append(gdf)
            
            state_info = f"({state_code})" if state_code else "(??)"
            cat_info = f"[{category}]" if category else "[Unknown]"
            print(f"✓ {len(gdf):4d} features | {state_info:6s} {cat_info:30s} | {layer_name}")
            
    except Exception as e:
        # These are folder layers - they define context but have no geometry
        print(f"✗ Error reading {layer_name}: {str(e)[:50]}...")

# Combine all GeoDataFrames
if all_gdfs:
    combined_gdf = gpd.GeoDataFrame(pd.concat(all_gdfs, ignore_index=True))
    
    print(f"\n{'='*70}")
    print(f"SUMMARY")
    print(f"{'='*70}")
    print(f"Total features: {len(combined_gdf):,}")
    print(f"Total layers: {len(all_gdfs)}")
    
    print(f"\nGeometry types:")
    print(combined_gdf.geometry.geom_type.value_counts())
    
    if 'state_code' in combined_gdf.columns and 'category' in combined_gdf.columns:
        print(f"\nFeatures by state:")
        state_counts = combined_gdf.groupby(['state_code', 'state_name']).size().sort_index()
        for (state, name), count in state_counts.items():
            if state:
                print(f"  {state} ({name}): {count:,}")
        
        print(f"\nFeatures by category:")
        cat_counts = combined_gdf['category'].value_counts().sort_index()
        for cat, count in cat_counts.items():
            print(f"  {cat if cat else 'Unknown':35s}: {count:,}")
        
        print(f"\nFeatures by state and category:")
        pivot = combined_gdf.groupby(['state_code', 'category']).size().unstack(fill_value=0)
        print(pivot)
    
    print(f"\nColumns: {combined_gdf.columns.tolist()}")
    
    print(f"\nSample data:")
    display_cols = [col for col in ['Name', 'state_code', 'category', 'layer_name', 'geometry'] 
                    if col in combined_gdf.columns]
    print(combined_gdf[display_cols].head(20))
    
    # Save to file
    output_file = notebook_dir / "esz_combined.gpkg"
    combined_gdf.to_file(output_file, driver='GPKG')
    print(f"\n✓ Saved to: {output_file}")
    print(f"  Total size: {output_file.stat().st_size / 1024 / 1024:.2f} MB")
    
else:
    print("\n⚠ No features extracted")

Building layer hierarchy with context tracking...
Found 15 layer mappings

Sample layer context mappings:
Extrusion zone_Sanctuaries.kmz           | State: MH  | Category: Sanctuary
Extrusion zone_Airport Funnel.kmz        | State: RJ  | Category: Sanctuary
Extrusion Zone_Forest boundary.kmz       | State: MH  | Category: Sanctuary
coastal.kmz                              | State: MH  | Category: Sanctuary
animal-bird.kmz                          | State: MH  | Category: Animal/Bird Migratory Path
Extrusion Zone_Protected Heritage.kmz    | State: MH  | Category: Animal/Bird Migratory Path
Extrusion zone_Resorvior.kmz             | State: MH  | Category: Animal/Bird Migratory Path
MH MOD                                   | State: MH  | Category: Sanctuary
Extrusion zone_Sanctuary.kmz             | State: RJ  | Category: Sanctuary
Extrusion zone_Forest.kmz                | State: RJ  | Category: Sanctuary
Mukundara Tiger Reserve                  | State: RJ  | Category: Animal/Bird Migratory Path
RJ-GIB Updated.kmz                       | State: RJ  | Category: Animal/Bird Migratory Path
GJ.kmz                                   | State: GJ  | Category: Unknown
MP.kmz                                   | State: MP  | Category: Unknown
ESZ-South.kmz                            | State: ??? | Category: Unknown

======================================================================
Reading geometry layers...
======================================================================

Total layers available: 267

✗ Error reading ESZ -West: Layer 'ESZ -West' could not be opened...
✓    2 features | (MH)   [Unknown]                      | MH
✗ Error reading ESZ-MH: Layer 'ESZ-MH' could not be opened...
✗ Error reading i.Sancturies: Layer 'i.Sancturies' could not be opened...
✓   31 features | (??)   [Unknown]                      | Point Features
✓   37 features | (??)   [Unknown]                      | Area Features
✓    4 features | (??)   [Unknown]                      | Line Features
✗ Error reading ii.Airport Funnel: Layer 'ii.Airport Funnel' could not be opened...
✓   93 features | (??)   [Unknown]                      | Point Features (#2)
✓   29 features | (??)   [Unknown]                      | Area Features (#2)
✓  868 features | (??)   [Unknown]                      | Line Features (#2)
✗ Error reading iii.Reserve Forest: Layer 'iii.Reserve Forest' could not be opened...
✓   70 features | (??)   [Unknown]                      | Area Features (#3)
✓    1 features | (??)   [Unknown]                      | Line Features (#3)
✗ Error reading iv.Coastal Regulatory: Layer 'iv.Coastal Regulatory' could not be opened...
✓    1 features | (??)   [Unknown]                      | Area Features (#4)
✗ Error reading v.Animal-Bird Migratory path: Layer 'v.Animal-Bird Migratory path' could not be ...
✓    1 features | (??)   [Unknown]                      | Point Features (#3)
✓    1 features | (??)   [Unknown]                      | Area Features (#5)
✗ Error reading vi.Defence Protected Area: Layer 'vi.Defence Protected Area' could not be ope...
✗ Error reading vii.Heritages: Layer 'vii.Heritages' could not be opened...
✓   34 features | (??)   [Unknown]                      | Point Features (#4)
✗ Error reading viii.Reserviors: Layer 'viii.Reserviors' could not be opened...
✓   73 features | (??)   [Unknown]                      | Point Features (#5)
✓   74 features | (??)   [Unknown]                      | Area Features (#6)
✗ Error reading ix.MOD: Layer 'ix.MOD' could not be opened...
✗ Error reading MH MOD: Layer 'MH MOD' could not be opened...
✗ Error reading MH (#2): Layer 'MH (#2)' could not be opened...
✓    1 features | (??)   [Unknown]                      | Ahmednagar
✗ Error reading Ahmednagar (#2): Layer 'Ahmednagar (#2)' could not be opened...
✓    1 features | (??)   [Unknown]                      | Ahmednagar_10NM
✗ Error reading Ahmednagar_10NM (#2): Layer 'Ahmednagar_10NM (#2)' could not be opened...
✓    1 features | (??)   [Unknown]                      | Beed
✗ Error reading Beed (#2): Layer 'Beed (#2)' could not be opened...
✓    5 features | (??)   [Unknown]                      | Identified Wind Potential Blocks
✗ Error reading Identified Wind Potential Blocks (#2): Layer 'Identified Wind Potential Blocks (#2)' coul...
✓    2 features | (??)   [Unknown]                      | puneandNDAAirfeld_20km
✗ Error reading puneandNDAAirfeld_20km (#2): Layer 'puneandNDAAirfeld_20km (#2)' could not be o...
✓    2 features | (??)   [Unknown]                      | pune_and_nda_airfield_56km_NEW
✗ Error reading pune_and_nda_airfield_56km_NEW (#2): Layer 'pune_and_nda_airfield_56km_NEW (#2)' could ...
✓    6 features | (??)   [Unknown]                      | Pune_1
✗ Error reading Pune_1 (#2): Layer 'Pune_1 (#2)' could not be opened...
✓    1 features | (??)   [Unknown]                      | Solapur
✗ Error reading Solapur (#2): Layer 'Solapur (#2)' could not be opened...
✓    1 features | (??)   [Unknown]                      | Stara
✗ Error reading Stara (#2): Layer 'Stara (#2)' could not be opened...
✗ Error reading RJ: Layer 'RJ' could not be opened...
✗ Error reading ESZ-RJ: Layer 'ESZ-RJ' could not be opened...
✗ Error reading i.Sancturies (#2): Layer 'i.Sancturies (#2)' could not be opened...
✓   21 features | (??)   [Unknown]                      | Point Features (#6)
✓   22 features | (??)   [Unknown]                      | Area Features (#7)
✓    1 features | (??)   [Unknown]                      | Line Features (#4)
✗ Error reading ii.Airport funnel (#2): Layer 'ii.Airport funnel (#2)' could not be opened...
✗ Error reading Extrusion zone_Airport Funnel.kmz (#2): Layer 'Extrusion zone_Airport Funnel.kmz (#2)' cou...
✓   10 features | (??)   [Unknown]                      | Point Features (#7)
✓   20 features | (??)   [Unknown]                      | Area Features (#8)
✓   54 features | (??)   [Unknown]                      | Line Features (#5)
✗ Error reading iii.Reserve Forest (#2): Layer 'iii.Reserve Forest (#2)' could not be opene...
✓    3 features | (??)   [Unknown]                      | Area Features (#9)
✓  100 features | (??)   [Unknown]                      | Line Features (#6)
✗ Error reading iv.Coastal Regulatory (#2): Layer 'iv.Coastal Regulatory (#2)' could not be op...
✗ Error reading v.Animal-bird Migratory Path (#2): Layer 'v.Animal-bird Migratory Path (#2)' could no...
✓    1 features | (RJ)   [Animal/Bird Migratory Path]   | Mukundara Tiger Reserve
✗ Error reading Mukundara Tiger Reserve (#2): Layer 'Mukundara Tiger Reserve (#2)' could not be ...
✓    1 features | (??)   [Unknown]                      | Area Features (#10)
✗ Error reading vi.Defence protected Area (#2): Layer 'vi.Defence protected Area (#2)' could not b...
✗ Error reading vii.Heritages (#2): Layer 'vii.Heritages (#2)' could not be opened...
✗ Error reading viii.Reservoir: Layer 'viii.Reservoir' could not be opened...
✗ Error reading GJ: Layer 'GJ' could not be opened...
✗ Error reading GJ (#2): Layer 'GJ (#2)' could not be opened...
✗ Error reading GJ-ESZ: Layer 'GJ-ESZ' could not be opened...
✗ Error reading i. Sanctuaries: Layer 'i. Sanctuaries' could not be opened...
✓   11 features | (??)   [Unknown]                      | Point Features (#8)
✓    4 features | (??)   [Unknown]                      | Area Features (#11)
✓    8 features | (??)   [Unknown]                      | Area Features (#12)
✓    7 features | (??)   [Unknown]                      | Line Features (#7)
✗ Error reading ii. Airport Funnel: Layer 'ii. Airport Funnel' could not be opened...
✓  460 features | (??)   [Unknown]                      | Line Features (#8)
✓  166 features | (??)   [Unknown]                      | Area Features (#13)
✓  402 features | (??)   [Unknown]                      | Point Features (#9)
✓   30 features | (??)   [Unknown]                      | iii. Reserve Forest
✓   32 features | (??)   [Unknown]                      | Point Features (#10)
✓  139 features | (??)   [Unknown]                      | Area Features (#14)
✓  802 features | (??)   [Unknown]                      | Line Features (#9)
✗ Error reading iv. Coastal Regulatory: Layer 'iv. Coastal Regulatory' could not be opened...
✓    1 features | (??)   [Unknown]                      | Area Features (#15)
✗ Error reading v. Animal/Bird Migratory Path: Layer 'v. Animal/Bird Migratory Path' could not be...
✓    3 features | (??)   [Unknown]                      | vi. Defence Protected Area
✓    1 features | (??)   [Unknown]                      | Area Features (#16)
✗ Error reading vii. Heritages: Layer 'vii. Heritages' could not be opened...
✓   12 features | (??)   [Unknown]                      | Point Features (#11)
✓    7 features | (??)   [Unknown]                      | Line Features (#10)
✗ Error reading viii. Reserviors: Layer 'viii. Reserviors' could not be opened...
✓   37 features | (??)   [Unknown]                      | Area Features (#17)
✓   60 features | (??)   [Unknown]                      | Point Features (#12)
✗ Error reading ix. MOD Boundaries: Layer 'ix. MOD Boundaries' could not be opened...
✗ Error reading MOD Boundaries: Layer 'MOD Boundaries' could not be opened...
✗ Error reading No wtg zone-block4: Layer 'No wtg zone-block4' could not be opened...
✓    1 features | (??)   [Unknown]                      | No wtg mod remarks-14062024
✗ Error reading shoreline25km buffer-block4: Layer 'shoreline25km buffer-block4' could not be o...
✓    1 features | (??)   [Unknown]                      | shoreline25km buffer
✓    1 features | (??)   [Unknown]                      | Amreli_1
✗ Error reading Amreli_1 (#2): Layer 'Amreli_1 (#2)' could not be opened...
✓    1 features | (??)   [Unknown]                      | Amreli_2
✗ Error reading Amreli_2 (#2): Layer 'Amreli_2 (#2)' could not be opened...
✓    6 features | (GJ)   [Unknown]                      | GJ_Blocks
✗ Error reading GJ_Blocks (#2): Layer 'GJ_Blocks (#2)' could not be opened...
✓    1 features | (??)   [Unknown]                      | IAF
✗ Error reading IAF (#2): Layer 'IAF (#2)' could not be opened...
✓    2 features | (??)   [Unknown]                      | JamANDkhamairfiled_20km
✗ Error reading JamANDkhamairfiled_20km (#2): Layer 'JamANDkhamairfiled_20km (#2)' could not be ...
✓    2 features | (??)   [Unknown]                      | Jamnagar_and_khambaliya_airfield_56km
✗ Error reading Jamnagar_and_khambaliya_airfield_56km (#2): Layer 'Jamnagar_and_khambaliya_airfield_56km (#2)'...
✓    1 features | (??)   [Unknown]                      | Jamnagar_1
✗ Error reading Jamnagar_1 (#2): Layer 'Jamnagar_1 (#2)' could not be opened...
✓    2 features | (??)   [Unknown]                      | Jamnagar_2
✗ Error reading Jamnagar_2 (#2): Layer 'Jamnagar_2 (#2)' could not be opened...
✓    1 features | (??)   [Unknown]                      | Kutch_1
✗ Error reading Kutch_1 (#2): Layer 'Kutch_1 (#2)' could not be opened...
✓    1 features | (??)   [Unknown]                      | Kutch_2
✗ Error reading Kutch_2 (#2): Layer 'Kutch_2 (#2)' could not be opened...
✓    1 features | (??)   [Unknown]                      | Kutch_6NM
✗ Error reading Kutch_6NM (#2): Layer 'Kutch_6NM (#2)' could not be opened...
✗ Error reading Naliya and Bhuj airfield_20km: Layer 'Naliya and Bhuj airfield_20km' could not be...
✓    2 features | (TG)   [Unknown]                      | No WTG Zone
✗ Error reading Naliya and Bhuj airfield_56km: Layer 'Naliya and Bhuj airfield_56km' could not be...
✓    2 features | (??)   [Unknown]                      | NOC to be obtained
✓    1 features | (??)   [Unknown]                      | Rajkot
✗ Error reading Rajkot (#2): Layer 'Rajkot (#2)' could not be opened...
✗ Error reading MP: Layer 'MP' could not be opened...
✗ Error reading MP (#2): Layer 'MP (#2)' could not be opened...
✗ Error reading MP- ESZ: Layer 'MP- ESZ' could not be opened...
✗ Error reading i. Sanctuaries (#2): Layer 'i. Sanctuaries (#2)' could not be opened...
✓   25 features | (??)   [Unknown]                      | Point Features (#13)
✓   21 features | (??)   [Unknown]                      | Area Features (#18)
✗ Error reading ii. Airport Funnel (#2): Layer 'ii. Airport Funnel (#2)' could not be opene...
✓  117 features | (??)   [Unknown]                      | Point Features (#14)
✓  230 features | (??)   [Unknown]                      | Area Features (#19)
✓  605 features | (??)   [Unknown]                      | Line Features (#11)
✗ Error reading iii. Reserve Forest (#2): Layer 'iii. Reserve Forest (#2)' could not be open...
✗ Error reading iv. Animal/Bird Migratory Path: Layer 'iv. Animal/Bird Migratory Path' could not b...
✗ Error reading v. Defence Protected Area: Layer 'v. Defence Protected Area' could not be ope...
✗ Error reading vi. Heritages: Layer 'vi. Heritages' could not be opened...
✗ Error reading vii. Reserviors: Layer 'vii. Reserviors' could not be opened...
✓   11 features | (??)   [Unknown]                      | Point Features (#15)
✓   11 features | (??)   [Unknown]                      | Area Features (#20)
✗ Error reading viii. MOD Boundaries: Layer 'viii. MOD Boundaries' could not be opened...
✗ Error reading Identified Wind Potential Blocks (#3): Layer 'Identified Wind Potential Blocks (#3)' coul...
✓    3 features | (MP)   [Unknown]                      | MP_bloacks
✗ Error reading ESZ-South: Layer 'ESZ-South' could not be opened...
✗ Error reading KA: Layer 'KA' could not be opened...
✗ Error reading KA-ESZ: Layer 'KA-ESZ' could not be opened...
✗ Error reading ii. Airport Funnel (#3): Layer 'ii. Airport Funnel (#3)' could not be opene...
✓   19 features | (KA)   [Unknown]                      | Airport Name-KA
✓ 1465 features | (KA)   [Unknown]                      | Airport Funnel-KA
✗ Error reading i. Sancturies: Layer 'i. Sancturies' could not be opened...
✓   30 features | (??)   [Unknown]                      | Santuries boundary
✓   30 features | (??)   [Unknown]                      | Santuries name
✗ Error reading iii. Reserve Forest (#3): Layer 'iii. Reserve Forest (#3)' could not be open...
✗ Error reading Reserve Forest: Layer 'Reserve Forest' could not be opened...
✓ 1308 features | (??)   [Unknown]                      | RF Boundary
✓  848 features | (??)   [Unknown]                      | RF name
✗ Error reading iv. Coastal Regulatory Zone: Layer 'iv. Coastal Regulatory Zone' could not be o...
✓   17 features | (KA)   [Unknown]                      | CRZ_KA
✗ Error reading v. Animal / Bird Migratory path: Layer 'v. Animal / Bird Migratory path' could not ...
✓    8 features | (??)   [Unknown]                      | Ex. Place name of EC
✓    2 features | (??)   [Unknown]                      | vi. Defence Protected Area (#2)
✗ Error reading vii. Heritages (#2): Layer 'vii. Heritages (#2)' could not be opened...
✗ Error reading Heritage_KA.KMZ: Layer 'Heritage_KA.KMZ' could not be opened...
✓   21 features | (KA)   [Unknown]                      | Heritage_Places, KA
✓   21 features | (??)   [Unknown]                      | Circle 01 Kms_Heritage Place
✓   29 features | (??)   [Unknown]                      | viii. Reservoirs
✗ Error reading AP: Layer 'AP' could not be opened...
✗ Error reading AP-ESZ: Layer 'AP-ESZ' could not be opened...
✗ Error reading i. Sanctuary: Layer 'i. Sanctuary' could not be opened...
✗ Error reading AP (#2): Layer 'AP (#2)' could not be opened...
✓   21 features | (??)   [Unknown]                      | Santuries boundary (#2)
✓   18 features | (??)   [Unknown]                      | Santuries name (#2)
✗ Error reading ii. Airport Funnel (#4): Layer 'ii. Airport Funnel (#4)' could not be opene...
✗ Error reading Airport_AP: Layer 'Airport_AP' could not be opened...
✓    8 features | (AP)   [Unknown]                      | Airport Name-AP
✓  544 features | (AP)   [Unknown]                      | Airport Funnel-AP
✗ Error reading iii. Reserve Forest (#4): Layer 'iii. Reserve Forest (#4)' could not be open...
✗ Error reading Reserve Forest_AP: Layer 'Reserve Forest_AP' could not be opened...
✓  187 features | (??)   [Unknown]                      | RF Boundary (#2)
✓  147 features | (??)   [Unknown]                      | RF name (#2)
✗ Error reading iv. Coastal Regulatory Zone (#2): Layer 'iv. Coastal Regulatory Zone (#2)' could not...
✓   75 features | (AP)   [Unknown]                      | CRZ_AP
✗ Error reading v. Animal / Bird Migratory path (#2): Layer 'v. Animal / Bird Migratory path (#2)' could...
✗ Error reading vi. Defence Protected Area (#3): Layer 'vi. Defence Protected Area (#3)' could not ...
✗ Error reading vii. Heritages (#3): Layer 'vii. Heritages (#3)' could not be opened...
✓   20 features | (AP)   [Unknown]                      | Heritage_Places, AP
✓   20 features | (??)   [Unknown]                      | Circle 01 Kms_Heritage Place (#2)
✗ Error reading viii. Reservoirs (#2): Layer 'viii. Reservoirs (#2)' could not be opened...
✓   46 features | (AP)   [Unknown]                      | Reservoirs_AP
✗ Error reading TN: Layer 'TN' could not be opened...
✗ Error reading TN-ESZ: Layer 'TN-ESZ' could not be opened...
✗ Error reading i. Sancturies (#2): Layer 'i. Sancturies (#2)' could not be opened...
✓   21 features | (??)   [Unknown]                      | Santuries boundary (#3)
✓   21 features | (??)   [Unknown]                      | Santuries name (#3)
✗ Error reading ii. Airport Funnel (#5): Layer 'ii. Airport Funnel (#5)' could not be opene...
✓   19 features | (TN)   [Unknown]                      | Airport name-TN&KL
✓ 1340 features | (TN)   [Unknown]                      | Airport Funnel-TN&KL
✗ Error reading iii. Reserve Forest (#5): Layer 'iii. Reserve Forest (#5)' could not be open...
✗ Error reading iv. Coastal Regulatory Zone (#3): Layer 'iv. Coastal Regulatory Zone (#3)' could not...
✓   30 features | (TN)   [Unknown]                      | TN CRZ
✗ Error reading v. Animal / Bird Migratory path (#3): Layer 'v. Animal / Bird Migratory path (#3)' could...
✗ Error reading vi. Defence Protected Area (#4): Layer 'vi. Defence Protected Area (#4)' could not ...
✗ Error reading vii. Heritages (#4): Layer 'vii. Heritages (#4)' could not be opened...
✗ Error reading TN Heritage place: Layer 'TN Heritage place' could not be opened...
✓   18 features | (??)   [Unknown]                      | Circle 01 Kms_Heritage Place (#3)
✓   18 features | (TN)   [Unknown]                      | Heritage_Places, TN
✓   21 features | (KL)   [Unknown]                      | Heritage_Places, KL
✓   21 features | (??)   [Unknown]                      | Circle 01 Kms_Heritage Place (#4)
✓   42 features | (??)   [Unknown]                      | viii. Reservoir
✗ Error reading ix.ESZ-Agri Protected Zone: Layer 'ix.ESZ-Agri Protected Zone' could not be op...
✗ Error reading ESZ-Agri Protected Zone.KMZ: Layer 'ESZ-Agri Protected Zone.KMZ' could not be o...
✓   22 features | (??)   [Unknown]                      | Point Features (#16)
✓    2 features | (??)   [Unknown]                      | Area Features (#21)
✓   21 features | (??)   [Unknown]                      | Line Features (#12)
✗ Error reading TG: Layer 'TG' could not be opened...
✗ Error reading TG-ESZ: Layer 'TG-ESZ' could not be opened...
✗ Error reading i. Sanctuary (#2): Layer 'i. Sanctuary (#2)' could not be opened...
✗ Error reading AP (#3): Layer 'AP (#3)' could not be opened...
✓   21 features | (??)   [Unknown]                      | Santuries boundary (#4)
✓   18 features | (??)   [Unknown]                      | Santuries name (#4)
✗ Error reading TG (#2): Layer 'TG (#2)' could not be opened...
✓   11 features | (??)   [Unknown]                      | Santuries boundary (#5)
✓   11 features | (??)   [Unknown]                      | Santuries name (#5)
✗ Error reading ii. Airport Funnel (#6): Layer 'ii. Airport Funnel (#6)' could not be opene...
✗ Error reading Airport_TG: Layer 'Airport_TG' could not be opened...

In [33]:
import geopandas as gpd
import pandas as pd
import xml.etree.ElementTree as ET
from pathlib import Path
import fiona

notebook_dir = Path.cwd()
extract_dir = notebook_dir / "extracted_kmz"
kml_path = extract_dir / "doc_fixed.kml"

# State mapping
state_mapping = {
    'MH': 'Maharashtra',
    'GJ': 'Gujarat', 
    'RJ': 'Rajasthan',
    'MP': 'Madhya Pradesh',
    'KA': 'Karnataka',
    'AP': 'Andhra Pradesh',
    'TG': 'Telangana',
    'TN': 'Tamil Nadu',
    'KL': 'Kerala'
}

# Category mapping (handle variations and spelling mistakes)
category_patterns = {
    'Sanctuary': ['i. Sanctuary', 'i.Sancturies', 'i. Sanctuaries', 'Sancturies', 'Sanctuary'],
    'Airport Funnel': ['ii. Airport Funnel', 'ii.Airport Funnel', 'ii.Airport funnel', 'Airport Funnel'],
    'Reserve Forest': ['iii. Reserve Forest', 'iii.Reserve Forest', 'Reserve Forest'],
    'Coastal Regulatory Zone': ['iv. Coastal Regulatory Zone', 'iv.Coastal Regulatory', 'iv. Coastal Regulatory'],
    'Animal/Bird Migratory Path': ['v. Animal / Bird Migratory path', 'v. Animal/Bird Migratory Path', 'v.Animal-Bird Migratory path', 'v.Animal-bird Migratory Path'],
    'Defence Protected Area': ['vi. Defence Protected Area', 'vi.Defence Protected Area', 'vi.Defence protected Area'],
    'Heritage': ['vii. Heritages', 'vii. Heritage', 'vii.Heritages'],
    'Reservoir': ['viii. Reservoirs', 'viii. Reservoir', 'viii.Reserviors', 'viii.Reserviors'],
    'MOD': ['ix. MOD', 'ix.MOD', 'MOD Boundaries', 'ix. MOD Boundaries'],
    'Agri Protected Zone': ['ix.ESZ-Agri Protected Zone', 'ESZ-Agri Protected Zone']
}

def match_category(layer_name):
    """Match layer name to standardized category"""
    if not layer_name:
        return None
    
    for standard_cat, patterns in category_patterns.items():
        for pattern in patterns:
            # Exact match or substring match
            if pattern in layer_name:
                return standard_cat
            
            # For patterns starting with Roman numerals, check if layer starts with exact prefix
            if pattern.startswith(('i.', 'ii.', 'iii.', 'iv.', 'v.', 'vi.', 'vii.', 'viii.', 'ix.')):
                # Extract the Roman numeral prefix (e.g., "ii.")
                prefix = pattern.split()[0]  # Get "ii." from "ii. Airport Funnel"
                
                # Check if layer_name starts with exactly this prefix
                if layer_name.startswith(prefix):
                    return standard_cat
    
    return None

def extract_state_from_name(layer_name):
    """Extract state code from layer name"""
    if not layer_name:
        return None
    
    for code in state_mapping.keys():
        # Check for exact state code match or state in various formats
        if (f'{code}-ESZ' in layer_name or 
            f'ESZ-{code}' in layer_name or 
            layer_name == code or
            layer_name.startswith(f'{code} ') or
            f' {code} ' in layer_name or
            layer_name.endswith(f' {code}') or
            f', {code}' in layer_name):
            return code
    return None

# Read all layers
print("="*70)
print("Reading geometry layers with context tracking...")
print("="*70 + "\n")

layers = fiona.listlayers(str(kml_path))
print(f"Total layers available: {len(layers)}\n")

# Track current context
current_state = None
current_category = None
context_stack = []  # Track folder hierarchy

all_gdfs = []

for layer_name in layers:
    # Skip KMZ reference layers
    if layer_name.endswith('.kmz'):
        continue
    
    # Try to read the layer
    try:
        gdf = gpd.read_file(str(kml_path), driver='KML', layer=layer_name)
        
        if len(gdf) > 0:
            # This is a real geometry layer
            # Use the current context (state and category from previous error layers)
            
            # Also check if layer name itself contains state/category info
            layer_state = extract_state_from_name(layer_name)
            layer_category = match_category(layer_name)
            
            # Prefer layer-specific info, fallback to context
            final_state = layer_state if layer_state else current_state
            final_category = layer_category if layer_category else current_category
            
            # Add metadata
            gdf['layer_name'] = layer_name
            gdf['state_code'] = final_state
            gdf['state_name'] = state_mapping.get(final_state, None) if final_state else None
            gdf['category'] = final_category
            gdf['context_path'] = ' > '.join(context_stack) if context_stack else None
            
            all_gdfs.append(gdf)
            
            state_info = f"({final_state})" if final_state else "(??)"
            cat_info = f"[{final_category}]" if final_category else "[Unknown]"
            context_info = f" | Context: {' > '.join(context_stack[-2:])}" if len(context_stack) > 0 else ""
            print(f"✓ {len(gdf):4d} features | {state_info:6s} {cat_info:30s} | {layer_name}{context_info}")
            
    except Exception as e:
        # This is a folder layer - update context
        
        # Check if this folder defines a new state
        folder_state = extract_state_from_name(layer_name)
        
        # Check if this folder defines a new category
        folder_category = match_category(layer_name)
        
        # Only print and update if we found something
        if folder_state or folder_category:
            print(f"✗ Folder layer: {layer_name}")
            
            if folder_state:
                current_state = folder_state
                # Replace old state in context stack
                context_stack = [c for c in context_stack if not c.startswith('State:')]
                context_stack.append(f"State:{folder_state}")
                print(f"  → Updated state context: {current_state}")
            
            if folder_category:
                current_category = folder_category
                # Replace old category in context stack
                context_stack = [c for c in context_stack if not c.startswith('Category:')]
                context_stack.append(f"Category:{folder_category}")
                print(f"  → Updated category context: {current_category}")
            
            print()

# Combine all GeoDataFrames
if all_gdfs:
    combined_gdf = gpd.GeoDataFrame(pd.concat(all_gdfs, ignore_index=True))
    
    print(f"\n{'='*70}")
    print(f"SUMMARY")
    print(f"{'='*70}")
    print(f"Total features: {len(combined_gdf):,}")
    print(f"Total layers: {len(all_gdfs)}")
    
    print(f"\nGeometry types:")
    print(combined_gdf.geometry.geom_type.value_counts())
    
    if 'state_code' in combined_gdf.columns and 'category' in combined_gdf.columns:
        print(f"\nFeatures by state:")
        state_counts = combined_gdf.groupby(['state_code', 'state_name']).size().sort_index()
        for (state, name), count in state_counts.items():
            if state and name:
                print(f"  {state} ({name}): {count:,}")
            elif state:
                print(f"  {state}: {count:,}")
            else:
                print(f"  Unknown: {count:,}")
        
        print(f"\nFeatures by category:")
        cat_counts = combined_gdf['category'].value_counts().sort_index()
        for cat, count in cat_counts.items():
            print(f"  {cat if cat else 'Unknown':35s}: {count:,}")
        
        print(f"\nFeatures by state and category:")
        try:
            pivot = combined_gdf.groupby(['state_code', 'category']).size().unstack(fill_value=0)
            print(pivot)
        except:
            print("  (Unable to create pivot table)")
    
    print(f"\nColumns: {combined_gdf.columns.tolist()}")
    
    print(f"\nSample data:")
    display_cols = [col for col in ['Name', 'state_code', 'category', 'layer_name', 'geometry'] 
                    if col in combined_gdf.columns]
    print(combined_gdf[display_cols].head(20))
    
    # Save to file
    output_file = notebook_dir / "esz_combined.gpkg"
    combined_gdf.to_file(output_file, driver='GPKG')
    print(f"\n✓ Saved to: {output_file}")
    print(f"  Total size: {output_file.stat().st_size / 1024 / 1024:.2f} MB")
    
else:
    print("\n⚠ No features extracted")

======================================================================
Reading geometry layers with context tracking...
======================================================================

Total layers available: 267

✓    2 features | (MH)   [Unknown]                      | MH
✗ Folder layer: ESZ-MH
  → Updated state context: MH

✗ Folder layer: i.Sancturies
  → Updated category context: Sanctuary

✓   31 features | (MH)   [Sanctuary]                    | Point Features | Context: State:MH > Category:Sanctuary
✓   37 features | (MH)   [Sanctuary]                    | Area Features | Context: State:MH > Category:Sanctuary
✓    4 features | (MH)   [Sanctuary]                    | Line Features | Context: State:MH > Category:Sanctuary
✗ Folder layer: ii.Airport Funnel
  → Updated category context: Airport Funnel

✓   93 features | (MH)   [Airport Funnel]               | Point Features (#2) | Context: State:MH > Category:Airport Funnel
✓   29 features | (MH)   [Airport Funnel]               | Area Features (#2) | Context: State:MH > Category:Airport Funnel
✓  868 features | (MH)   [Airport Funnel]               | Line Features (#2) | Context: State:MH > Category:Airport Funnel
✗ Folder layer: iii.Reserve Forest
  → Updated category context: Reserve Forest

✓   70 features | (MH)   [Reserve Forest]               | Area Features (#3) | Context: State:MH > Category:Reserve Forest
✓    1 features | (MH)   [Reserve Forest]               | Line Features (#3) | Context: State:MH > Category:Reserve Forest
✗ Folder layer: iv.Coastal Regulatory
  → Updated category context: Coastal Regulatory Zone

✓    1 features | (MH)   [Coastal Regulatory Zone]      | Area Features (#4) | Context: State:MH > Category:Coastal Regulatory Zone
✗ Folder layer: v.Animal-Bird Migratory path
  → Updated category context: Animal/Bird Migratory Path

✓    1 features | (MH)   [Animal/Bird Migratory Path]   | Point Features (#3) | Context: State:MH > Category:Animal/Bird Migratory Path
✓    1 features | (MH)   [Animal/Bird Migratory Path]   | Area Features (#5) | Context: State:MH > Category:Animal/Bird Migratory Path
✗ Folder layer: vi.Defence Protected Area
  → Updated category context: Defence Protected Area

✗ Folder layer: vii.Heritages
  → Updated category context: Heritage

✓   34 features | (MH)   [Heritage]                     | Point Features (#4) | Context: State:MH > Category:Heritage
✗ Folder layer: viii.Reserviors
  → Updated category context: Reservoir

✓   73 features | (MH)   [Reservoir]                    | Point Features (#5) | Context: State:MH > Category:Reservoir
✓   74 features | (MH)   [Reservoir]                    | Area Features (#6) | Context: State:MH > Category:Reservoir
✗ Folder layer: ix.MOD
  → Updated category context: MOD

✗ Folder layer: MH MOD
  → Updated state context: MH

✗ Folder layer: MH (#2)
  → Updated state context: MH

✓    1 features | (MH)   [MOD]                          | Ahmednagar | Context: Category:MOD > State:MH
✓    1 features | (MH)   [MOD]                          | Ahmednagar_10NM | Context: Category:MOD > State:MH
✓    1 features | (MH)   [MOD]                          | Beed | Context: Category:MOD > State:MH
✓    5 features | (MH)   [MOD]                          | Identified Wind Potential Blocks | Context: Category:MOD > State:MH
✓    2 features | (MH)   [MOD]                          | puneandNDAAirfeld_20km | Context: Category:MOD > State:MH
✓    2 features | (MH)   [MOD]                          | pune_and_nda_airfield_56km_NEW | Context: Category:MOD > State:MH
✓    6 features | (MH)   [MOD]                          | Pune_1 | Context: Category:MOD > State:MH
✓    1 features | (MH)   [MOD]                          | Solapur | Context: Category:MOD > State:MH
✓    1 features | (MH)   [MOD]                          | Stara | Context: Category:MOD > State:MH
✗ Folder layer: RJ
  → Updated state context: RJ

✗ Folder layer: ESZ-RJ
  → Updated state context: RJ

✗ Folder layer: i.Sancturies (#2)
  → Updated category context: Sanctuary

✓   21 features | (RJ)   [Sanctuary]                    | Point Features (#6) | Context: State:RJ > Category:Sanctuary
✓   22 features | (RJ)   [Sanctuary]                    | Area Features (#7) | Context: State:RJ > Category:Sanctuary
✓    1 features | (RJ)   [Sanctuary]                    | Line Features (#4) | Context: State:RJ > Category:Sanctuary
✗ Folder layer: ii.Airport funnel (#2)
  → Updated category context: Airport Funnel

✗ Folder layer: Extrusion zone_Airport Funnel.kmz (#2)
  → Updated category context: Airport Funnel

✓   10 features | (RJ)   [Airport Funnel]               | Point Features (#7) | Context: State:RJ > Category:Airport Funnel
✓   20 features | (RJ)   [Airport Funnel]               | Area Features (#8) | Context: State:RJ > Category:Airport Funnel
✓   54 features | (RJ)   [Airport Funnel]               | Line Features (#5) | Context: State:RJ > Category:Airport Funnel
✗ Folder layer: iii.Reserve Forest (#2)
  → Updated category context: Reserve Forest

✓    3 features | (RJ)   [Reserve Forest]               | Area Features (#9) | Context: State:RJ > Category:Reserve Forest
✓  100 features | (RJ)   [Reserve Forest]               | Line Features (#6) | Context: State:RJ > Category:Reserve Forest
✗ Folder layer: iv.Coastal Regulatory (#2)
  → Updated category context: Coastal Regulatory Zone

✗ Folder layer: v.Animal-bird Migratory Path (#2)
  → Updated category context: Animal/Bird Migratory Path

✓    1 features | (RJ)   [Animal/Bird Migratory Path]   | Mukundara Tiger Reserve | Context: State:RJ > Category:Animal/Bird Migratory Path
✓    1 features | (RJ)   [Animal/Bird Migratory Path]   | Area Features (#10) | Context: State:RJ > Category:Animal/Bird Migratory Path
✗ Folder layer: vi.Defence protected Area (#2)
  → Updated category context: Defence Protected Area

✗ Folder layer: vii.Heritages (#2)
  → Updated category context: Heritage

✗ Folder layer: viii.Reservoir
  → Updated category context: Reservoir

✗ Folder layer: GJ
  → Updated state context: GJ

✗ Folder layer: GJ (#2)
  → Updated state context: GJ

✗ Folder layer: GJ-ESZ
  → Updated state context: GJ

✗ Folder layer: i. Sanctuaries
  → Updated category context: Sanctuary

✓   11 features | (GJ)   [Sanctuary]                    | Point Features (#8) | Context: State:GJ > Category:Sanctuary
✓    4 features | (GJ)   [Sanctuary]                    | Area Features (#11) | Context: State:GJ > Category:Sanctuary
✓    8 features | (GJ)   [Sanctuary]                    | Area Features (#12) | Context: State:GJ > Category:Sanctuary
✓    7 features | (GJ)   [Sanctuary]                    | Line Features (#7) | Context: State:GJ > Category:Sanctuary
✗ Folder layer: ii. Airport Funnel
  → Updated category context: Airport Funnel

✓  460 features | (GJ)   [Airport Funnel]               | Line Features (#8) | Context: State:GJ > Category:Airport Funnel
✓  166 features | (GJ)   [Airport Funnel]               | Area Features (#13) | Context: State:GJ > Category:Airport Funnel
✓  402 features | (GJ)   [Airport Funnel]               | Point Features (#9) | Context: State:GJ > Category:Airport Funnel
✓   30 features | (GJ)   [Reserve Forest]               | iii. Reserve Forest | Context: State:GJ > Category:Airport Funnel
✓   32 features | (GJ)   [Airport Funnel]               | Point Features (#10) | Context: State:GJ > Category:Airport Funnel
✓  139 features | (GJ)   [Airport Funnel]               | Area Features (#14) | Context: State:GJ > Category:Airport Funnel
✓  802 features | (GJ)   [Airport Funnel]               | Line Features (#9) | Context: State:GJ > Category:Airport Funnel
✗ Folder layer: iv. Coastal Regulatory
  → Updated category context: Coastal Regulatory Zone

✓    1 features | (GJ)   [Coastal Regulatory Zone]      | Area Features (#15) | Context: State:GJ > Category:Coastal Regulatory Zone
✗ Folder layer: v. Animal/Bird Migratory Path
  → Updated category context: Animal/Bird Migratory Path

✓    3 features | (GJ)   [Defence Protected Area]       | vi. Defence Protected Area | Context: State:GJ > Category:Animal/Bird Migratory Path
✓    1 features | (GJ)   [Animal/Bird Migratory Path]   | Area Features (#16) | Context: State:GJ > Category:Animal/Bird Migratory Path
✗ Folder layer: vii. Heritages
  → Updated category context: Heritage

✓   12 features | (GJ)   [Heritage]                     | Point Features (#11) | Context: State:GJ > Category:Heritage
✓    7 features | (GJ)   [Heritage]                     | Line Features (#10) | Context: State:GJ > Category:Heritage
✗ Folder layer: viii. Reserviors
  → Updated category context: Reservoir

✓   37 features | (GJ)   [Reservoir]                    | Area Features (#17) | Context: State:GJ > Category:Reservoir
✓   60 features | (GJ)   [Reservoir]                    | Point Features (#12) | Context: State:GJ > Category:Reservoir
✗ Folder layer: ix. MOD Boundaries
  → Updated category context: MOD

✗ Folder layer: MOD Boundaries
  → Updated category context: MOD

✓    1 features | (GJ)   [MOD]                          | No wtg mod remarks-14062024 | Context: State:GJ > Category:MOD
✓    1 features | (GJ)   [MOD]                          | shoreline25km buffer | Context: State:GJ > Category:MOD
✓    1 features | (GJ)   [MOD]                          | Amreli_1 | Context: State:GJ > Category:MOD
✓    1 features | (GJ)   [MOD]                          | Amreli_2 | Context: State:GJ > Category:MOD
✓    6 features | (GJ)   [MOD]                          | GJ_Blocks | Context: State:GJ > Category:MOD
✓    1 features | (GJ)   [MOD]                          | IAF | Context: State:GJ > Category:MOD
✓    2 features | (GJ)   [MOD]                          | JamANDkhamairfiled_20km | Context: State:GJ > Category:MOD
✓    2 features | (GJ)   [MOD]                          | Jamnagar_and_khambaliya_airfield_56km | Context: State:GJ > Category:MOD
✓    1 features | (GJ)   [MOD]                          | Jamnagar_1 | Context: State:GJ > Category:MOD
✓    2 features | (GJ)   [MOD]                          | Jamnagar_2 | Context: State:GJ > Category:MOD
✓    1 features | (GJ)   [MOD]                          | Kutch_1 | Context: State:GJ > Category:MOD
✓    1 features | (GJ)   [MOD]                          | Kutch_2 | Context: State:GJ > Category:MOD
✓    1 features | (GJ)   [MOD]                          | Kutch_6NM | Context: State:GJ > Category:MOD
✓    2 features | (GJ)   [MOD]                          | No WTG Zone | Context: State:GJ > Category:MOD
✓    2 features | (GJ)   [MOD]                          | NOC to be obtained | Context: State:GJ > Category:MOD
✓    1 features | (GJ)   [MOD]                          | Rajkot | Context: State:GJ > Category:MOD
✗ Folder layer: MP
  → Updated state context: MP

✗ Folder layer: MP (#2)
  → Updated state context: MP

✗ Folder layer: i. Sanctuaries (#2)
  → Updated category context: Sanctuary

✓   25 features | (MP)   [Sanctuary]                    | Point Features (#13) | Context: State:MP > Category:Sanctuary
✓   21 features | (MP)   [Sanctuary]                    | Area Features (#18) | Context: State:MP > Category:Sanctuary
✗ Folder layer: ii. Airport Funnel (#2)
  → Updated category context: Airport Funnel

✓  117 features | (MP)   [Airport Funnel]               | Point Features (#14) | Context: State:MP > Category:Airport Funnel
✓  230 features | (MP)   [Airport Funnel]               | Area Features (#19) | Context: State:MP > Category:Airport Funnel
✓  605 features | (MP)   [Airport Funnel]               | Line Features (#11) | Context: State:MP > Category:Airport Funnel
✗ Folder layer: iii. Reserve Forest (#2)
  → Updated category context: Reserve Forest

✗ Folder layer: iv. Animal/Bird Migratory Path
  → Updated category context: Coastal Regulatory Zone

✗ Folder layer: v. Defence Protected Area
  → Updated category context: Animal/Bird Migratory Path

✗ Folder layer: vi. Heritages
  → Updated category context: Defence Protected Area

✗ Folder layer: vii. Reserviors
  → Updated category context: Heritage

✓   11 features | (MP)   [Heritage]                     | Point Features (#15) | Context: State:MP > Category:Heritage
✓   11 features | (MP)   [Heritage]                     | Area Features (#20) | Context: State:MP > Category:Heritage
✗ Folder layer: viii. MOD Boundaries
  → Updated category context: Reservoir

✓    3 features | (MP)   [Reservoir]                    | MP_bloacks | Context: State:MP > Category:Reservoir
✗ Folder layer: KA
  → Updated state context: KA

✗ Folder layer: KA-ESZ
  → Updated state context: KA

✗ Folder layer: ii. Airport Funnel (#3)
  → Updated category context: Airport Funnel

✓   19 features | (KA)   [Airport Funnel]               | Airport Name-KA | Context: State:KA > Category:Airport Funnel
✓ 1465 features | (KA)   [Airport Funnel]               | Airport Funnel-KA | Context: State:KA > Category:Airport Funnel
✗ Folder layer: i. Sancturies
  → Updated category context: Sanctuary

✓   30 features | (KA)   [Sanctuary]                    | Santuries boundary | Context: State:KA > Category:Sanctuary
✓   30 features | (KA)   [Sanctuary]                    | Santuries name | Context: State:KA > Category:Sanctuary
✗ Folder layer: iii. Reserve Forest (#3)
  → Updated category context: Reserve Forest

✗ Folder layer: Reserve Forest
  → Updated category context: Reserve Forest

✓ 1308 features | (KA)   [Reserve Forest]               | RF Boundary | Context: State:KA > Category:Reserve Forest
✓  848 features | (KA)   [Reserve Forest]               | RF name | Context: State:KA > Category:Reserve Forest
✗ Folder layer: iv. Coastal Regulatory Zone
  → Updated category context: Coastal Regulatory Zone

✓   17 features | (KA)   [Coastal Regulatory Zone]      | CRZ_KA | Context: State:KA > Category:Coastal Regulatory Zone
✗ Folder layer: v. Animal / Bird Migratory path
  → Updated category context: Animal/Bird Migratory Path

✓    8 features | (KA)   [Animal/Bird Migratory Path]   | Ex. Place name of EC | Context: State:KA > Category:Animal/Bird Migratory Path
✓    2 features | (KA)   [Defence Protected Area]       | vi. Defence Protected Area (#2) | Context: State:KA > Category:Animal/Bird Migratory Path
✗ Folder layer: vii. Heritages (#2)
  → Updated category context: Heritage

✓   21 features | (KA)   [Heritage]                     | Heritage_Places, KA | Context: State:KA > Category:Heritage
✓   21 features | (KA)   [Heritage]                     | Circle 01 Kms_Heritage Place | Context: State:KA > Category:Heritage
✓   29 features | (KA)   [Reservoir]                    | viii. Reservoirs | Context: State:KA > Category:Heritage
✗ Folder layer: AP
  → Updated state context: AP

✗ Folder layer: AP-ESZ
  → Updated state context: AP

✗ Folder layer: i. Sanctuary
  → Updated category context: Sanctuary

✗ Folder layer: AP (#2)
  → Updated state context: AP

✓   21 features | (AP)   [Sanctuary]                    | Santuries boundary (#2) | Context: Category:Sanctuary > State:AP
✓   18 features | (AP)   [Sanctuary]                    | Santuries name (#2) | Context: Category:Sanctuary > State:AP
✗ Folder layer: ii. Airport Funnel (#4)
  → Updated category context: Airport Funnel

✓    8 features | (AP)   [Airport Funnel]               | Airport Name-AP | Context: State:AP > Category:Airport Funnel
✓  544 features | (AP)   [Airport Funnel]               | Airport Funnel-AP | Context: State:AP > Category:Airport Funnel
✗ Folder layer: iii. Reserve Forest (#4)
  → Updated category context: Reserve Forest

✗ Folder layer: Reserve Forest_AP
  → Updated category context: Reserve Forest

✓  187 features | (AP)   [Reserve Forest]               | RF Boundary (#2) | Context: State:AP > Category:Reserve Forest
✓  147 features | (AP)   [Reserve Forest]               | RF name (#2) | Context: State:AP > Category:Reserve Forest
✗ Folder layer: iv. Coastal Regulatory Zone (#2)
  → Updated category context: Coastal Regulatory Zone

✓   75 features | (AP)   [Coastal Regulatory Zone]      | CRZ_AP | Context: State:AP > Category:Coastal Regulatory Zone
✗ Folder layer: v. Animal / Bird Migratory path (#2)
  → Updated category context: Animal/Bird Migratory Path

✗ Folder layer: vi. Defence Protected Area (#3)
  → Updated category context: Defence Protected Area

✗ Folder layer: vii. Heritages (#3)
  → Updated category context: Heritage

✓   20 features | (AP)   [Heritage]                     | Heritage_Places, AP | Context: State:AP > Category:Heritage
✓   20 features | (AP)   [Heritage]                     | Circle 01 Kms_Heritage Place (#2) | Context: State:AP > Category:Heritage
✗ Folder layer: viii. Reservoirs (#2)
  → Updated category context: Reservoir

✓   46 features | (AP)   [Reservoir]                    | Reservoirs_AP | Context: State:AP > Category:Reservoir
✗ Folder layer: TN
  → Updated state context: TN

✗ Folder layer: TN-ESZ
  → Updated state context: TN

✗ Folder layer: i. Sancturies (#2)
  → Updated category context: Sanctuary

✓   21 features | (TN)   [Sanctuary]                    | Santuries boundary (#3) | Context: State:TN > Category:Sanctuary
✓   21 features | (TN)   [Sanctuary]                    | Santuries name (#3) | Context: State:TN > Category:Sanctuary
✗ Folder layer: ii. Airport Funnel (#5)
  → Updated category context: Airport Funnel

✓   19 features | (TN)   [Airport Funnel]               | Airport name-TN&KL | Context: State:TN > Category:Airport Funnel
✓ 1340 features | (TN)   [Airport Funnel]               | Airport Funnel-TN&KL | Context: State:TN > Category:Airport Funnel
✗ Folder layer: iii. Reserve Forest (#5)
  → Updated category context: Reserve Forest

✗ Folder layer: iv. Coastal Regulatory Zone (#3)
  → Updated category context: Coastal Regulatory Zone

✓   30 features | (TN)   [Coastal Regulatory Zone]      | TN CRZ | Context: State:TN > Category:Coastal Regulatory Zone
✗ Folder layer: v. Animal / Bird Migratory path (#3)
  → Updated category context: Animal/Bird Migratory Path

✗ Folder layer: vi. Defence Protected Area (#4)
  → Updated category context: Defence Protected Area

✗ Folder layer: vii. Heritages (#4)
  → Updated category context: Heritage

✗ Folder layer: TN Heritage place
  → Updated state context: TN

✓   18 features | (TN)   [Heritage]                     | Circle 01 Kms_Heritage Place (#3) | Context: Category:Heritage > State:TN
✓   18 features | (TN)   [Heritage]                     | Heritage_Places, TN | Context: Category:Heritage > State:TN
✓   21 features | (KL)   [Heritage]                     | Heritage_Places, KL | Context: Category:Heritage > State:TN
✓   21 features | (TN)   [Heritage]                     | Circle 01 Kms_Heritage Place (#4) | Context: Category:Heritage > State:TN
✓   42 features | (TN)   [Reservoir]                    | viii. Reservoir | Context: Category:Heritage > State:TN
✗ Folder layer: ix.ESZ-Agri Protected Zone
  → Updated category context: MOD

✗ Folder layer: ESZ-Agri Protected Zone.KMZ
  → Updated category context: Agri Protected Zone

✓   22 features | (TN)   [Agri Protected Zone]          | Point Features (#16) | Context: State:TN > Category:Agri Protected Zone
✓    2 features | (TN)   [Agri Protected Zone]          | Area Features (#21) | Context: State:TN > Category:Agri Protected Zone
✓   21 features | (TN)   [Agri Protected Zone]          | Line Features (#12) | Context: State:TN > Category:Agri Protected Zone
✗ Folder layer: TG
  → Updated state context: TG

✗ Folder layer: TG-ESZ
  → Updated state context: TG

✗ Folder layer: i. Sanctuary (#2)
  → Updated category context: Sanctuary

✗ Folder layer: AP (#3)
  → Updated state context: AP

✓   21 features | (AP)   [Sanctuary]                    | Santuries boundary (#4) | Context: Category:Sanctuary > State:AP
✓   18 features | (AP)   [Sanctuary]                    | Santuries name (#4) | Context: Category:Sanctuary > State:AP
✗ Folder layer: TG (#2)
  → Updated state context: TG


In [2]:
import geopandas as gpd
import folium
from pathlib import Path

# Read the combined ESZ data
notebook_dir = Path.cwd()
gpkg_file = notebook_dir / "esz_combined.gpkg"  # Goes up one level to parent dir

print(f"Loading ESZ data from: {gpkg_file}")
gdf = gpd.read_file(gpkg_file)

Loading ESZ data from: d:\OneDrive - Suzlon Energy Ltd\Documents\Deployment\Map Analytics\test_notebooks\esz_combined.gpkg

In [3]:
gdf

,Name,Description,layer_name,state_code,state_name,category,context_path,geometry
0,Block A,,MH,MH,Maharashtra,None,None,"POLYGON Z ((75.49 18.57002 0, 75.55 18.57002 0..."
1,Block B,,MH,MH,Maharashtra,None,None,"POLYGON Z ((75.24 18.86002 0, 75.25002 18.8300..."
2,FEATURE,EXTRUSION_ZONE_SANCTUARIES,Point Features,MH,Maharashtra,Sanctuary,State:MH > Category:Sanctuary,POINT Z (72.9908 18.99128 0)
3,FEATURE,EXTRUSION_ZONE_SANCTUARIES,Point Features,MH,Maharashtra,Sanctuary,State:MH > Category:Sanctuary,POINT Z (75.07968 18.20872 0)
4,FEATURE,EXTRUSION_ZONE_SANCTUARIES,Point Features,MH,Maharashtra,Sanctuary,State:MH > Category:Sanctuary,POINT Z (73.87456 16.55496 0)
...,...,...,...,...,...,...,...,...
13056,KRISHNAPURAM PROJECT,LAND_COVER_AP_STATE_RESERV<BR><BR><B>ELEVATION...,Reservoirs_AP (#2),TG,Telangana,Reservoir,State:TG > Category:Reservoir,"POLYGON Z ((79.35686 13.37143 0, 79.35676 13.3..."
13057,GAJULADINNE PROJECT,LAND_COVER_AP_STATE_RESERV<BR><BR><B>ELEVATION...,Reservoirs_AP (#2),TG,Telangana,Reservoir,State:TG > Category:Reservoir,"POLYGON Z ((77.61475 15.70563 0, 77.61249 15.7..."
13058,BUGGAVAGU DAM,LAND_COVER_AP_STATE_RESERV<BR><BR><B>ELEVATION...,Reservoirs_AP (#2),TG,Telangana,Reservoir,State:TG > Category:Reservoir,"POLYGON Z ((79.52556 16.45638 0, 79.52859 16.4..."
13059,VARADARAJASWAMY GUDI PROJECT,LAND_COVER_AP_STATE_RESERV<BR><BR><B>ELEVATION...,Reservoirs_AP (#2),TG,Telangana,Reservoir,State:TG > Category:Reservoir,"POLYGON Z ((78.6467 15.96629 0, 78.647 15.9664..."
13060,ZURRERU RESERVOIR Med,LAND_COVER_AP_STATE_RESERV<BR><BR><B>ELEVATION...,Reservoirs_AP (#2),TG,Telangana,Reservoir,State:TG > Category:Reservoir,"POLYGON Z ((78.13906 15.30883 0, 78.13919 15.3..."

In [4]:
# Filter for Reserve Forests only
reserve_forests = gdf[gdf['category'] == 'Reserve Forest'].copy()

# Remove Point features - keep Polygon, MultiPolygon, LineString, and MultiLineString
#reserve_forests = reserve_forests[reserve_forests.geometry.geom_type.isin(['Polygon', 'MultiPolygon', 'LineString', 'MultiLineString'])].copy()

print(f"\nTotal features in combined file: {len(gdf):,}")
print(f"Reserve Forest features (no points): {len(reserve_forests):,}")

# Print summary by state
print("\nReserve Forests by state:")
state_counts = reserve_forests['state_code'].value_counts()
for state, count in state_counts.items():
    state_name = reserve_forests[reserve_forests['state_code'] == state]['state_name'].iloc[0]
    print(f"  {state} ({state_name}): {count:,}")

Total features in combined file: 13,061
Reserve Forest features (no points): 3,092

Reserve Forests by state:
  KA (Karnataka): 2,156
  TG (Telangana): 398
  AP (Andhra Pradesh): 334
  RJ (Rajasthan): 103
  MH (Maharashtra): 71
  GJ (Gujarat): 30

In [5]:
reserve_forests.head()

,Name,Description,layer_name,state_code,state_name,category,context_path,geometry
1064,,EXTRUSION_ZONE_FOREST_BOUN,Area Features (#3),MH,Maharashtra,Reserve Forest,State:MH > Category:Reserve Forest,"POLYGON Z ((74.63723 17.69335 0, 74.6372 17.69..."
1065,,EXTRUSION_ZONE_FOREST_BOUN,Area Features (#3),MH,Maharashtra,Reserve Forest,State:MH > Category:Reserve Forest,"POLYGON Z ((74.66792 17.69657 0, 74.66766 17.6..."
1066,,EXTRUSION_ZONE_FOREST_BOUN,Area Features (#3),MH,Maharashtra,Reserve Forest,State:MH > Category:Reserve Forest,"POLYGON Z ((74.59216 17.94806 0, 74.59006 17.9..."
1067,,EXTRUSION_ZONE_FOREST_BOUN,Area Features (#3),MH,Maharashtra,Reserve Forest,State:MH > Category:Reserve Forest,"POLYGON Z ((74.60484 17.95083 0, 74.60404 17.9..."
1068,,EXTRUSION_ZONE_FOREST_BOUN,Area Features (#3),MH,Maharashtra,Reserve Forest,State:MH > Category:Reserve Forest,"POLYGON Z ((74.6131 17.94873 0, 74.61387 17.94..."

In [ ]:
from shapely.geometry import LineString, MultiLineString, Polygon, MultiPolygon, GeometryCollection
from shapely.ops import unary_union, polygonize_full, snap
from shapely import make_valid
from shapely.errors import GEOSException
import pandas as pd

def _flatten_lines(geom):
    """Return individual LineStrings from any line-like geometry."""
    if geom is None or geom.is_empty:
        return []

    if isinstance(geom, LineString):
        return [geom]
    if isinstance(geom, MultiLineString):
        return [g for g in geom.geoms if not g.is_empty]
    if isinstance(geom, GeometryCollection):
        out = []
        for g in geom.geoms:
            out.extend(_flatten_lines(g))
        return out
    return []

def _flatten_polygons(geom):
    """Return individual Polygons from polygon-like geometry."""
    if geom is None or geom.is_empty:
        return []

    if isinstance(geom, Polygon):
        return [geom]
    if isinstance(geom, MultiPolygon):
        return [g for g in geom.geoms if not g.is_empty]
    if isinstance(geom, GeometryCollection):
        out = []
        for g in geom.geoms:
            out.extend(_flatten_polygons(g))
        return out
    return []

def _safe_make_valid(geom):
    if geom is None or geom.is_empty:
        return geom
    try:
        return make_valid(geom)
    except Exception:
        try:
            return geom.buffer(0)
        except Exception:
            return geom

def _safe_intersection_area(a, b):
    try:
        return a.intersection(b).area
    except GEOSException:
        try:
            return _safe_make_valid(a).intersection(_safe_make_valid(b)).area
        except Exception:
            try:
                return a.buffer(0).intersection(b.buffer(0)).area
            except Exception:
                return 0.0

def _safe_intersects(a, b):
    try:
        return a.intersects(b)
    except GEOSException:
        return _safe_intersection_area(a, b) > 0

def _build_full_polygons(lines, snap_tolerance_m, min_area_m2):
    """Polygonize from line network, returning polygons and leftover linework."""
    if not lines:
        return [], [], {"network_lines": 0, "polygonized": 0, "leftover": 0}

    merged = unary_union(lines)
    noded = snap(merged, merged, snap_tolerance_m) if snap_tolerance_m > 0 else merged

    polys_gc, dangles_gc, cuts_gc, invalid_gc = polygonize_full(noded)

    poly_geoms = [
        p for p in getattr(polys_gc, "geoms", [])
        if (not p.is_empty) and p.is_valid and p.area >= min_area_m2
    ]

    leftover_geoms = []
    for gc in (dangles_gc, cuts_gc, invalid_gc):
        for g in getattr(gc, "geoms", []):
            leftover_geoms.extend(_flatten_lines(g))

    stats = {
        "network_lines": len(lines),
        "polygonized": len(poly_geoms),
        "leftover": len(leftover_geoms),
    }
    return poly_geoms, leftover_geoms, stats

def convert_lines_and_fuse_with_polygons(
    gdf_input,
    snap_tolerance_m=8.0,
    min_area_m2=25.0,
    dedupe_overlap_ratio=0.98,
    area_growth_ratio=1.05,
):
    """
    Stage 1: Build polygons from line-only network and keep unused tails.
    Stage 2: Build additional polygons from (leftover lines + existing polygon boundaries),
    so lines that close rings with polygon edges can form larger polygons.
    """
    if gdf_input.crs is None:
        raise ValueError("Input GeoDataFrame must have CRS.")

    projected_crs = gdf_input.estimate_utm_crs()
    work = gdf_input.to_crs(projected_crs).copy()

    line_mask = work.geometry.geom_type.isin(["LineString", "MultiLineString"])
    poly_mask = work.geometry.geom_type.isin(["Polygon", "MultiPolygon"])

    gdf_lines = work[line_mask].copy()
    gdf_polys_existing = work[poly_mask].copy()
    gdf_non_line_non_poly = work[~line_mask & ~poly_mask].copy()

    input_lines = []
    for geom in gdf_lines.geometry:
        input_lines.extend(_flatten_lines(geom))

    # Stage 1: line-only polygonization
    stage1_polys, stage1_leftovers, _ = _build_full_polygons(
        lines=input_lines,
        snap_tolerance_m=snap_tolerance_m,
        min_area_m2=min_area_m2,
    )

    # Stage 2: fuse leftover lines with polygon boundaries
    poly_boundaries = []
    for geom in gdf_polys_existing.geometry:
        valid_geom = _safe_make_valid(geom)
        for p in _flatten_polygons(valid_geom):
            poly_boundaries.append(p.boundary)

    stage2_lines = stage1_leftovers + poly_boundaries
    stage2_polys, stage2_leftovers, _ = _build_full_polygons(
        lines=stage2_lines,
        snap_tolerance_m=snap_tolerance_m,
        min_area_m2=min_area_m2,
    )

    existing_polys = []
    for geom in gdf_polys_existing.geometry:
        valid_geom = _safe_make_valid(geom)
        existing_polys.extend(_flatten_polygons(valid_geom))

    accepted_stage2 = []
    for p in stage2_polys:
        p = _safe_make_valid(p)
        if p is None or p.is_empty:
            continue

        is_duplicate = False
        for e in existing_polys:
            inter = _safe_intersection_area(p, e)
            if inter / max(p.area, 1e-9) >= dedupe_overlap_ratio:
                is_duplicate = True
                break
        if is_duplicate:
            continue

        overlaps_existing = [e for e in existing_polys if _safe_intersects(p, e)]
        if overlaps_existing:
            union_with_overlap = unary_union(overlaps_existing)
            if p.area >= union_with_overlap.area * area_growth_ratio:
                accepted_stage2.append(p)
        else:
            accepted_stage2.append(p)

    # Build output frames
    cols = list(gdf_input.columns)

    def _make_frame(geoms, source_name):
        if not geoms:
            return gpd.GeoDataFrame(columns=cols, crs=projected_crs, geometry="geometry")
        frame = gpd.GeoDataFrame({"geometry": geoms}, crs=projected_crs)
        if "Name" in cols:
            frame["Name"] = source_name
        if "Description" in cols:
            frame["Description"] = source_name
        if "layer" in cols:
            frame["layer"] = source_name
        for c in cols:
            if c not in frame.columns:
                frame[c] = None
        return frame[cols]

    frame_stage1_polys = _make_frame(stage1_polys, "Derived from linework")
    frame_stage2_polys = _make_frame(accepted_stage2, "Derived from polygon+line fusion")
    frame_leftovers = _make_frame(stage2_leftovers, "Leftover linework")

    gdf_final_proj = gpd.GeoDataFrame(
        pd.concat(
            [
                gdf_non_line_non_poly[cols],
                gdf_polys_existing[cols],
                frame_stage1_polys,
                frame_stage2_polys,
                frame_leftovers,
            ],
            ignore_index=True,
        ),
        crs=projected_crs,
        geometry="geometry",
    )

    stats = {
        "input_line_segments": len(input_lines),
        "stage1_polygons_from_lines": len(stage1_polys),
        "stage1_leftover_segments": len(stage1_leftovers),
        "stage2_polygons_from_polygon_plus_line": len(accepted_stage2),
        "stage2_leftover_segments": len(stage2_leftovers),
    }

    return gdf_final_proj.to_crs(gdf_input.crs), stats

forests_gdf, conversion_stats = convert_lines_and_fuse_with_polygons(
    gdf_input=reserve_forests,
    snap_tolerance_m=15,   # strict; try 10-15 if small gaps are still missed
    min_area_m2=25.0,
    dedupe_overlap_ratio=0.98,
    area_growth_ratio=1.05,
 )

print("Conversion stats:", conversion_stats)
print("Geometry mix after final fusion:")
print(forests_gdf.geom_type.value_counts())

In [11]:
# Create folium map centered on India
india_center = [20.5937, 78.9629]
m = folium.Map(location=india_center, zoom_start=5, tiles="CartoDB positron")

# Define styles for different geometry types
styles = {
    'Polygon': {'fillColor': '#2d8659', 'color': '#000000', 'weight': 1, 'fillOpacity': 0.6},
    'MultiPolygon': {'fillColor': '#2d8659', 'color': '#000000', 'weight': 1, 'fillOpacity': 0.6},
    'LineString': {'color': '#ff6b6b', 'weight': 2, 'opacity': 0.8},
    'MultiLineString': {'color': '#ff6b6b', 'weight': 2, 'opacity': 0.8},
    'Point': {'color': '#4ecdc4', 'radius': 5, 'fillOpacity': 0.7}
}

# Add each geometry type as a separate feature group
if len(reserve_forests) > 0:
    for geom_type in reserve_forests.geometry.geom_type.unique():
        subset = reserve_forests[reserve_forests.geometry.geom_type == geom_type]
        
        fg = folium.FeatureGroup(name=f"{geom_type} ({len(subset)})", show=True)
        
        def style_fn(feature, gt=geom_type):
            return styles.get(gt, {'color': '#cccccc'})
        
        folium.GeoJson(
            subset.to_json(),
            style_function=style_fn,
            tooltip=folium.GeoJsonTooltip(
                fields=["Name", "state_code", "state_name", "category", "layer_name"],
                aliases=["Name", "State Code", "State Name", "Category", "Layer"]
            ),
        ).add_to(fg)
        
        fg.add_to(m)
    
    print(f"\n✓ Added {len(reserve_forests):,} reserve forest features to map")
else:
    print("\n⚠ No Reserve Forest features found")

# Add layer control
folium.LayerControl(collapsed=False).add_to(m)

# Save and display
output_file = notebook_dir / "reserve_forests_map.html"
m.save(str(output_file))
print(f"\n✓ Map saved to: {output_file.name}")
print("Open the HTML file in your browser to view the interactive map")

✓ Added 3,092 reserve forest features to map

✓ Map saved to: reserve_forests_map.html
Open the HTML file in your browser to view the interactive map